// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

type NetworkSecurityPerimetersProfile_STATUS struct {
	// Id: Fully qualified resource ID for the resource. E.g.
	// "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id *string `json:"id,omitempty"`

	// Name: The name of the resource
	Name *string `json:"name,omitempty"`

	// Properties: Properties of the network security perimeter profile
	Properties *NspProfileProperties_STATUS `json:"properties,omitempty"`

	// SystemData: Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *CommonSystemData_STATUS `json:"systemData,omitempty"`

	// Type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`
}

// Properties of NSP profile.
type NspProfileProperties_STATUS struct {
	// AccessRulesVersion: Version number that increases with every update to access rules within the profile.
	AccessRulesVersion *string `json:"accessRulesVersion,omitempty"`

	// DiagnosticSettingsVersion: Version number that increases with every update to diagnostic settings within the profile.
	DiagnosticSettingsVersion *string `json:"diagnosticSettingsVersion,omitempty"`
}
