// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_NetworkSecurityPerimetersProfilesAccessRule_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersProfilesAccessRule_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersProfilesAccessRule_Spec, NetworkSecurityPerimetersProfilesAccessRule_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersProfilesAccessRule_Spec runs a test to see if a specific instance of NetworkSecurityPerimetersProfilesAccessRule_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersProfilesAccessRule_Spec(subject NetworkSecurityPerimetersProfilesAccessRule_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersProfilesAccessRule_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersProfilesAccessRule_Spec instances for property testing - lazily instantiated by
// NetworkSecurityPerimetersProfilesAccessRule_SpecGenerator()
var networkSecurityPerimetersProfilesAccessRule_SpecGenerator gopter.Gen

// NetworkSecurityPerimetersProfilesAccessRule_SpecGenerator returns a generator of NetworkSecurityPerimetersProfilesAccessRule_Spec instances for property testing.
func NetworkSecurityPerimetersProfilesAccessRule_SpecGenerator() gopter.Gen {
	if networkSecurityPerimetersProfilesAccessRule_SpecGenerator != nil {
		return networkSecurityPerimetersProfilesAccessRule_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfilesAccessRule_Spec(generators)
	networkSecurityPerimetersProfilesAccessRule_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersProfilesAccessRule_Spec{}), generators)

	return networkSecurityPerimetersProfilesAccessRule_SpecGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfilesAccessRule_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfilesAccessRule_Spec(gens map[string]gopter.Gen) {
	gens["Name"] = gen.AlphaString()
}
