// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

type NetworkSecurityPerimetersLoggingConfiguration_STATUS struct {
	// Id: Fully qualified resource ID for the resource. E.g.
	// "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id *string `json:"id,omitempty"`

	// Name: The name of the resource
	Name *string `json:"name,omitempty"`

	// Properties: Properties of the NSP logging configuration.
	Properties *NspLoggingConfigurationProperties_STATUS `json:"properties,omitempty"`

	// SystemData: Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *CommonSystemData_STATUS `json:"systemData,omitempty"`

	// Type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`
}

// The NSP logging configuration properties.
type NspLoggingConfigurationProperties_STATUS struct {
	// EnabledLogCategories: The log categories to enable in the NSP logging configuration.
	EnabledLogCategories []string `json:"enabledLogCategories,omitempty"`

	// Version: The version of the NSP logging configuration.
	Version *string `json:"version,omitempty"`
}
