// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import "github.com/Azure/azure-service-operator/v2/pkg/genruntime"

type NetworkSecurityPerimetersResourceAssociation_Spec struct {
	Name string `json:"name,omitempty"`
}

var _ genruntime.ARMResourceSpec = &NetworkSecurityPerimetersResourceAssociation_Spec{}

// GetAPIVersion returns the ARM API version of the resource. This is always "2025-05-01"
func (association NetworkSecurityPerimetersResourceAssociation_Spec) GetAPIVersion() string {
	return "2025-05-01"
}

// GetName returns the Name of the resource
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) GetName() string {
	return association.Name
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Network/networkSecurityPerimeters/resourceAssociations"
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) GetType() string {
	return "Microsoft.Network/networkSecurityPerimeters/resourceAssociations"
}
