// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

type NetworkSecurityPerimetersLink_STATUS struct {
	// Id: Fully qualified resource ID for the resource. E.g.
	// "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id *string `json:"id,omitempty"`

	// Name: The name of the resource
	Name *string `json:"name,omitempty"`

	// Properties: Properties of the network security perimeter link resource.
	Properties *NspLinkProperties_STATUS `json:"properties,omitempty"`

	// SystemData: Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *CommonSystemData_STATUS `json:"systemData,omitempty"`

	// Type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`
}

// Properties of NSP Link resource.
type NspLinkProperties_STATUS struct {
	// AutoApprovedRemotePerimeterResourceId: Perimeter ARM Id for the remote NSP with which the link gets created in
	// Auto-approval mode. It should be used when the NSP admin have
	// Microsoft.Network/networkSecurityPerimeters/linkPerimeter/action permission on the remote NSP resource.
	AutoApprovedRemotePerimeterResourceId *string `json:"autoApprovedRemotePerimeterResourceId,omitempty"`

	// Description: A message passed to the owner of the remote NSP link resource with this connection request. In case of
	// Auto-approved flow, it is default to 'Auto Approved'. Restricted to 140 chars.
	Description *string `json:"description,omitempty"`

	// LocalInboundProfiles: Local Inbound profile names to which Inbound is allowed. Use ['*'] to allow inbound to all
	// profiles.
	LocalInboundProfiles []string `json:"localInboundProfiles,omitempty"`

	// LocalOutboundProfiles: Local Outbound profile names from which Outbound is allowed. In current version, it is readonly
	// property and it's value is set to ['*'] to allow outbound from all profiles. In later version, user will be able to
	// modify it.
	LocalOutboundProfiles []string `json:"localOutboundProfiles,omitempty"`

	// ProvisioningState: The provisioning state of the NSP Link resource.
	ProvisioningState *NSPLinkProvisioningState_STATUS `json:"provisioningState,omitempty"`

	// RemoteInboundProfiles: Remote Inbound profile names to which Inbound is allowed. Use ['*'] to allow inbound to all
	// profiles. This property can only be updated in auto-approval mode.
	RemoteInboundProfiles []string `json:"remoteInboundProfiles,omitempty"`

	// RemoteOutboundProfiles: Remote Outbound profile names from which Outbound is allowed. In current version, it is readonly
	// property and it's value is set to ['*'] to allow outbound from all profiles. In later version, user will be able to
	// modify it.
	RemoteOutboundProfiles []string `json:"remoteOutboundProfiles,omitempty"`

	// RemotePerimeterGuid: Remote NSP Guid with which the link gets created.
	RemotePerimeterGuid *string `json:"remotePerimeterGuid,omitempty"`

	// RemotePerimeterLocation: Remote NSP location with which the link gets created.
	RemotePerimeterLocation *string `json:"remotePerimeterLocation,omitempty"`

	// Status: The NSP link state.
	Status *NspLinkProperties_Status_STATUS `json:"status,omitempty"`
}

type NspLinkProperties_Status_STATUS string

const (
	NspLinkProperties_Status_STATUS_Approved     = NspLinkProperties_Status_STATUS("Approved")
	NspLinkProperties_Status_STATUS_Disconnected = NspLinkProperties_Status_STATUS("Disconnected")
	NspLinkProperties_Status_STATUS_Pending      = NspLinkProperties_Status_STATUS("Pending")
	NspLinkProperties_Status_STATUS_Rejected     = NspLinkProperties_Status_STATUS("Rejected")
)

// Mapping from string to NspLinkProperties_Status_STATUS
var nspLinkProperties_Status_STATUS_Values = map[string]NspLinkProperties_Status_STATUS{
	"approved":     NspLinkProperties_Status_STATUS_Approved,
	"disconnected": NspLinkProperties_Status_STATUS_Disconnected,
	"pending":      NspLinkProperties_Status_STATUS_Pending,
	"rejected":     NspLinkProperties_Status_STATUS_Rejected,
}

// The current provisioning state of NSP Link/LinkReference.
type NSPLinkProvisioningState_STATUS string

const (
	NSPLinkProvisioningState_STATUS_Accepted                = NSPLinkProvisioningState_STATUS("Accepted")
	NSPLinkProvisioningState_STATUS_Creating                = NSPLinkProvisioningState_STATUS("Creating")
	NSPLinkProvisioningState_STATUS_Deleting                = NSPLinkProvisioningState_STATUS("Deleting")
	NSPLinkProvisioningState_STATUS_Failed                  = NSPLinkProvisioningState_STATUS("Failed")
	NSPLinkProvisioningState_STATUS_Succeeded               = NSPLinkProvisioningState_STATUS("Succeeded")
	NSPLinkProvisioningState_STATUS_Updating                = NSPLinkProvisioningState_STATUS("Updating")
	NSPLinkProvisioningState_STATUS_WaitForRemoteCompletion = NSPLinkProvisioningState_STATUS("WaitForRemoteCompletion")
)

// Mapping from string to NSPLinkProvisioningState_STATUS
var nSPLinkProvisioningState_STATUS_Values = map[string]NSPLinkProvisioningState_STATUS{
	"accepted":                NSPLinkProvisioningState_STATUS_Accepted,
	"creating":                NSPLinkProvisioningState_STATUS_Creating,
	"deleting":                NSPLinkProvisioningState_STATUS_Deleting,
	"failed":                  NSPLinkProvisioningState_STATUS_Failed,
	"succeeded":               NSPLinkProvisioningState_STATUS_Succeeded,
	"updating":                NSPLinkProvisioningState_STATUS_Updating,
	"waitforremotecompletion": NSPLinkProvisioningState_STATUS_WaitForRemoteCompletion,
}
