// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

type NetworkSecurityPerimetersResourceAssociation_STATUS struct {
	// Id: Fully qualified resource ID for the resource. E.g.
	// "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id *string `json:"id,omitempty"`

	// Name: The name of the resource
	Name *string `json:"name,omitempty"`

	// Properties: Properties of the NSP resource association.
	Properties *NspAssociationProperties_STATUS `json:"properties,omitempty"`

	// SystemData: Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *CommonSystemData_STATUS `json:"systemData,omitempty"`

	// Type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`
}

type NspAssociationProperties_STATUS struct {
	// AccessMode: Access mode on the association.
	AccessMode *NspAssociationProperties_AccessMode_STATUS `json:"accessMode,omitempty"`

	// HasProvisioningIssues: Specifies if there are provisioning issues
	HasProvisioningIssues *string `json:"hasProvisioningIssues,omitempty"`

	// PrivateLinkResource: The PaaS resource to be associated.
	PrivateLinkResource *NetworkSecurityPerimeterSubResource_STATUS `json:"privateLinkResource,omitempty"`

	// Profile: Profile id to which the PaaS resource is associated.
	Profile *NetworkSecurityPerimeterSubResource_STATUS `json:"profile,omitempty"`

	// ProvisioningState: The provisioning state of the resource  association resource.
	ProvisioningState *NSPProvisioningState_STATUS `json:"provisioningState,omitempty"`
}

// Reference to another subresource.
type NetworkSecurityPerimeterSubResource_STATUS struct {
	// Id: Resource ID.
	Id *string `json:"id,omitempty"`
}

type NspAssociationProperties_AccessMode_STATUS string

const (
	NspAssociationProperties_AccessMode_STATUS_Audit    = NspAssociationProperties_AccessMode_STATUS("Audit")
	NspAssociationProperties_AccessMode_STATUS_Enforced = NspAssociationProperties_AccessMode_STATUS("Enforced")
	NspAssociationProperties_AccessMode_STATUS_Learning = NspAssociationProperties_AccessMode_STATUS("Learning")
)

// Mapping from string to NspAssociationProperties_AccessMode_STATUS
var nspAssociationProperties_AccessMode_STATUS_Values = map[string]NspAssociationProperties_AccessMode_STATUS{
	"audit":    NspAssociationProperties_AccessMode_STATUS_Audit,
	"enforced": NspAssociationProperties_AccessMode_STATUS_Enforced,
	"learning": NspAssociationProperties_AccessMode_STATUS_Learning,
}
