// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_NetworkSecurityPerimetersResourceAssociation_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersResourceAssociation_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersResourceAssociation_Spec, NetworkSecurityPerimetersResourceAssociation_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersResourceAssociation_Spec runs a test to see if a specific instance of NetworkSecurityPerimetersResourceAssociation_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersResourceAssociation_Spec(subject NetworkSecurityPerimetersResourceAssociation_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersResourceAssociation_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersResourceAssociation_Spec instances for property testing - lazily instantiated
// by NetworkSecurityPerimetersResourceAssociation_SpecGenerator()
var networkSecurityPerimetersResourceAssociation_SpecGenerator gopter.Gen

// NetworkSecurityPerimetersResourceAssociation_SpecGenerator returns a generator of NetworkSecurityPerimetersResourceAssociation_Spec instances for property testing.
func NetworkSecurityPerimetersResourceAssociation_SpecGenerator() gopter.Gen {
	if networkSecurityPerimetersResourceAssociation_SpecGenerator != nil {
		return networkSecurityPerimetersResourceAssociation_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_Spec(generators)
	networkSecurityPerimetersResourceAssociation_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersResourceAssociation_Spec{}), generators)

	return networkSecurityPerimetersResourceAssociation_SpecGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_Spec(gens map[string]gopter.Gen) {
	gens["Name"] = gen.AlphaString()
}
