// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_NetworkSecurityPerimetersLoggingConfiguration_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersLoggingConfiguration_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersLoggingConfiguration_Spec, NetworkSecurityPerimetersLoggingConfiguration_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersLoggingConfiguration_Spec runs a test to see if a specific instance of NetworkSecurityPerimetersLoggingConfiguration_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersLoggingConfiguration_Spec(subject NetworkSecurityPerimetersLoggingConfiguration_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersLoggingConfiguration_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersLoggingConfiguration_Spec instances for property testing - lazily instantiated
// by NetworkSecurityPerimetersLoggingConfiguration_SpecGenerator()
var networkSecurityPerimetersLoggingConfiguration_SpecGenerator gopter.Gen

// NetworkSecurityPerimetersLoggingConfiguration_SpecGenerator returns a generator of NetworkSecurityPerimetersLoggingConfiguration_Spec instances for property testing.
func NetworkSecurityPerimetersLoggingConfiguration_SpecGenerator() gopter.Gen {
	if networkSecurityPerimetersLoggingConfiguration_SpecGenerator != nil {
		return networkSecurityPerimetersLoggingConfiguration_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLoggingConfiguration_Spec(generators)
	networkSecurityPerimetersLoggingConfiguration_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLoggingConfiguration_Spec{}), generators)

	return networkSecurityPerimetersLoggingConfiguration_SpecGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLoggingConfiguration_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLoggingConfiguration_Spec(gens map[string]gopter.Gen) {
	gens["Name"] = gen.AlphaString()
}
