// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_NetworkSecurityPerimetersProfile_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersProfile_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersProfile_STATUS, NetworkSecurityPerimetersProfile_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersProfile_STATUS runs a test to see if a specific instance of NetworkSecurityPerimetersProfile_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersProfile_STATUS(subject NetworkSecurityPerimetersProfile_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersProfile_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersProfile_STATUS instances for property testing - lazily instantiated by
// NetworkSecurityPerimetersProfile_STATUSGenerator()
var networkSecurityPerimetersProfile_STATUSGenerator gopter.Gen

// NetworkSecurityPerimetersProfile_STATUSGenerator returns a generator of NetworkSecurityPerimetersProfile_STATUS instances for property testing.
// We first initialize networkSecurityPerimetersProfile_STATUSGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimetersProfile_STATUSGenerator() gopter.Gen {
	if networkSecurityPerimetersProfile_STATUSGenerator != nil {
		return networkSecurityPerimetersProfile_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS(generators)
	networkSecurityPerimetersProfile_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersProfile_STATUS{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS(generators)
	networkSecurityPerimetersProfile_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersProfile_STATUS{}), generators)

	return networkSecurityPerimetersProfile_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS(gens map[string]gopter.Gen) {
	gens["Properties"] = gen.PtrOf(NspProfileProperties_STATUSGenerator())
	gens["SystemData"] = gen.PtrOf(CommonSystemData_STATUSGenerator())
}

func Test_NspProfileProperties_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NspProfileProperties_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNspProfileProperties_STATUS, NspProfileProperties_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNspProfileProperties_STATUS runs a test to see if a specific instance of NspProfileProperties_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNspProfileProperties_STATUS(subject NspProfileProperties_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NspProfileProperties_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NspProfileProperties_STATUS instances for property testing - lazily instantiated by
// NspProfileProperties_STATUSGenerator()
var nspProfileProperties_STATUSGenerator gopter.Gen

// NspProfileProperties_STATUSGenerator returns a generator of NspProfileProperties_STATUS instances for property testing.
func NspProfileProperties_STATUSGenerator() gopter.Gen {
	if nspProfileProperties_STATUSGenerator != nil {
		return nspProfileProperties_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNspProfileProperties_STATUS(generators)
	nspProfileProperties_STATUSGenerator = gen.Struct(reflect.TypeOf(NspProfileProperties_STATUS{}), generators)

	return nspProfileProperties_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNspProfileProperties_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNspProfileProperties_STATUS(gens map[string]gopter.Gen) {
	gens["AccessRulesVersion"] = gen.PtrOf(gen.AlphaString())
	gens["DiagnosticSettingsVersion"] = gen.PtrOf(gen.AlphaString())
}
