// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_NetworkSecurityPerimetersLink_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersLink_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersLink_STATUS, NetworkSecurityPerimetersLink_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersLink_STATUS runs a test to see if a specific instance of NetworkSecurityPerimetersLink_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersLink_STATUS(subject NetworkSecurityPerimetersLink_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersLink_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersLink_STATUS instances for property testing - lazily instantiated by
// NetworkSecurityPerimetersLink_STATUSGenerator()
var networkSecurityPerimetersLink_STATUSGenerator gopter.Gen

// NetworkSecurityPerimetersLink_STATUSGenerator returns a generator of NetworkSecurityPerimetersLink_STATUS instances for property testing.
// We first initialize networkSecurityPerimetersLink_STATUSGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimetersLink_STATUSGenerator() gopter.Gen {
	if networkSecurityPerimetersLink_STATUSGenerator != nil {
		return networkSecurityPerimetersLink_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS(generators)
	networkSecurityPerimetersLink_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLink_STATUS{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS(generators)
	networkSecurityPerimetersLink_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLink_STATUS{}), generators)

	return networkSecurityPerimetersLink_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS(gens map[string]gopter.Gen) {
	gens["Properties"] = gen.PtrOf(NspLinkProperties_STATUSGenerator())
	gens["SystemData"] = gen.PtrOf(CommonSystemData_STATUSGenerator())
}

func Test_NspLinkProperties_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NspLinkProperties_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNspLinkProperties_STATUS, NspLinkProperties_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNspLinkProperties_STATUS runs a test to see if a specific instance of NspLinkProperties_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNspLinkProperties_STATUS(subject NspLinkProperties_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NspLinkProperties_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NspLinkProperties_STATUS instances for property testing - lazily instantiated by
// NspLinkProperties_STATUSGenerator()
var nspLinkProperties_STATUSGenerator gopter.Gen

// NspLinkProperties_STATUSGenerator returns a generator of NspLinkProperties_STATUS instances for property testing.
func NspLinkProperties_STATUSGenerator() gopter.Gen {
	if nspLinkProperties_STATUSGenerator != nil {
		return nspLinkProperties_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNspLinkProperties_STATUS(generators)
	nspLinkProperties_STATUSGenerator = gen.Struct(reflect.TypeOf(NspLinkProperties_STATUS{}), generators)

	return nspLinkProperties_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNspLinkProperties_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNspLinkProperties_STATUS(gens map[string]gopter.Gen) {
	gens["AutoApprovedRemotePerimeterResourceId"] = gen.PtrOf(gen.AlphaString())
	gens["Description"] = gen.PtrOf(gen.AlphaString())
	gens["LocalInboundProfiles"] = gen.SliceOf(gen.AlphaString())
	gens["LocalOutboundProfiles"] = gen.SliceOf(gen.AlphaString())
	gens["ProvisioningState"] = gen.PtrOf(gen.OneConstOf(
		NSPLinkProvisioningState_STATUS_Accepted,
		NSPLinkProvisioningState_STATUS_Creating,
		NSPLinkProvisioningState_STATUS_Deleting,
		NSPLinkProvisioningState_STATUS_Failed,
		NSPLinkProvisioningState_STATUS_Succeeded,
		NSPLinkProvisioningState_STATUS_Updating,
		NSPLinkProvisioningState_STATUS_WaitForRemoteCompletion))
	gens["RemoteInboundProfiles"] = gen.SliceOf(gen.AlphaString())
	gens["RemoteOutboundProfiles"] = gen.SliceOf(gen.AlphaString())
	gens["RemotePerimeterGuid"] = gen.PtrOf(gen.AlphaString())
	gens["RemotePerimeterLocation"] = gen.PtrOf(gen.AlphaString())
	gens["Status"] = gen.PtrOf(gen.OneConstOf(
		NspLinkProperties_Status_STATUS_Approved,
		NspLinkProperties_Status_STATUS_Disconnected,
		NspLinkProperties_Status_STATUS_Pending,
		NspLinkProperties_Status_STATUS_Rejected))
}
