apiVersion: network.azure.com/v20250501
kind: NetworkSecurityPerimetersLoggingConfiguration
metadata:
  name: sample-networksecurityperimetersloggingconfiguration
spec:
  enabledLogCategories:
    - NspPublicInboundPerimeterRulesDenied
    - NspPublicOutboundPerimeterRulesDenied
  owner:
    name: sample-networksecurityperimeter