// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package customizations

import (
	v20250701 "github.com/Azure/azure-service-operator/v2/api/network/v20250701"
	storage "github.com/Azure/azure-service-operator/v2/api/network/v20250701/storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
)

type NetworkSecurityPerimetersLinkExtension struct {
}

// GetExtendedResources Returns the KubernetesResource slice for Resource versions
func (extension *NetworkSecurityPerimetersLinkExtension) GetExtendedResources() []genruntime.KubernetesResource {
	return []genruntime.KubernetesResource{
		&v20250701.NetworkSecurityPerimetersLink{},
		&storage.NetworkSecurityPerimetersLink{}}
}
