// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package customizations

import (
	v20250501 "github.com/Azure/azure-service-operator/v2/api/network/v20250501"
	storage "github.com/Azure/azure-service-operator/v2/api/network/v20250501/storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
)

type NetworkSecurityPerimetersResourceAssociationExtension struct {
}

// GetExtendedResources Returns the KubernetesResource slice for Resource versions
func (extension *NetworkSecurityPerimetersResourceAssociationExtension) GetExtendedResources() []genruntime.KubernetesResource {
	return []genruntime.KubernetesResource{
		&v20250501.NetworkSecurityPerimetersResourceAssociation{},
		&storage.NetworkSecurityPerimetersResourceAssociation{}}
}
