// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v20250501

import (
	"fmt"
	arm "github.com/Azure/azure-service-operator/v2/api/network/v20250501/arm"
	storage "github.com/Azure/azure-service-operator/v2/api/network/v20250501/storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/conditions"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/configmaps"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/core"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/secrets"
	"github.com/rotisserie/eris"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/conversion"
)

// +kubebuilder:object:root=true
// +kubebuilder:resource:categories={azure,network}
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Severity",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].severity"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].message"
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-05-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/profiles/{profileName}
type NetworkSecurityPerimetersProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkSecurityPerimetersProfile_Spec   `json:"spec,omitempty"`
	Status            NetworkSecurityPerimetersProfile_STATUS `json:"status,omitempty"`
}

var _ conditions.Conditioner = &NetworkSecurityPerimetersProfile{}

// GetConditions returns the conditions of the resource
func (profile *NetworkSecurityPerimetersProfile) GetConditions() conditions.Conditions {
	return profile.Status.Conditions
}

// SetConditions sets the conditions on the resource status
func (profile *NetworkSecurityPerimetersProfile) SetConditions(conditions conditions.Conditions) {
	profile.Status.Conditions = conditions
}

var _ conversion.Convertible = &NetworkSecurityPerimetersProfile{}

// ConvertFrom populates our NetworkSecurityPerimetersProfile from the provided hub NetworkSecurityPerimetersProfile
func (profile *NetworkSecurityPerimetersProfile) ConvertFrom(hub conversion.Hub) error {
	source, ok := hub.(*storage.NetworkSecurityPerimetersProfile)
	if !ok {
		return fmt.Errorf("expected network/v20250501/storage/NetworkSecurityPerimetersProfile but received %T instead", hub)
	}

	return profile.AssignProperties_From_NetworkSecurityPerimetersProfile(source)
}

// ConvertTo populates the provided hub NetworkSecurityPerimetersProfile from our NetworkSecurityPerimetersProfile
func (profile *NetworkSecurityPerimetersProfile) ConvertTo(hub conversion.Hub) error {
	destination, ok := hub.(*storage.NetworkSecurityPerimetersProfile)
	if !ok {
		return fmt.Errorf("expected network/v20250501/storage/NetworkSecurityPerimetersProfile but received %T instead", hub)
	}

	return profile.AssignProperties_To_NetworkSecurityPerimetersProfile(destination)
}

var _ configmaps.Exporter = &NetworkSecurityPerimetersProfile{}

// ConfigMapDestinationExpressions returns the Spec.OperatorSpec.ConfigMapExpressions property
func (profile *NetworkSecurityPerimetersProfile) ConfigMapDestinationExpressions() []*core.DestinationExpression {
	if profile.Spec.OperatorSpec == nil {
		return nil
	}
	return profile.Spec.OperatorSpec.ConfigMapExpressions
}

var _ secrets.Exporter = &NetworkSecurityPerimetersProfile{}

// SecretDestinationExpressions returns the Spec.OperatorSpec.SecretExpressions property
func (profile *NetworkSecurityPerimetersProfile) SecretDestinationExpressions() []*core.DestinationExpression {
	if profile.Spec.OperatorSpec == nil {
		return nil
	}
	return profile.Spec.OperatorSpec.SecretExpressions
}

var _ genruntime.ImportableResource = &NetworkSecurityPerimetersProfile{}

// InitializeSpec initializes the spec for this resource from the given status
func (profile *NetworkSecurityPerimetersProfile) InitializeSpec(status genruntime.ConvertibleStatus) error {
	if s, ok := status.(*NetworkSecurityPerimetersProfile_STATUS); ok {
		return profile.Spec.Initialize_From_NetworkSecurityPerimetersProfile_STATUS(s)
	}

	return fmt.Errorf("expected Status of type NetworkSecurityPerimetersProfile_STATUS but received %T instead", status)
}

var _ genruntime.KubernetesResource = &NetworkSecurityPerimetersProfile{}

// AzureName returns the Azure name of the resource
func (profile *NetworkSecurityPerimetersProfile) AzureName() string {
	return profile.Spec.AzureName
}

// GetAPIVersion returns the ARM API version of the resource. This is always "2025-05-01"
func (profile NetworkSecurityPerimetersProfile) GetAPIVersion() string {
	return "2025-05-01"
}

// GetResourceScope returns the scope of the resource
func (profile *NetworkSecurityPerimetersProfile) GetResourceScope() genruntime.ResourceScope {
	return genruntime.ResourceScopeResourceGroup
}

// GetSpec returns the specification of this resource
func (profile *NetworkSecurityPerimetersProfile) GetSpec() genruntime.ConvertibleSpec {
	return &profile.Spec
}

// GetStatus returns the status of this resource
func (profile *NetworkSecurityPerimetersProfile) GetStatus() genruntime.ConvertibleStatus {
	return &profile.Status
}

// GetSupportedOperations returns the operations supported by the resource
func (profile *NetworkSecurityPerimetersProfile) GetSupportedOperations() []genruntime.ResourceOperation {
	return []genruntime.ResourceOperation{
		genruntime.ResourceOperationDelete,
		genruntime.ResourceOperationGet,
		genruntime.ResourceOperationPut,
	}
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Network/networkSecurityPerimeters/profiles"
func (profile *NetworkSecurityPerimetersProfile) GetType() string {
	return "Microsoft.Network/networkSecurityPerimeters/profiles"
}

// NewEmptyStatus returns a new empty (blank) status
func (profile *NetworkSecurityPerimetersProfile) NewEmptyStatus() genruntime.ConvertibleStatus {
	return &NetworkSecurityPerimetersProfile_STATUS{}
}

// Owner returns the ResourceReference of the owner
func (profile *NetworkSecurityPerimetersProfile) Owner() *genruntime.ResourceReference {
	if profile.Spec.Owner == nil {
		return nil
	}

	group, kind := genruntime.LookupOwnerGroupKind(profile.Spec)
	return profile.Spec.Owner.AsResourceReference(group, kind)
}

// SetStatus sets the status of this resource
func (profile *NetworkSecurityPerimetersProfile) SetStatus(status genruntime.ConvertibleStatus) error {
	// If we have exactly the right type of status, assign it
	if st, ok := status.(*NetworkSecurityPerimetersProfile_STATUS); ok {
		profile.Status = *st
		return nil
	}

	// Convert status to required version
	var st NetworkSecurityPerimetersProfile_STATUS
	err := status.ConvertStatusTo(&st)
	if err != nil {
		return eris.Wrap(err, "failed to convert status")
	}

	profile.Status = st
	return nil
}

// AssignProperties_From_NetworkSecurityPerimetersProfile populates our NetworkSecurityPerimetersProfile from the provided source NetworkSecurityPerimetersProfile
func (profile *NetworkSecurityPerimetersProfile) AssignProperties_From_NetworkSecurityPerimetersProfile(source *storage.NetworkSecurityPerimetersProfile) error {

	// ObjectMeta
	profile.ObjectMeta = *source.ObjectMeta.DeepCopy()

	// Spec
	var spec NetworkSecurityPerimetersProfile_Spec
	err := spec.AssignProperties_From_NetworkSecurityPerimetersProfile_Spec(&source.Spec)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_From_NetworkSecurityPerimetersProfile_Spec() to populate field Spec")
	}
	profile.Spec = spec

	// Status
	var status NetworkSecurityPerimetersProfile_STATUS
	err = status.AssignProperties_From_NetworkSecurityPerimetersProfile_STATUS(&source.Status)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_From_NetworkSecurityPerimetersProfile_STATUS() to populate field Status")
	}
	profile.Status = status

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersProfile populates the provided destination NetworkSecurityPerimetersProfile from our NetworkSecurityPerimetersProfile
func (profile *NetworkSecurityPerimetersProfile) AssignProperties_To_NetworkSecurityPerimetersProfile(destination *storage.NetworkSecurityPerimetersProfile) error {

	// ObjectMeta
	destination.ObjectMeta = *profile.ObjectMeta.DeepCopy()

	// Spec
	var spec storage.NetworkSecurityPerimetersProfile_Spec
	err := profile.Spec.AssignProperties_To_NetworkSecurityPerimetersProfile_Spec(&spec)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_To_NetworkSecurityPerimetersProfile_Spec() to populate field Spec")
	}
	destination.Spec = spec

	// Status
	var status storage.NetworkSecurityPerimetersProfile_STATUS
	err = profile.Status.AssignProperties_To_NetworkSecurityPerimetersProfile_STATUS(&status)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_To_NetworkSecurityPerimetersProfile_STATUS() to populate field Status")
	}
	destination.Status = status

	// No error
	return nil
}

// OriginalGVK returns a GroupValueKind for the original API version used to create the resource
func (profile *NetworkSecurityPerimetersProfile) OriginalGVK() *schema.GroupVersionKind {
	return &schema.GroupVersionKind{
		Group:   GroupVersion.Group,
		Version: profile.Spec.OriginalVersion(),
		Kind:    "NetworkSecurityPerimetersProfile",
	}
}

// +kubebuilder:object:root=true
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-05-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/profiles/{profileName}
type NetworkSecurityPerimetersProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkSecurityPerimetersProfile `json:"items"`
}

type NetworkSecurityPerimetersProfile_Spec struct {
	// +kubebuilder:validation:MaxLength=80
	// +kubebuilder:validation:Pattern="(^[a-zA-Z0-9]+[a-zA-Z0-9_.-]*[a-zA-Z0-9_]+$)|(^[a-zA-Z0-9]$)"
	// AzureName: The name of the resource in Azure. This is often the same as the name of the resource in Kubernetes but it
	// doesn't have to be.
	AzureName string `json:"azureName,omitempty"`

	// OperatorSpec: The specification for configuring operator behavior. This field is interpreted by the operator and not
	// passed directly to Azure
	OperatorSpec *NetworkSecurityPerimetersProfileOperatorSpec `json:"operatorSpec,omitempty"`

	// +kubebuilder:validation:Required
	// Owner: The owner of the resource. The owner controls where the resource goes when it is deployed. The owner also
	// controls the resources lifecycle. When the owner is deleted the resource will also be deleted. Owner is expected to be a
	// reference to a network.azure.com/NetworkSecurityPerimeter resource
	Owner *genruntime.KnownResourceReference `group:"network.azure.com" json:"owner,omitempty" kind:"NetworkSecurityPerimeter"`
}

var _ genruntime.ARMTransformer = &NetworkSecurityPerimetersProfile_Spec{}

// ConvertToARM converts from a Kubernetes CRD object to an ARM object
func (profile *NetworkSecurityPerimetersProfile_Spec) ConvertToARM(resolved genruntime.ConvertToARMResolvedDetails) (interface{}, error) {
	if profile == nil {
		return nil, nil
	}
	result := &arm.NetworkSecurityPerimetersProfile_Spec{}

	// Set property "Name":
	result.Name = resolved.Name
	return result, nil
}

// NewEmptyARMValue returns an empty ARM value suitable for deserializing into
func (profile *NetworkSecurityPerimetersProfile_Spec) NewEmptyARMValue() genruntime.ARMResourceStatus {
	return &arm.NetworkSecurityPerimetersProfile_Spec{}
}

// PopulateFromARM populates a Kubernetes CRD object from an Azure ARM object
func (profile *NetworkSecurityPerimetersProfile_Spec) PopulateFromARM(owner genruntime.ArbitraryOwnerReference, armInput interface{}) error {
	typedInput, ok := armInput.(arm.NetworkSecurityPerimetersProfile_Spec)
	if !ok {
		return fmt.Errorf("unexpected type supplied for PopulateFromARM() function. Expected arm.NetworkSecurityPerimetersProfile_Spec, got %T", armInput)
	}

	// Set property "AzureName":
	profile.SetAzureName(genruntime.ExtractKubernetesResourceNameFromARMName(typedInput.Name))

	// no assignment for property "OperatorSpec"

	// Set property "Owner":
	profile.Owner = &genruntime.KnownResourceReference{
		Name:  owner.Name,
		ARMID: owner.ARMID,
	}

	// No error
	return nil
}

var _ genruntime.ConvertibleSpec = &NetworkSecurityPerimetersProfile_Spec{}

// ConvertSpecFrom populates our NetworkSecurityPerimetersProfile_Spec from the provided source
func (profile *NetworkSecurityPerimetersProfile_Spec) ConvertSpecFrom(source genruntime.ConvertibleSpec) error {
	src, ok := source.(*storage.NetworkSecurityPerimetersProfile_Spec)
	if ok {
		// Populate our instance from source
		return profile.AssignProperties_From_NetworkSecurityPerimetersProfile_Spec(src)
	}

	// Convert to an intermediate form
	src = &storage.NetworkSecurityPerimetersProfile_Spec{}
	err := src.ConvertSpecFrom(source)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertSpecFrom()")
	}

	// Update our instance from src
	err = profile.AssignProperties_From_NetworkSecurityPerimetersProfile_Spec(src)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertSpecFrom()")
	}

	return nil
}

// ConvertSpecTo populates the provided destination from our NetworkSecurityPerimetersProfile_Spec
func (profile *NetworkSecurityPerimetersProfile_Spec) ConvertSpecTo(destination genruntime.ConvertibleSpec) error {
	dst, ok := destination.(*storage.NetworkSecurityPerimetersProfile_Spec)
	if ok {
		// Populate destination from our instance
		return profile.AssignProperties_To_NetworkSecurityPerimetersProfile_Spec(dst)
	}

	// Convert to an intermediate form
	dst = &storage.NetworkSecurityPerimetersProfile_Spec{}
	err := profile.AssignProperties_To_NetworkSecurityPerimetersProfile_Spec(dst)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertSpecTo()")
	}

	// Update dst from our instance
	err = dst.ConvertSpecTo(destination)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertSpecTo()")
	}

	return nil
}

// AssignProperties_From_NetworkSecurityPerimetersProfile_Spec populates our NetworkSecurityPerimetersProfile_Spec from the provided source NetworkSecurityPerimetersProfile_Spec
func (profile *NetworkSecurityPerimetersProfile_Spec) AssignProperties_From_NetworkSecurityPerimetersProfile_Spec(source *storage.NetworkSecurityPerimetersProfile_Spec) error {

	// AzureName
	profile.AzureName = source.AzureName

	// OperatorSpec
	if source.OperatorSpec != nil {
		var operatorSpec NetworkSecurityPerimetersProfileOperatorSpec
		err := operatorSpec.AssignProperties_From_NetworkSecurityPerimetersProfileOperatorSpec(source.OperatorSpec)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_From_NetworkSecurityPerimetersProfileOperatorSpec() to populate field OperatorSpec")
		}
		profile.OperatorSpec = &operatorSpec
	} else {
		profile.OperatorSpec = nil
	}

	// Owner
	if source.Owner != nil {
		owner := source.Owner.Copy()
		profile.Owner = &owner
	} else {
		profile.Owner = nil
	}

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersProfile_Spec populates the provided destination NetworkSecurityPerimetersProfile_Spec from our NetworkSecurityPerimetersProfile_Spec
func (profile *NetworkSecurityPerimetersProfile_Spec) AssignProperties_To_NetworkSecurityPerimetersProfile_Spec(destination *storage.NetworkSecurityPerimetersProfile_Spec) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// AzureName
	destination.AzureName = profile.AzureName

	// OperatorSpec
	if profile.OperatorSpec != nil {
		var operatorSpec storage.NetworkSecurityPerimetersProfileOperatorSpec
		err := profile.OperatorSpec.AssignProperties_To_NetworkSecurityPerimetersProfileOperatorSpec(&operatorSpec)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_To_NetworkSecurityPerimetersProfileOperatorSpec() to populate field OperatorSpec")
		}
		destination.OperatorSpec = &operatorSpec
	} else {
		destination.OperatorSpec = nil
	}

	// OriginalVersion
	destination.OriginalVersion = profile.OriginalVersion()

	// Owner
	if profile.Owner != nil {
		owner := profile.Owner.Copy()
		destination.Owner = &owner
	} else {
		destination.Owner = nil
	}

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

// Initialize_From_NetworkSecurityPerimetersProfile_STATUS populates our NetworkSecurityPerimetersProfile_Spec from the provided source NetworkSecurityPerimetersProfile_STATUS
func (profile *NetworkSecurityPerimetersProfile_Spec) Initialize_From_NetworkSecurityPerimetersProfile_STATUS(source *NetworkSecurityPerimetersProfile_STATUS) error {

	// No error
	return nil
}

// OriginalVersion returns the original API version used to create the resource.
func (profile *NetworkSecurityPerimetersProfile_Spec) OriginalVersion() string {
	return GroupVersion.Version
}

// SetAzureName sets the Azure name of the resource
func (profile *NetworkSecurityPerimetersProfile_Spec) SetAzureName(azureName string) {
	profile.AzureName = azureName
}

type NetworkSecurityPerimetersProfile_STATUS struct {
	// AccessRulesVersion: Version number that increases with every update to access rules within the profile.
	AccessRulesVersion *string `json:"accessRulesVersion,omitempty"`

	// Conditions: The observed state of the resource
	Conditions []conditions.Condition `json:"conditions,omitempty"`

	// DiagnosticSettingsVersion: Version number that increases with every update to diagnostic settings within the profile.
	DiagnosticSettingsVersion *string `json:"diagnosticSettingsVersion,omitempty"`

	// Id: Fully qualified resource ID for the resource. E.g.
	// "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id *string `json:"id,omitempty"`

	// Name: The name of the resource
	Name *string `json:"name,omitempty"`

	// SystemData: Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *CommonSystemData_STATUS `json:"systemData,omitempty"`

	// Type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`
}

var _ genruntime.ConvertibleStatus = &NetworkSecurityPerimetersProfile_STATUS{}

// ConvertStatusFrom populates our NetworkSecurityPerimetersProfile_STATUS from the provided source
func (profile *NetworkSecurityPerimetersProfile_STATUS) ConvertStatusFrom(source genruntime.ConvertibleStatus) error {
	src, ok := source.(*storage.NetworkSecurityPerimetersProfile_STATUS)
	if ok {
		// Populate our instance from source
		return profile.AssignProperties_From_NetworkSecurityPerimetersProfile_STATUS(src)
	}

	// Convert to an intermediate form
	src = &storage.NetworkSecurityPerimetersProfile_STATUS{}
	err := src.ConvertStatusFrom(source)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertStatusFrom()")
	}

	// Update our instance from src
	err = profile.AssignProperties_From_NetworkSecurityPerimetersProfile_STATUS(src)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertStatusFrom()")
	}

	return nil
}

// ConvertStatusTo populates the provided destination from our NetworkSecurityPerimetersProfile_STATUS
func (profile *NetworkSecurityPerimetersProfile_STATUS) ConvertStatusTo(destination genruntime.ConvertibleStatus) error {
	dst, ok := destination.(*storage.NetworkSecurityPerimetersProfile_STATUS)
	if ok {
		// Populate destination from our instance
		return profile.AssignProperties_To_NetworkSecurityPerimetersProfile_STATUS(dst)
	}

	// Convert to an intermediate form
	dst = &storage.NetworkSecurityPerimetersProfile_STATUS{}
	err := profile.AssignProperties_To_NetworkSecurityPerimetersProfile_STATUS(dst)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertStatusTo()")
	}

	// Update dst from our instance
	err = dst.ConvertStatusTo(destination)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertStatusTo()")
	}

	return nil
}

var _ genruntime.FromARMConverter = &NetworkSecurityPerimetersProfile_STATUS{}

// NewEmptyARMValue returns an empty ARM value suitable for deserializing into
func (profile *NetworkSecurityPerimetersProfile_STATUS) NewEmptyARMValue() genruntime.ARMResourceStatus {
	return &arm.NetworkSecurityPerimetersProfile_STATUS{}
}

// PopulateFromARM populates a Kubernetes CRD object from an Azure ARM object
func (profile *NetworkSecurityPerimetersProfile_STATUS) PopulateFromARM(owner genruntime.ArbitraryOwnerReference, armInput interface{}) error {
	typedInput, ok := armInput.(arm.NetworkSecurityPerimetersProfile_STATUS)
	if !ok {
		return fmt.Errorf("unexpected type supplied for PopulateFromARM() function. Expected arm.NetworkSecurityPerimetersProfile_STATUS, got %T", armInput)
	}

	// Set property "AccessRulesVersion":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.AccessRulesVersion != nil {
			accessRulesVersion := *typedInput.Properties.AccessRulesVersion
			profile.AccessRulesVersion = &accessRulesVersion
		}
	}

	// no assignment for property "Conditions"

	// Set property "DiagnosticSettingsVersion":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.DiagnosticSettingsVersion != nil {
			diagnosticSettingsVersion := *typedInput.Properties.DiagnosticSettingsVersion
			profile.DiagnosticSettingsVersion = &diagnosticSettingsVersion
		}
	}

	// Set property "Id":
	if typedInput.Id != nil {
		id := *typedInput.Id
		profile.Id = &id
	}

	// Set property "Name":
	if typedInput.Name != nil {
		name := *typedInput.Name
		profile.Name = &name
	}

	// Set property "SystemData":
	if typedInput.SystemData != nil {
		var systemData1 CommonSystemData_STATUS
		err := systemData1.PopulateFromARM(owner, *typedInput.SystemData)
		if err != nil {
			return err
		}
		systemData := systemData1
		profile.SystemData = &systemData
	}

	// Set property "Type":
	if typedInput.Type != nil {
		typeVar := *typedInput.Type
		profile.Type = &typeVar
	}

	// No error
	return nil
}

// AssignProperties_From_NetworkSecurityPerimetersProfile_STATUS populates our NetworkSecurityPerimetersProfile_STATUS from the provided source NetworkSecurityPerimetersProfile_STATUS
func (profile *NetworkSecurityPerimetersProfile_STATUS) AssignProperties_From_NetworkSecurityPerimetersProfile_STATUS(source *storage.NetworkSecurityPerimetersProfile_STATUS) error {

	// AccessRulesVersion
	profile.AccessRulesVersion = genruntime.ClonePointerToString(source.AccessRulesVersion)

	// Conditions
	profile.Conditions = genruntime.CloneSliceOfCondition(source.Conditions)

	// DiagnosticSettingsVersion
	profile.DiagnosticSettingsVersion = genruntime.ClonePointerToString(source.DiagnosticSettingsVersion)

	// Id
	profile.Id = genruntime.ClonePointerToString(source.Id)

	// Name
	profile.Name = genruntime.ClonePointerToString(source.Name)

	// SystemData
	if source.SystemData != nil {
		var systemDatum CommonSystemData_STATUS
		err := systemDatum.AssignProperties_From_CommonSystemData_STATUS(source.SystemData)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_From_CommonSystemData_STATUS() to populate field SystemData")
		}
		profile.SystemData = &systemDatum
	} else {
		profile.SystemData = nil
	}

	// Type
	profile.Type = genruntime.ClonePointerToString(source.Type)

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersProfile_STATUS populates the provided destination NetworkSecurityPerimetersProfile_STATUS from our NetworkSecurityPerimetersProfile_STATUS
func (profile *NetworkSecurityPerimetersProfile_STATUS) AssignProperties_To_NetworkSecurityPerimetersProfile_STATUS(destination *storage.NetworkSecurityPerimetersProfile_STATUS) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// AccessRulesVersion
	destination.AccessRulesVersion = genruntime.ClonePointerToString(profile.AccessRulesVersion)

	// Conditions
	destination.Conditions = genruntime.CloneSliceOfCondition(profile.Conditions)

	// DiagnosticSettingsVersion
	destination.DiagnosticSettingsVersion = genruntime.ClonePointerToString(profile.DiagnosticSettingsVersion)

	// Id
	destination.Id = genruntime.ClonePointerToString(profile.Id)

	// Name
	destination.Name = genruntime.ClonePointerToString(profile.Name)

	// SystemData
	if profile.SystemData != nil {
		var systemDatum storage.CommonSystemData_STATUS
		err := profile.SystemData.AssignProperties_To_CommonSystemData_STATUS(&systemDatum)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_To_CommonSystemData_STATUS() to populate field SystemData")
		}
		destination.SystemData = &systemDatum
	} else {
		destination.SystemData = nil
	}

	// Type
	destination.Type = genruntime.ClonePointerToString(profile.Type)

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

// Details for configuring operator behavior. Fields in this struct are interpreted by the operator directly rather than being passed to Azure
type NetworkSecurityPerimetersProfileOperatorSpec struct {
	// ConfigMapExpressions: configures where to place operator written dynamic ConfigMaps (created with CEL expressions).
	ConfigMapExpressions []*core.DestinationExpression `json:"configMapExpressions,omitempty"`

	// SecretExpressions: configures where to place operator written dynamic secrets (created with CEL expressions).
	SecretExpressions []*core.DestinationExpression `json:"secretExpressions,omitempty"`
}

// AssignProperties_From_NetworkSecurityPerimetersProfileOperatorSpec populates our NetworkSecurityPerimetersProfileOperatorSpec from the provided source NetworkSecurityPerimetersProfileOperatorSpec
func (operator *NetworkSecurityPerimetersProfileOperatorSpec) AssignProperties_From_NetworkSecurityPerimetersProfileOperatorSpec(source *storage.NetworkSecurityPerimetersProfileOperatorSpec) error {

	// ConfigMapExpressions
	if source.ConfigMapExpressions != nil {
		configMapExpressionList := make([]*core.DestinationExpression, len(source.ConfigMapExpressions))
		for configMapExpressionIndex, configMapExpressionItem := range source.ConfigMapExpressions {
			if configMapExpressionItem != nil {
				configMapExpression := *configMapExpressionItem.DeepCopy()
				configMapExpressionList[configMapExpressionIndex] = &configMapExpression
			} else {
				configMapExpressionList[configMapExpressionIndex] = nil
			}
		}
		operator.ConfigMapExpressions = configMapExpressionList
	} else {
		operator.ConfigMapExpressions = nil
	}

	// SecretExpressions
	if source.SecretExpressions != nil {
		secretExpressionList := make([]*core.DestinationExpression, len(source.SecretExpressions))
		for secretExpressionIndex, secretExpressionItem := range source.SecretExpressions {
			if secretExpressionItem != nil {
				secretExpression := *secretExpressionItem.DeepCopy()
				secretExpressionList[secretExpressionIndex] = &secretExpression
			} else {
				secretExpressionList[secretExpressionIndex] = nil
			}
		}
		operator.SecretExpressions = secretExpressionList
	} else {
		operator.SecretExpressions = nil
	}

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersProfileOperatorSpec populates the provided destination NetworkSecurityPerimetersProfileOperatorSpec from our NetworkSecurityPerimetersProfileOperatorSpec
func (operator *NetworkSecurityPerimetersProfileOperatorSpec) AssignProperties_To_NetworkSecurityPerimetersProfileOperatorSpec(destination *storage.NetworkSecurityPerimetersProfileOperatorSpec) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// ConfigMapExpressions
	if operator.ConfigMapExpressions != nil {
		configMapExpressionList := make([]*core.DestinationExpression, len(operator.ConfigMapExpressions))
		for configMapExpressionIndex, configMapExpressionItem := range operator.ConfigMapExpressions {
			if configMapExpressionItem != nil {
				configMapExpression := *configMapExpressionItem.DeepCopy()
				configMapExpressionList[configMapExpressionIndex] = &configMapExpression
			} else {
				configMapExpressionList[configMapExpressionIndex] = nil
			}
		}
		destination.ConfigMapExpressions = configMapExpressionList
	} else {
		destination.ConfigMapExpressions = nil
	}

	// SecretExpressions
	if operator.SecretExpressions != nil {
		secretExpressionList := make([]*core.DestinationExpression, len(operator.SecretExpressions))
		for secretExpressionIndex, secretExpressionItem := range operator.SecretExpressions {
			if secretExpressionItem != nil {
				secretExpression := *secretExpressionItem.DeepCopy()
				secretExpressionList[secretExpressionIndex] = &secretExpression
			} else {
				secretExpressionList[secretExpressionIndex] = nil
			}
		}
		destination.SecretExpressions = secretExpressionList
	} else {
		destination.SecretExpressions = nil
	}

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

func init() {
	SchemeBuilder.Register(&NetworkSecurityPerimetersProfile{}, &NetworkSecurityPerimetersProfileList{})
}
