// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v20250501

import (
	"fmt"
	arm "github.com/Azure/azure-service-operator/v2/api/network/v20250501/arm"
	storage "github.com/Azure/azure-service-operator/v2/api/network/v20250501/storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/conditions"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/configmaps"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/core"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/secrets"
	"github.com/rotisserie/eris"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/conversion"
)

// +kubebuilder:object:root=true
// +kubebuilder:resource:categories={azure,network}
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Severity",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].severity"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].message"
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-05-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/profiles/{profileName}/accessRules/{accessRuleName}
type NetworkSecurityPerimetersProfilesAccessRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkSecurityPerimetersProfilesAccessRule_Spec   `json:"spec,omitempty"`
	Status            NetworkSecurityPerimetersProfilesAccessRule_STATUS `json:"status,omitempty"`
}

var _ conditions.Conditioner = &NetworkSecurityPerimetersProfilesAccessRule{}

// GetConditions returns the conditions of the resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) GetConditions() conditions.Conditions {
	return rule.Status.Conditions
}

// SetConditions sets the conditions on the resource status
func (rule *NetworkSecurityPerimetersProfilesAccessRule) SetConditions(conditions conditions.Conditions) {
	rule.Status.Conditions = conditions
}

var _ conversion.Convertible = &NetworkSecurityPerimetersProfilesAccessRule{}

// ConvertFrom populates our NetworkSecurityPerimetersProfilesAccessRule from the provided hub NetworkSecurityPerimetersProfilesAccessRule
func (rule *NetworkSecurityPerimetersProfilesAccessRule) ConvertFrom(hub conversion.Hub) error {
	source, ok := hub.(*storage.NetworkSecurityPerimetersProfilesAccessRule)
	if !ok {
		return fmt.Errorf("expected network/v20250501/storage/NetworkSecurityPerimetersProfilesAccessRule but received %T instead", hub)
	}

	return rule.AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule(source)
}

// ConvertTo populates the provided hub NetworkSecurityPerimetersProfilesAccessRule from our NetworkSecurityPerimetersProfilesAccessRule
func (rule *NetworkSecurityPerimetersProfilesAccessRule) ConvertTo(hub conversion.Hub) error {
	destination, ok := hub.(*storage.NetworkSecurityPerimetersProfilesAccessRule)
	if !ok {
		return fmt.Errorf("expected network/v20250501/storage/NetworkSecurityPerimetersProfilesAccessRule but received %T instead", hub)
	}

	return rule.AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule(destination)
}

var _ configmaps.Exporter = &NetworkSecurityPerimetersProfilesAccessRule{}

// ConfigMapDestinationExpressions returns the Spec.OperatorSpec.ConfigMapExpressions property
func (rule *NetworkSecurityPerimetersProfilesAccessRule) ConfigMapDestinationExpressions() []*core.DestinationExpression {
	if rule.Spec.OperatorSpec == nil {
		return nil
	}
	return rule.Spec.OperatorSpec.ConfigMapExpressions
}

var _ secrets.Exporter = &NetworkSecurityPerimetersProfilesAccessRule{}

// SecretDestinationExpressions returns the Spec.OperatorSpec.SecretExpressions property
func (rule *NetworkSecurityPerimetersProfilesAccessRule) SecretDestinationExpressions() []*core.DestinationExpression {
	if rule.Spec.OperatorSpec == nil {
		return nil
	}
	return rule.Spec.OperatorSpec.SecretExpressions
}

var _ genruntime.ImportableResource = &NetworkSecurityPerimetersProfilesAccessRule{}

// InitializeSpec initializes the spec for this resource from the given status
func (rule *NetworkSecurityPerimetersProfilesAccessRule) InitializeSpec(status genruntime.ConvertibleStatus) error {
	if s, ok := status.(*NetworkSecurityPerimetersProfilesAccessRule_STATUS); ok {
		return rule.Spec.Initialize_From_NetworkSecurityPerimetersProfilesAccessRule_STATUS(s)
	}

	return fmt.Errorf("expected Status of type NetworkSecurityPerimetersProfilesAccessRule_STATUS but received %T instead", status)
}

var _ genruntime.KubernetesResource = &NetworkSecurityPerimetersProfilesAccessRule{}

// AzureName returns the Azure name of the resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) AzureName() string {
	return rule.Spec.AzureName
}

// GetAPIVersion returns the ARM API version of the resource. This is always "2025-05-01"
func (rule NetworkSecurityPerimetersProfilesAccessRule) GetAPIVersion() string {
	return "2025-05-01"
}

// GetResourceScope returns the scope of the resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) GetResourceScope() genruntime.ResourceScope {
	return genruntime.ResourceScopeResourceGroup
}

// GetSpec returns the specification of this resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) GetSpec() genruntime.ConvertibleSpec {
	return &rule.Spec
}

// GetStatus returns the status of this resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) GetStatus() genruntime.ConvertibleStatus {
	return &rule.Status
}

// GetSupportedOperations returns the operations supported by the resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) GetSupportedOperations() []genruntime.ResourceOperation {
	return []genruntime.ResourceOperation{
		genruntime.ResourceOperationDelete,
		genruntime.ResourceOperationGet,
		genruntime.ResourceOperationPut,
	}
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Network/networkSecurityPerimeters/profiles/accessRules"
func (rule *NetworkSecurityPerimetersProfilesAccessRule) GetType() string {
	return "Microsoft.Network/networkSecurityPerimeters/profiles/accessRules"
}

// NewEmptyStatus returns a new empty (blank) status
func (rule *NetworkSecurityPerimetersProfilesAccessRule) NewEmptyStatus() genruntime.ConvertibleStatus {
	return &NetworkSecurityPerimetersProfilesAccessRule_STATUS{}
}

// Owner returns the ResourceReference of the owner
func (rule *NetworkSecurityPerimetersProfilesAccessRule) Owner() *genruntime.ResourceReference {
	if rule.Spec.Owner == nil {
		return nil
	}

	group, kind := genruntime.LookupOwnerGroupKind(rule.Spec)
	return rule.Spec.Owner.AsResourceReference(group, kind)
}

// SetStatus sets the status of this resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) SetStatus(status genruntime.ConvertibleStatus) error {
	// If we have exactly the right type of status, assign it
	if st, ok := status.(*NetworkSecurityPerimetersProfilesAccessRule_STATUS); ok {
		rule.Status = *st
		return nil
	}

	// Convert status to required version
	var st NetworkSecurityPerimetersProfilesAccessRule_STATUS
	err := status.ConvertStatusTo(&st)
	if err != nil {
		return eris.Wrap(err, "failed to convert status")
	}

	rule.Status = st
	return nil
}

// AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule populates our NetworkSecurityPerimetersProfilesAccessRule from the provided source NetworkSecurityPerimetersProfilesAccessRule
func (rule *NetworkSecurityPerimetersProfilesAccessRule) AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule(source *storage.NetworkSecurityPerimetersProfilesAccessRule) error {

	// ObjectMeta
	rule.ObjectMeta = *source.ObjectMeta.DeepCopy()

	// Spec
	var spec NetworkSecurityPerimetersProfilesAccessRule_Spec
	err := spec.AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule_Spec(&source.Spec)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule_Spec() to populate field Spec")
	}
	rule.Spec = spec

	// Status
	var status NetworkSecurityPerimetersProfilesAccessRule_STATUS
	err = status.AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule_STATUS(&source.Status)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule_STATUS() to populate field Status")
	}
	rule.Status = status

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule populates the provided destination NetworkSecurityPerimetersProfilesAccessRule from our NetworkSecurityPerimetersProfilesAccessRule
func (rule *NetworkSecurityPerimetersProfilesAccessRule) AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule(destination *storage.NetworkSecurityPerimetersProfilesAccessRule) error {

	// ObjectMeta
	destination.ObjectMeta = *rule.ObjectMeta.DeepCopy()

	// Spec
	var spec storage.NetworkSecurityPerimetersProfilesAccessRule_Spec
	err := rule.Spec.AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule_Spec(&spec)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule_Spec() to populate field Spec")
	}
	destination.Spec = spec

	// Status
	var status storage.NetworkSecurityPerimetersProfilesAccessRule_STATUS
	err = rule.Status.AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule_STATUS(&status)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule_STATUS() to populate field Status")
	}
	destination.Status = status

	// No error
	return nil
}

// OriginalGVK returns a GroupValueKind for the original API version used to create the resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) OriginalGVK() *schema.GroupVersionKind {
	return &schema.GroupVersionKind{
		Group:   GroupVersion.Group,
		Version: rule.Spec.OriginalVersion(),
		Kind:    "NetworkSecurityPerimetersProfilesAccessRule",
	}
}

// +kubebuilder:object:root=true
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-05-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/profiles/{profileName}/accessRules/{accessRuleName}
type NetworkSecurityPerimetersProfilesAccessRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkSecurityPerimetersProfilesAccessRule `json:"items"`
}

type NetworkSecurityPerimetersProfilesAccessRule_Spec struct {
	// +kubebuilder:validation:MaxLength=80
	// +kubebuilder:validation:Pattern="(^[a-zA-Z0-9]+[a-zA-Z0-9_.-]*[a-zA-Z0-9_]+$)|(^[a-zA-Z0-9]$)"
	// AzureName: The name of the resource in Azure. This is often the same as the name of the resource in Kubernetes but it
	// doesn't have to be.
	AzureName string `json:"azureName,omitempty"`

	// OperatorSpec: The specification for configuring operator behavior. This field is interpreted by the operator and not
	// passed directly to Azure
	OperatorSpec *NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec `json:"operatorSpec,omitempty"`

	// +kubebuilder:validation:Required
	// Owner: The owner of the resource. The owner controls where the resource goes when it is deployed. The owner also
	// controls the resources lifecycle. When the owner is deleted the resource will also be deleted. Owner is expected to be a
	// reference to a network.azure.com/NetworkSecurityPerimetersProfile resource
	Owner *genruntime.KnownResourceReference `group:"network.azure.com" json:"owner,omitempty" kind:"NetworkSecurityPerimetersProfile"`
}

var _ genruntime.ARMTransformer = &NetworkSecurityPerimetersProfilesAccessRule_Spec{}

// ConvertToARM converts from a Kubernetes CRD object to an ARM object
func (rule *NetworkSecurityPerimetersProfilesAccessRule_Spec) ConvertToARM(resolved genruntime.ConvertToARMResolvedDetails) (interface{}, error) {
	if rule == nil {
		return nil, nil
	}
	result := &arm.NetworkSecurityPerimetersProfilesAccessRule_Spec{}

	// Set property "Name":
	result.Name = resolved.Name
	return result, nil
}

// NewEmptyARMValue returns an empty ARM value suitable for deserializing into
func (rule *NetworkSecurityPerimetersProfilesAccessRule_Spec) NewEmptyARMValue() genruntime.ARMResourceStatus {
	return &arm.NetworkSecurityPerimetersProfilesAccessRule_Spec{}
}

// PopulateFromARM populates a Kubernetes CRD object from an Azure ARM object
func (rule *NetworkSecurityPerimetersProfilesAccessRule_Spec) PopulateFromARM(owner genruntime.ArbitraryOwnerReference, armInput interface{}) error {
	typedInput, ok := armInput.(arm.NetworkSecurityPerimetersProfilesAccessRule_Spec)
	if !ok {
		return fmt.Errorf("unexpected type supplied for PopulateFromARM() function. Expected arm.NetworkSecurityPerimetersProfilesAccessRule_Spec, got %T", armInput)
	}

	// Set property "AzureName":
	rule.SetAzureName(genruntime.ExtractKubernetesResourceNameFromARMName(typedInput.Name))

	// no assignment for property "OperatorSpec"

	// Set property "Owner":
	rule.Owner = &genruntime.KnownResourceReference{
		Name:  owner.Name,
		ARMID: owner.ARMID,
	}

	// No error
	return nil
}

var _ genruntime.ConvertibleSpec = &NetworkSecurityPerimetersProfilesAccessRule_Spec{}

// ConvertSpecFrom populates our NetworkSecurityPerimetersProfilesAccessRule_Spec from the provided source
func (rule *NetworkSecurityPerimetersProfilesAccessRule_Spec) ConvertSpecFrom(source genruntime.ConvertibleSpec) error {
	src, ok := source.(*storage.NetworkSecurityPerimetersProfilesAccessRule_Spec)
	if ok {
		// Populate our instance from source
		return rule.AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule_Spec(src)
	}

	// Convert to an intermediate form
	src = &storage.NetworkSecurityPerimetersProfilesAccessRule_Spec{}
	err := src.ConvertSpecFrom(source)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertSpecFrom()")
	}

	// Update our instance from src
	err = rule.AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule_Spec(src)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertSpecFrom()")
	}

	return nil
}

// ConvertSpecTo populates the provided destination from our NetworkSecurityPerimetersProfilesAccessRule_Spec
func (rule *NetworkSecurityPerimetersProfilesAccessRule_Spec) ConvertSpecTo(destination genruntime.ConvertibleSpec) error {
	dst, ok := destination.(*storage.NetworkSecurityPerimetersProfilesAccessRule_Spec)
	if ok {
		// Populate destination from our instance
		return rule.AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule_Spec(dst)
	}

	// Convert to an intermediate form
	dst = &storage.NetworkSecurityPerimetersProfilesAccessRule_Spec{}
	err := rule.AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule_Spec(dst)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertSpecTo()")
	}

	// Update dst from our instance
	err = dst.ConvertSpecTo(destination)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertSpecTo()")
	}

	return nil
}

// AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule_Spec populates our NetworkSecurityPerimetersProfilesAccessRule_Spec from the provided source NetworkSecurityPerimetersProfilesAccessRule_Spec
func (rule *NetworkSecurityPerimetersProfilesAccessRule_Spec) AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule_Spec(source *storage.NetworkSecurityPerimetersProfilesAccessRule_Spec) error {

	// AzureName
	rule.AzureName = source.AzureName

	// OperatorSpec
	if source.OperatorSpec != nil {
		var operatorSpec NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec
		err := operatorSpec.AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec(source.OperatorSpec)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec() to populate field OperatorSpec")
		}
		rule.OperatorSpec = &operatorSpec
	} else {
		rule.OperatorSpec = nil
	}

	// Owner
	if source.Owner != nil {
		owner := source.Owner.Copy()
		rule.Owner = &owner
	} else {
		rule.Owner = nil
	}

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule_Spec populates the provided destination NetworkSecurityPerimetersProfilesAccessRule_Spec from our NetworkSecurityPerimetersProfilesAccessRule_Spec
func (rule *NetworkSecurityPerimetersProfilesAccessRule_Spec) AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule_Spec(destination *storage.NetworkSecurityPerimetersProfilesAccessRule_Spec) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// AzureName
	destination.AzureName = rule.AzureName

	// OperatorSpec
	if rule.OperatorSpec != nil {
		var operatorSpec storage.NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec
		err := rule.OperatorSpec.AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec(&operatorSpec)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec() to populate field OperatorSpec")
		}
		destination.OperatorSpec = &operatorSpec
	} else {
		destination.OperatorSpec = nil
	}

	// OriginalVersion
	destination.OriginalVersion = rule.OriginalVersion()

	// Owner
	if rule.Owner != nil {
		owner := rule.Owner.Copy()
		destination.Owner = &owner
	} else {
		destination.Owner = nil
	}

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

// Initialize_From_NetworkSecurityPerimetersProfilesAccessRule_STATUS populates our NetworkSecurityPerimetersProfilesAccessRule_Spec from the provided source NetworkSecurityPerimetersProfilesAccessRule_STATUS
func (rule *NetworkSecurityPerimetersProfilesAccessRule_Spec) Initialize_From_NetworkSecurityPerimetersProfilesAccessRule_STATUS(source *NetworkSecurityPerimetersProfilesAccessRule_STATUS) error {

	// No error
	return nil
}

// OriginalVersion returns the original API version used to create the resource.
func (rule *NetworkSecurityPerimetersProfilesAccessRule_Spec) OriginalVersion() string {
	return GroupVersion.Version
}

// SetAzureName sets the Azure name of the resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule_Spec) SetAzureName(azureName string) {
	rule.AzureName = azureName
}

type NetworkSecurityPerimetersProfilesAccessRule_STATUS struct {
	// AddressPrefixes: Inbound address prefixes (IPv4/IPv6)
	AddressPrefixes []string `json:"addressPrefixes,omitempty"`

	// Conditions: The observed state of the resource
	Conditions []conditions.Condition `json:"conditions,omitempty"`

	// Direction: Direction that specifies whether the access rules is inbound/outbound.
	Direction *NspAccessRuleProperties_Direction_STATUS `json:"direction,omitempty"`

	// EmailAddresses: Outbound rules in email address format. This access rule type is currently unavailable for use.
	EmailAddresses []string `json:"emailAddresses,omitempty"`

	// FullyQualifiedDomainNames: Outbound rules in fully qualified domain name format.
	FullyQualifiedDomainNames []string `json:"fullyQualifiedDomainNames,omitempty"`

	// Id: Fully qualified resource ID for the resource. E.g.
	// "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id *string `json:"id,omitempty"`

	// Name: The name of the resource
	Name *string `json:"name,omitempty"`

	// NetworkSecurityPerimeters: Rule specified by the perimeter id.
	NetworkSecurityPerimeters []PerimeterBasedAccessRule_STATUS `json:"networkSecurityPerimeters,omitempty"`

	// PhoneNumbers: Outbound rules in phone number format. This access rule type is currently unavailable for use.
	PhoneNumbers []string `json:"phoneNumbers,omitempty"`

	// ProvisioningState: The provisioning state of the scope assignment resource.
	ProvisioningState *NSPProvisioningState_STATUS `json:"provisioningState,omitempty"`

	// ServiceTags: Inbound rules of type service tag. This access rule type is currently unavailable for use.
	ServiceTags []string `json:"serviceTags,omitempty"`

	// Subscriptions: List of subscription ids
	Subscriptions []SubscriptionId_STATUS `json:"subscriptions,omitempty"`

	// SystemData: Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *CommonSystemData_STATUS `json:"systemData,omitempty"`

	// Type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`
}

var _ genruntime.ConvertibleStatus = &NetworkSecurityPerimetersProfilesAccessRule_STATUS{}

// ConvertStatusFrom populates our NetworkSecurityPerimetersProfilesAccessRule_STATUS from the provided source
func (rule *NetworkSecurityPerimetersProfilesAccessRule_STATUS) ConvertStatusFrom(source genruntime.ConvertibleStatus) error {
	src, ok := source.(*storage.NetworkSecurityPerimetersProfilesAccessRule_STATUS)
	if ok {
		// Populate our instance from source
		return rule.AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule_STATUS(src)
	}

	// Convert to an intermediate form
	src = &storage.NetworkSecurityPerimetersProfilesAccessRule_STATUS{}
	err := src.ConvertStatusFrom(source)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertStatusFrom()")
	}

	// Update our instance from src
	err = rule.AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule_STATUS(src)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertStatusFrom()")
	}

	return nil
}

// ConvertStatusTo populates the provided destination from our NetworkSecurityPerimetersProfilesAccessRule_STATUS
func (rule *NetworkSecurityPerimetersProfilesAccessRule_STATUS) ConvertStatusTo(destination genruntime.ConvertibleStatus) error {
	dst, ok := destination.(*storage.NetworkSecurityPerimetersProfilesAccessRule_STATUS)
	if ok {
		// Populate destination from our instance
		return rule.AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule_STATUS(dst)
	}

	// Convert to an intermediate form
	dst = &storage.NetworkSecurityPerimetersProfilesAccessRule_STATUS{}
	err := rule.AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule_STATUS(dst)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertStatusTo()")
	}

	// Update dst from our instance
	err = dst.ConvertStatusTo(destination)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertStatusTo()")
	}

	return nil
}

var _ genruntime.FromARMConverter = &NetworkSecurityPerimetersProfilesAccessRule_STATUS{}

// NewEmptyARMValue returns an empty ARM value suitable for deserializing into
func (rule *NetworkSecurityPerimetersProfilesAccessRule_STATUS) NewEmptyARMValue() genruntime.ARMResourceStatus {
	return &arm.NetworkSecurityPerimetersProfilesAccessRule_STATUS{}
}

// PopulateFromARM populates a Kubernetes CRD object from an Azure ARM object
func (rule *NetworkSecurityPerimetersProfilesAccessRule_STATUS) PopulateFromARM(owner genruntime.ArbitraryOwnerReference, armInput interface{}) error {
	typedInput, ok := armInput.(arm.NetworkSecurityPerimetersProfilesAccessRule_STATUS)
	if !ok {
		return fmt.Errorf("unexpected type supplied for PopulateFromARM() function. Expected arm.NetworkSecurityPerimetersProfilesAccessRule_STATUS, got %T", armInput)
	}

	// Set property "AddressPrefixes":
	// copying flattened property:
	if typedInput.Properties != nil {
		for _, item := range typedInput.Properties.AddressPrefixes {
			rule.AddressPrefixes = append(rule.AddressPrefixes, item)
		}
	}

	// no assignment for property "Conditions"

	// Set property "Direction":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.Direction != nil {
			var temp string
			temp = string(*typedInput.Properties.Direction)
			direction := NspAccessRuleProperties_Direction_STATUS(temp)
			rule.Direction = &direction
		}
	}

	// Set property "EmailAddresses":
	// copying flattened property:
	if typedInput.Properties != nil {
		for _, item := range typedInput.Properties.EmailAddresses {
			rule.EmailAddresses = append(rule.EmailAddresses, item)
		}
	}

	// Set property "FullyQualifiedDomainNames":
	// copying flattened property:
	if typedInput.Properties != nil {
		for _, item := range typedInput.Properties.FullyQualifiedDomainNames {
			rule.FullyQualifiedDomainNames = append(rule.FullyQualifiedDomainNames, item)
		}
	}

	// Set property "Id":
	if typedInput.Id != nil {
		id := *typedInput.Id
		rule.Id = &id
	}

	// Set property "Name":
	if typedInput.Name != nil {
		name := *typedInput.Name
		rule.Name = &name
	}

	// Set property "NetworkSecurityPerimeters":
	// copying flattened property:
	if typedInput.Properties != nil {
		for _, item := range typedInput.Properties.NetworkSecurityPerimeters {
			var item1 PerimeterBasedAccessRule_STATUS
			err := item1.PopulateFromARM(owner, item)
			if err != nil {
				return err
			}
			rule.NetworkSecurityPerimeters = append(rule.NetworkSecurityPerimeters, item1)
		}
	}

	// Set property "PhoneNumbers":
	// copying flattened property:
	if typedInput.Properties != nil {
		for _, item := range typedInput.Properties.PhoneNumbers {
			rule.PhoneNumbers = append(rule.PhoneNumbers, item)
		}
	}

	// Set property "ProvisioningState":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.ProvisioningState != nil {
			var temp string
			temp = string(*typedInput.Properties.ProvisioningState)
			provisioningState := NSPProvisioningState_STATUS(temp)
			rule.ProvisioningState = &provisioningState
		}
	}

	// Set property "ServiceTags":
	// copying flattened property:
	if typedInput.Properties != nil {
		for _, item := range typedInput.Properties.ServiceTags {
			rule.ServiceTags = append(rule.ServiceTags, item)
		}
	}

	// Set property "Subscriptions":
	// copying flattened property:
	if typedInput.Properties != nil {
		for _, item := range typedInput.Properties.Subscriptions {
			var item1 SubscriptionId_STATUS
			err := item1.PopulateFromARM(owner, item)
			if err != nil {
				return err
			}
			rule.Subscriptions = append(rule.Subscriptions, item1)
		}
	}

	// Set property "SystemData":
	if typedInput.SystemData != nil {
		var systemData1 CommonSystemData_STATUS
		err := systemData1.PopulateFromARM(owner, *typedInput.SystemData)
		if err != nil {
			return err
		}
		systemData := systemData1
		rule.SystemData = &systemData
	}

	// Set property "Type":
	if typedInput.Type != nil {
		typeVar := *typedInput.Type
		rule.Type = &typeVar
	}

	// No error
	return nil
}

// AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule_STATUS populates our NetworkSecurityPerimetersProfilesAccessRule_STATUS from the provided source NetworkSecurityPerimetersProfilesAccessRule_STATUS
func (rule *NetworkSecurityPerimetersProfilesAccessRule_STATUS) AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRule_STATUS(source *storage.NetworkSecurityPerimetersProfilesAccessRule_STATUS) error {

	// AddressPrefixes
	rule.AddressPrefixes = genruntime.CloneSliceOfString(source.AddressPrefixes)

	// Conditions
	rule.Conditions = genruntime.CloneSliceOfCondition(source.Conditions)

	// Direction
	if source.Direction != nil {
		direction := *source.Direction
		directionTemp := genruntime.ToEnum(direction, nspAccessRuleProperties_Direction_STATUS_Values)
		rule.Direction = &directionTemp
	} else {
		rule.Direction = nil
	}

	// EmailAddresses
	rule.EmailAddresses = genruntime.CloneSliceOfString(source.EmailAddresses)

	// FullyQualifiedDomainNames
	rule.FullyQualifiedDomainNames = genruntime.CloneSliceOfString(source.FullyQualifiedDomainNames)

	// Id
	rule.Id = genruntime.ClonePointerToString(source.Id)

	// Name
	rule.Name = genruntime.ClonePointerToString(source.Name)

	// NetworkSecurityPerimeters
	if source.NetworkSecurityPerimeters != nil {
		networkSecurityPerimeterList := make([]PerimeterBasedAccessRule_STATUS, len(source.NetworkSecurityPerimeters))
		for networkSecurityPerimeterIndex, networkSecurityPerimeterItem := range source.NetworkSecurityPerimeters {
			var networkSecurityPerimeter PerimeterBasedAccessRule_STATUS
			err := networkSecurityPerimeter.AssignProperties_From_PerimeterBasedAccessRule_STATUS(&networkSecurityPerimeterItem)
			if err != nil {
				return eris.Wrap(err, "calling AssignProperties_From_PerimeterBasedAccessRule_STATUS() to populate field NetworkSecurityPerimeters")
			}
			networkSecurityPerimeterList[networkSecurityPerimeterIndex] = networkSecurityPerimeter
		}
		rule.NetworkSecurityPerimeters = networkSecurityPerimeterList
	} else {
		rule.NetworkSecurityPerimeters = nil
	}

	// PhoneNumbers
	rule.PhoneNumbers = genruntime.CloneSliceOfString(source.PhoneNumbers)

	// ProvisioningState
	if source.ProvisioningState != nil {
		provisioningState := *source.ProvisioningState
		provisioningStateTemp := genruntime.ToEnum(provisioningState, nSPProvisioningState_STATUS_Values)
		rule.ProvisioningState = &provisioningStateTemp
	} else {
		rule.ProvisioningState = nil
	}

	// ServiceTags
	rule.ServiceTags = genruntime.CloneSliceOfString(source.ServiceTags)

	// Subscriptions
	if source.Subscriptions != nil {
		subscriptionList := make([]SubscriptionId_STATUS, len(source.Subscriptions))
		for subscriptionIndex, subscriptionItem := range source.Subscriptions {
			var subscription SubscriptionId_STATUS
			err := subscription.AssignProperties_From_SubscriptionId_STATUS(&subscriptionItem)
			if err != nil {
				return eris.Wrap(err, "calling AssignProperties_From_SubscriptionId_STATUS() to populate field Subscriptions")
			}
			subscriptionList[subscriptionIndex] = subscription
		}
		rule.Subscriptions = subscriptionList
	} else {
		rule.Subscriptions = nil
	}

	// SystemData
	if source.SystemData != nil {
		var systemDatum CommonSystemData_STATUS
		err := systemDatum.AssignProperties_From_CommonSystemData_STATUS(source.SystemData)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_From_CommonSystemData_STATUS() to populate field SystemData")
		}
		rule.SystemData = &systemDatum
	} else {
		rule.SystemData = nil
	}

	// Type
	rule.Type = genruntime.ClonePointerToString(source.Type)

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule_STATUS populates the provided destination NetworkSecurityPerimetersProfilesAccessRule_STATUS from our NetworkSecurityPerimetersProfilesAccessRule_STATUS
func (rule *NetworkSecurityPerimetersProfilesAccessRule_STATUS) AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRule_STATUS(destination *storage.NetworkSecurityPerimetersProfilesAccessRule_STATUS) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// AddressPrefixes
	destination.AddressPrefixes = genruntime.CloneSliceOfString(rule.AddressPrefixes)

	// Conditions
	destination.Conditions = genruntime.CloneSliceOfCondition(rule.Conditions)

	// Direction
	if rule.Direction != nil {
		direction := string(*rule.Direction)
		destination.Direction = &direction
	} else {
		destination.Direction = nil
	}

	// EmailAddresses
	destination.EmailAddresses = genruntime.CloneSliceOfString(rule.EmailAddresses)

	// FullyQualifiedDomainNames
	destination.FullyQualifiedDomainNames = genruntime.CloneSliceOfString(rule.FullyQualifiedDomainNames)

	// Id
	destination.Id = genruntime.ClonePointerToString(rule.Id)

	// Name
	destination.Name = genruntime.ClonePointerToString(rule.Name)

	// NetworkSecurityPerimeters
	if rule.NetworkSecurityPerimeters != nil {
		networkSecurityPerimeterList := make([]storage.PerimeterBasedAccessRule_STATUS, len(rule.NetworkSecurityPerimeters))
		for networkSecurityPerimeterIndex, networkSecurityPerimeterItem := range rule.NetworkSecurityPerimeters {
			var networkSecurityPerimeter storage.PerimeterBasedAccessRule_STATUS
			err := networkSecurityPerimeterItem.AssignProperties_To_PerimeterBasedAccessRule_STATUS(&networkSecurityPerimeter)
			if err != nil {
				return eris.Wrap(err, "calling AssignProperties_To_PerimeterBasedAccessRule_STATUS() to populate field NetworkSecurityPerimeters")
			}
			networkSecurityPerimeterList[networkSecurityPerimeterIndex] = networkSecurityPerimeter
		}
		destination.NetworkSecurityPerimeters = networkSecurityPerimeterList
	} else {
		destination.NetworkSecurityPerimeters = nil
	}

	// PhoneNumbers
	destination.PhoneNumbers = genruntime.CloneSliceOfString(rule.PhoneNumbers)

	// ProvisioningState
	if rule.ProvisioningState != nil {
		provisioningState := string(*rule.ProvisioningState)
		destination.ProvisioningState = &provisioningState
	} else {
		destination.ProvisioningState = nil
	}

	// ServiceTags
	destination.ServiceTags = genruntime.CloneSliceOfString(rule.ServiceTags)

	// Subscriptions
	if rule.Subscriptions != nil {
		subscriptionList := make([]storage.SubscriptionId_STATUS, len(rule.Subscriptions))
		for subscriptionIndex, subscriptionItem := range rule.Subscriptions {
			var subscription storage.SubscriptionId_STATUS
			err := subscriptionItem.AssignProperties_To_SubscriptionId_STATUS(&subscription)
			if err != nil {
				return eris.Wrap(err, "calling AssignProperties_To_SubscriptionId_STATUS() to populate field Subscriptions")
			}
			subscriptionList[subscriptionIndex] = subscription
		}
		destination.Subscriptions = subscriptionList
	} else {
		destination.Subscriptions = nil
	}

	// SystemData
	if rule.SystemData != nil {
		var systemDatum storage.CommonSystemData_STATUS
		err := rule.SystemData.AssignProperties_To_CommonSystemData_STATUS(&systemDatum)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_To_CommonSystemData_STATUS() to populate field SystemData")
		}
		destination.SystemData = &systemDatum
	} else {
		destination.SystemData = nil
	}

	// Type
	destination.Type = genruntime.ClonePointerToString(rule.Type)

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

// Details for configuring operator behavior. Fields in this struct are interpreted by the operator directly rather than being passed to Azure
type NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec struct {
	// ConfigMapExpressions: configures where to place operator written dynamic ConfigMaps (created with CEL expressions).
	ConfigMapExpressions []*core.DestinationExpression `json:"configMapExpressions,omitempty"`

	// SecretExpressions: configures where to place operator written dynamic secrets (created with CEL expressions).
	SecretExpressions []*core.DestinationExpression `json:"secretExpressions,omitempty"`
}

// AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec populates our NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec from the provided source NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec
func (operator *NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec) AssignProperties_From_NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec(source *storage.NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec) error {

	// ConfigMapExpressions
	if source.ConfigMapExpressions != nil {
		configMapExpressionList := make([]*core.DestinationExpression, len(source.ConfigMapExpressions))
		for configMapExpressionIndex, configMapExpressionItem := range source.ConfigMapExpressions {
			if configMapExpressionItem != nil {
				configMapExpression := *configMapExpressionItem.DeepCopy()
				configMapExpressionList[configMapExpressionIndex] = &configMapExpression
			} else {
				configMapExpressionList[configMapExpressionIndex] = nil
			}
		}
		operator.ConfigMapExpressions = configMapExpressionList
	} else {
		operator.ConfigMapExpressions = nil
	}

	// SecretExpressions
	if source.SecretExpressions != nil {
		secretExpressionList := make([]*core.DestinationExpression, len(source.SecretExpressions))
		for secretExpressionIndex, secretExpressionItem := range source.SecretExpressions {
			if secretExpressionItem != nil {
				secretExpression := *secretExpressionItem.DeepCopy()
				secretExpressionList[secretExpressionIndex] = &secretExpression
			} else {
				secretExpressionList[secretExpressionIndex] = nil
			}
		}
		operator.SecretExpressions = secretExpressionList
	} else {
		operator.SecretExpressions = nil
	}

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec populates the provided destination NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec from our NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec
func (operator *NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec) AssignProperties_To_NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec(destination *storage.NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// ConfigMapExpressions
	if operator.ConfigMapExpressions != nil {
		configMapExpressionList := make([]*core.DestinationExpression, len(operator.ConfigMapExpressions))
		for configMapExpressionIndex, configMapExpressionItem := range operator.ConfigMapExpressions {
			if configMapExpressionItem != nil {
				configMapExpression := *configMapExpressionItem.DeepCopy()
				configMapExpressionList[configMapExpressionIndex] = &configMapExpression
			} else {
				configMapExpressionList[configMapExpressionIndex] = nil
			}
		}
		destination.ConfigMapExpressions = configMapExpressionList
	} else {
		destination.ConfigMapExpressions = nil
	}

	// SecretExpressions
	if operator.SecretExpressions != nil {
		secretExpressionList := make([]*core.DestinationExpression, len(operator.SecretExpressions))
		for secretExpressionIndex, secretExpressionItem := range operator.SecretExpressions {
			if secretExpressionItem != nil {
				secretExpression := *secretExpressionItem.DeepCopy()
				secretExpressionList[secretExpressionIndex] = &secretExpression
			} else {
				secretExpressionList[secretExpressionIndex] = nil
			}
		}
		destination.SecretExpressions = secretExpressionList
	} else {
		destination.SecretExpressions = nil
	}

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

type NspAccessRuleProperties_Direction_STATUS string

const (
	NspAccessRuleProperties_Direction_STATUS_Inbound  = NspAccessRuleProperties_Direction_STATUS("Inbound")
	NspAccessRuleProperties_Direction_STATUS_Outbound = NspAccessRuleProperties_Direction_STATUS("Outbound")
)

// Mapping from string to NspAccessRuleProperties_Direction_STATUS
var nspAccessRuleProperties_Direction_STATUS_Values = map[string]NspAccessRuleProperties_Direction_STATUS{
	"inbound":  NspAccessRuleProperties_Direction_STATUS_Inbound,
	"outbound": NspAccessRuleProperties_Direction_STATUS_Outbound,
}

type PerimeterBasedAccessRule_STATUS struct {
	// Id: NSP id in the ARM id format.
	Id *string `json:"id,omitempty"`

	// Location: Location of the NSP supplied.
	Location *string `json:"location,omitempty"`

	// PerimeterGuid: Resource guid of the NSP supplied.
	PerimeterGuid *string `json:"perimeterGuid,omitempty"`
}

var _ genruntime.FromARMConverter = &PerimeterBasedAccessRule_STATUS{}

// NewEmptyARMValue returns an empty ARM value suitable for deserializing into
func (rule *PerimeterBasedAccessRule_STATUS) NewEmptyARMValue() genruntime.ARMResourceStatus {
	return &arm.PerimeterBasedAccessRule_STATUS{}
}

// PopulateFromARM populates a Kubernetes CRD object from an Azure ARM object
func (rule *PerimeterBasedAccessRule_STATUS) PopulateFromARM(owner genruntime.ArbitraryOwnerReference, armInput interface{}) error {
	typedInput, ok := armInput.(arm.PerimeterBasedAccessRule_STATUS)
	if !ok {
		return fmt.Errorf("unexpected type supplied for PopulateFromARM() function. Expected arm.PerimeterBasedAccessRule_STATUS, got %T", armInput)
	}

	// Set property "Id":
	if typedInput.Id != nil {
		id := *typedInput.Id
		rule.Id = &id
	}

	// Set property "Location":
	if typedInput.Location != nil {
		location := *typedInput.Location
		rule.Location = &location
	}

	// Set property "PerimeterGuid":
	if typedInput.PerimeterGuid != nil {
		perimeterGuid := *typedInput.PerimeterGuid
		rule.PerimeterGuid = &perimeterGuid
	}

	// No error
	return nil
}

// AssignProperties_From_PerimeterBasedAccessRule_STATUS populates our PerimeterBasedAccessRule_STATUS from the provided source PerimeterBasedAccessRule_STATUS
func (rule *PerimeterBasedAccessRule_STATUS) AssignProperties_From_PerimeterBasedAccessRule_STATUS(source *storage.PerimeterBasedAccessRule_STATUS) error {

	// Id
	rule.Id = genruntime.ClonePointerToString(source.Id)

	// Location
	rule.Location = genruntime.ClonePointerToString(source.Location)

	// PerimeterGuid
	rule.PerimeterGuid = genruntime.ClonePointerToString(source.PerimeterGuid)

	// No error
	return nil
}

// AssignProperties_To_PerimeterBasedAccessRule_STATUS populates the provided destination PerimeterBasedAccessRule_STATUS from our PerimeterBasedAccessRule_STATUS
func (rule *PerimeterBasedAccessRule_STATUS) AssignProperties_To_PerimeterBasedAccessRule_STATUS(destination *storage.PerimeterBasedAccessRule_STATUS) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// Id
	destination.Id = genruntime.ClonePointerToString(rule.Id)

	// Location
	destination.Location = genruntime.ClonePointerToString(rule.Location)

	// PerimeterGuid
	destination.PerimeterGuid = genruntime.ClonePointerToString(rule.PerimeterGuid)

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

type SubscriptionId_STATUS struct {
	// Id: Subscription id in the ARM id format.
	Id *string `json:"id,omitempty"`
}

var _ genruntime.FromARMConverter = &SubscriptionId_STATUS{}

// NewEmptyARMValue returns an empty ARM value suitable for deserializing into
func (subscriptionId *SubscriptionId_STATUS) NewEmptyARMValue() genruntime.ARMResourceStatus {
	return &arm.SubscriptionId_STATUS{}
}

// PopulateFromARM populates a Kubernetes CRD object from an Azure ARM object
func (subscriptionId *SubscriptionId_STATUS) PopulateFromARM(owner genruntime.ArbitraryOwnerReference, armInput interface{}) error {
	typedInput, ok := armInput.(arm.SubscriptionId_STATUS)
	if !ok {
		return fmt.Errorf("unexpected type supplied for PopulateFromARM() function. Expected arm.SubscriptionId_STATUS, got %T", armInput)
	}

	// Set property "Id":
	if typedInput.Id != nil {
		id := *typedInput.Id
		subscriptionId.Id = &id
	}

	// No error
	return nil
}

// AssignProperties_From_SubscriptionId_STATUS populates our SubscriptionId_STATUS from the provided source SubscriptionId_STATUS
func (subscriptionId *SubscriptionId_STATUS) AssignProperties_From_SubscriptionId_STATUS(source *storage.SubscriptionId_STATUS) error {

	// Id
	subscriptionId.Id = genruntime.ClonePointerToString(source.Id)

	// No error
	return nil
}

// AssignProperties_To_SubscriptionId_STATUS populates the provided destination SubscriptionId_STATUS from our SubscriptionId_STATUS
func (subscriptionId *SubscriptionId_STATUS) AssignProperties_To_SubscriptionId_STATUS(destination *storage.SubscriptionId_STATUS) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// Id
	destination.Id = genruntime.ClonePointerToString(subscriptionId.Id)

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

func init() {
	SchemeBuilder.Register(&NetworkSecurityPerimetersProfilesAccessRule{}, &NetworkSecurityPerimetersProfilesAccessRuleList{})
}
