// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v20250701

import (
	"fmt"
	arm "github.com/Azure/azure-service-operator/v2/api/network/v20250701/arm"
	storage "github.com/Azure/azure-service-operator/v2/api/network/v20250701/storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/conditions"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/configmaps"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/core"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/secrets"
	"github.com/rotisserie/eris"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/conversion"
)

// +kubebuilder:object:root=true
// +kubebuilder:resource:categories={azure,network}
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Severity",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].severity"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].message"
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-07-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/loggingConfigurations/{loggingConfigurationName}
type NetworkSecurityPerimetersLoggingConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkSecurityPerimetersLoggingConfiguration_Spec   `json:"spec,omitempty"`
	Status            NetworkSecurityPerimetersLoggingConfiguration_STATUS `json:"status,omitempty"`
}

var _ conditions.Conditioner = &NetworkSecurityPerimetersLoggingConfiguration{}

// GetConditions returns the conditions of the resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) GetConditions() conditions.Conditions {
	return configuration.Status.Conditions
}

// SetConditions sets the conditions on the resource status
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) SetConditions(conditions conditions.Conditions) {
	configuration.Status.Conditions = conditions
}

var _ conversion.Convertible = &NetworkSecurityPerimetersLoggingConfiguration{}

// ConvertFrom populates our NetworkSecurityPerimetersLoggingConfiguration from the provided hub NetworkSecurityPerimetersLoggingConfiguration
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) ConvertFrom(hub conversion.Hub) error {
	source, ok := hub.(*storage.NetworkSecurityPerimetersLoggingConfiguration)
	if !ok {
		return fmt.Errorf("expected network/v20250701/storage/NetworkSecurityPerimetersLoggingConfiguration but received %T instead", hub)
	}

	return configuration.AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration(source)
}

// ConvertTo populates the provided hub NetworkSecurityPerimetersLoggingConfiguration from our NetworkSecurityPerimetersLoggingConfiguration
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) ConvertTo(hub conversion.Hub) error {
	destination, ok := hub.(*storage.NetworkSecurityPerimetersLoggingConfiguration)
	if !ok {
		return fmt.Errorf("expected network/v20250701/storage/NetworkSecurityPerimetersLoggingConfiguration but received %T instead", hub)
	}

	return configuration.AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration(destination)
}

var _ configmaps.Exporter = &NetworkSecurityPerimetersLoggingConfiguration{}

// ConfigMapDestinationExpressions returns the Spec.OperatorSpec.ConfigMapExpressions property
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) ConfigMapDestinationExpressions() []*core.DestinationExpression {
	if configuration.Spec.OperatorSpec == nil {
		return nil
	}
	return configuration.Spec.OperatorSpec.ConfigMapExpressions
}

var _ secrets.Exporter = &NetworkSecurityPerimetersLoggingConfiguration{}

// SecretDestinationExpressions returns the Spec.OperatorSpec.SecretExpressions property
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) SecretDestinationExpressions() []*core.DestinationExpression {
	if configuration.Spec.OperatorSpec == nil {
		return nil
	}
	return configuration.Spec.OperatorSpec.SecretExpressions
}

var _ genruntime.ImportableResource = &NetworkSecurityPerimetersLoggingConfiguration{}

// InitializeSpec initializes the spec for this resource from the given status
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) InitializeSpec(status genruntime.ConvertibleStatus) error {
	if s, ok := status.(*NetworkSecurityPerimetersLoggingConfiguration_STATUS); ok {
		return configuration.Spec.Initialize_From_NetworkSecurityPerimetersLoggingConfiguration_STATUS(s)
	}

	return fmt.Errorf("expected Status of type NetworkSecurityPerimetersLoggingConfiguration_STATUS but received %T instead", status)
}

var _ genruntime.KubernetesResource = &NetworkSecurityPerimetersLoggingConfiguration{}

// AzureName returns the Azure name of the resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) AzureName() string {
	return configuration.Spec.AzureName
}

// GetAPIVersion returns the ARM API version of the resource. This is always "2025-07-01"
func (configuration NetworkSecurityPerimetersLoggingConfiguration) GetAPIVersion() string {
	return "2025-07-01"
}

// GetResourceScope returns the scope of the resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) GetResourceScope() genruntime.ResourceScope {
	return genruntime.ResourceScopeResourceGroup
}

// GetSpec returns the specification of this resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) GetSpec() genruntime.ConvertibleSpec {
	return &configuration.Spec
}

// GetStatus returns the status of this resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) GetStatus() genruntime.ConvertibleStatus {
	return &configuration.Status
}

// GetSupportedOperations returns the operations supported by the resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) GetSupportedOperations() []genruntime.ResourceOperation {
	return []genruntime.ResourceOperation{
		genruntime.ResourceOperationDelete,
		genruntime.ResourceOperationGet,
		genruntime.ResourceOperationPut,
	}
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Network/networkSecurityPerimeters/loggingConfigurations"
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) GetType() string {
	return "Microsoft.Network/networkSecurityPerimeters/loggingConfigurations"
}

// NewEmptyStatus returns a new empty (blank) status
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) NewEmptyStatus() genruntime.ConvertibleStatus {
	return &NetworkSecurityPerimetersLoggingConfiguration_STATUS{}
}

// Owner returns the ResourceReference of the owner
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) Owner() *genruntime.ResourceReference {
	if configuration.Spec.Owner == nil {
		return nil
	}

	group, kind := genruntime.LookupOwnerGroupKind(configuration.Spec)
	return configuration.Spec.Owner.AsResourceReference(group, kind)
}

// SetStatus sets the status of this resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) SetStatus(status genruntime.ConvertibleStatus) error {
	// If we have exactly the right type of status, assign it
	if st, ok := status.(*NetworkSecurityPerimetersLoggingConfiguration_STATUS); ok {
		configuration.Status = *st
		return nil
	}

	// Convert status to required version
	var st NetworkSecurityPerimetersLoggingConfiguration_STATUS
	err := status.ConvertStatusTo(&st)
	if err != nil {
		return eris.Wrap(err, "failed to convert status")
	}

	configuration.Status = st
	return nil
}

// AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration populates our NetworkSecurityPerimetersLoggingConfiguration from the provided source NetworkSecurityPerimetersLoggingConfiguration
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration(source *storage.NetworkSecurityPerimetersLoggingConfiguration) error {

	// ObjectMeta
	configuration.ObjectMeta = *source.ObjectMeta.DeepCopy()

	// Spec
	var spec NetworkSecurityPerimetersLoggingConfiguration_Spec
	err := spec.AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration_Spec(&source.Spec)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration_Spec() to populate field Spec")
	}
	configuration.Spec = spec

	// Status
	var status NetworkSecurityPerimetersLoggingConfiguration_STATUS
	err = status.AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration_STATUS(&source.Status)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration_STATUS() to populate field Status")
	}
	configuration.Status = status

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration populates the provided destination NetworkSecurityPerimetersLoggingConfiguration from our NetworkSecurityPerimetersLoggingConfiguration
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration(destination *storage.NetworkSecurityPerimetersLoggingConfiguration) error {

	// ObjectMeta
	destination.ObjectMeta = *configuration.ObjectMeta.DeepCopy()

	// Spec
	var spec storage.NetworkSecurityPerimetersLoggingConfiguration_Spec
	err := configuration.Spec.AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration_Spec(&spec)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration_Spec() to populate field Spec")
	}
	destination.Spec = spec

	// Status
	var status storage.NetworkSecurityPerimetersLoggingConfiguration_STATUS
	err = configuration.Status.AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration_STATUS(&status)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration_STATUS() to populate field Status")
	}
	destination.Status = status

	// No error
	return nil
}

// OriginalGVK returns a GroupValueKind for the original API version used to create the resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) OriginalGVK() *schema.GroupVersionKind {
	return &schema.GroupVersionKind{
		Group:   GroupVersion.Group,
		Version: configuration.Spec.OriginalVersion(),
		Kind:    "NetworkSecurityPerimetersLoggingConfiguration",
	}
}

// +kubebuilder:object:root=true
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-07-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/loggingConfigurations/{loggingConfigurationName}
type NetworkSecurityPerimetersLoggingConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkSecurityPerimetersLoggingConfiguration `json:"items"`
}

type NetworkSecurityPerimetersLoggingConfiguration_Spec struct {
	// +kubebuilder:validation:MaxLength=80
	// +kubebuilder:validation:Pattern="(^[a-zA-Z0-9]+[a-zA-Z0-9_.-]*[a-zA-Z0-9_]+$)|(^[a-zA-Z0-9]$)"
	// AzureName: The name of the resource in Azure. This is often the same as the name of the resource in Kubernetes but it
	// doesn't have to be.
	AzureName string `json:"azureName,omitempty"`

	// EnabledLogCategories: The log categories to enable in the NSP logging configuration.
	EnabledLogCategories []string `json:"enabledLogCategories,omitempty"`

	// OperatorSpec: The specification for configuring operator behavior. This field is interpreted by the operator and not
	// passed directly to Azure
	OperatorSpec *NetworkSecurityPerimetersLoggingConfigurationOperatorSpec `json:"operatorSpec,omitempty"`

	// +kubebuilder:validation:Required
	// Owner: The owner of the resource. The owner controls where the resource goes when it is deployed. The owner also
	// controls the resources lifecycle. When the owner is deleted the resource will also be deleted. Owner is expected to be a
	// reference to a network.azure.com/NetworkSecurityPerimeter resource
	Owner *genruntime.KnownResourceReference `group:"network.azure.com" json:"owner,omitempty" kind:"NetworkSecurityPerimeter"`

	// Version: The version of the NSP logging configuration.
	Version *string `json:"version,omitempty"`
}

var _ genruntime.ARMTransformer = &NetworkSecurityPerimetersLoggingConfiguration_Spec{}

// ConvertToARM converts from a Kubernetes CRD object to an ARM object
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) ConvertToARM(resolved genruntime.ConvertToARMResolvedDetails) (interface{}, error) {
	if configuration == nil {
		return nil, nil
	}
	result := &arm.NetworkSecurityPerimetersLoggingConfiguration_Spec{}

	// Set property "Name":
	result.Name = resolved.Name

	// Set property "Properties":
	if configuration.EnabledLogCategories != nil || configuration.Version != nil {
		result.Properties = &arm.NspLoggingConfigurationProperties{}
	}
	for _, item := range configuration.EnabledLogCategories {
		result.Properties.EnabledLogCategories = append(result.Properties.EnabledLogCategories, item)
	}
	if configuration.Version != nil {
		version := *configuration.Version
		result.Properties.Version = &version
	}
	return result, nil
}

// NewEmptyARMValue returns an empty ARM value suitable for deserializing into
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) NewEmptyARMValue() genruntime.ARMResourceStatus {
	return &arm.NetworkSecurityPerimetersLoggingConfiguration_Spec{}
}

// PopulateFromARM populates a Kubernetes CRD object from an Azure ARM object
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) PopulateFromARM(owner genruntime.ArbitraryOwnerReference, armInput interface{}) error {
	typedInput, ok := armInput.(arm.NetworkSecurityPerimetersLoggingConfiguration_Spec)
	if !ok {
		return fmt.Errorf("unexpected type supplied for PopulateFromARM() function. Expected arm.NetworkSecurityPerimetersLoggingConfiguration_Spec, got %T", armInput)
	}

	// Set property "AzureName":
	configuration.SetAzureName(genruntime.ExtractKubernetesResourceNameFromARMName(typedInput.Name))

	// Set property "EnabledLogCategories":
	// copying flattened property:
	if typedInput.Properties != nil {
		for _, item := range typedInput.Properties.EnabledLogCategories {
			configuration.EnabledLogCategories = append(configuration.EnabledLogCategories, item)
		}
	}

	// no assignment for property "OperatorSpec"

	// Set property "Owner":
	configuration.Owner = &genruntime.KnownResourceReference{
		Name:  owner.Name,
		ARMID: owner.ARMID,
	}

	// Set property "Version":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.Version != nil {
			version := *typedInput.Properties.Version
			configuration.Version = &version
		}
	}

	// No error
	return nil
}

var _ genruntime.ConvertibleSpec = &NetworkSecurityPerimetersLoggingConfiguration_Spec{}

// ConvertSpecFrom populates our NetworkSecurityPerimetersLoggingConfiguration_Spec from the provided source
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) ConvertSpecFrom(source genruntime.ConvertibleSpec) error {
	src, ok := source.(*storage.NetworkSecurityPerimetersLoggingConfiguration_Spec)
	if ok {
		// Populate our instance from source
		return configuration.AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration_Spec(src)
	}

	// Convert to an intermediate form
	src = &storage.NetworkSecurityPerimetersLoggingConfiguration_Spec{}
	err := src.ConvertSpecFrom(source)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertSpecFrom()")
	}

	// Update our instance from src
	err = configuration.AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration_Spec(src)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertSpecFrom()")
	}

	return nil
}

// ConvertSpecTo populates the provided destination from our NetworkSecurityPerimetersLoggingConfiguration_Spec
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) ConvertSpecTo(destination genruntime.ConvertibleSpec) error {
	dst, ok := destination.(*storage.NetworkSecurityPerimetersLoggingConfiguration_Spec)
	if ok {
		// Populate destination from our instance
		return configuration.AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration_Spec(dst)
	}

	// Convert to an intermediate form
	dst = &storage.NetworkSecurityPerimetersLoggingConfiguration_Spec{}
	err := configuration.AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration_Spec(dst)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertSpecTo()")
	}

	// Update dst from our instance
	err = dst.ConvertSpecTo(destination)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertSpecTo()")
	}

	return nil
}

// AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration_Spec populates our NetworkSecurityPerimetersLoggingConfiguration_Spec from the provided source NetworkSecurityPerimetersLoggingConfiguration_Spec
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration_Spec(source *storage.NetworkSecurityPerimetersLoggingConfiguration_Spec) error {

	// AzureName
	configuration.AzureName = source.AzureName

	// EnabledLogCategories
	configuration.EnabledLogCategories = genruntime.CloneSliceOfString(source.EnabledLogCategories)

	// OperatorSpec
	if source.OperatorSpec != nil {
		var operatorSpec NetworkSecurityPerimetersLoggingConfigurationOperatorSpec
		err := operatorSpec.AssignProperties_From_NetworkSecurityPerimetersLoggingConfigurationOperatorSpec(source.OperatorSpec)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_From_NetworkSecurityPerimetersLoggingConfigurationOperatorSpec() to populate field OperatorSpec")
		}
		configuration.OperatorSpec = &operatorSpec
	} else {
		configuration.OperatorSpec = nil
	}

	// Owner
	if source.Owner != nil {
		owner := source.Owner.Copy()
		configuration.Owner = &owner
	} else {
		configuration.Owner = nil
	}

	// Version
	configuration.Version = genruntime.ClonePointerToString(source.Version)

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration_Spec populates the provided destination NetworkSecurityPerimetersLoggingConfiguration_Spec from our NetworkSecurityPerimetersLoggingConfiguration_Spec
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration_Spec(destination *storage.NetworkSecurityPerimetersLoggingConfiguration_Spec) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// AzureName
	destination.AzureName = configuration.AzureName

	// EnabledLogCategories
	destination.EnabledLogCategories = genruntime.CloneSliceOfString(configuration.EnabledLogCategories)

	// OperatorSpec
	if configuration.OperatorSpec != nil {
		var operatorSpec storage.NetworkSecurityPerimetersLoggingConfigurationOperatorSpec
		err := configuration.OperatorSpec.AssignProperties_To_NetworkSecurityPerimetersLoggingConfigurationOperatorSpec(&operatorSpec)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_To_NetworkSecurityPerimetersLoggingConfigurationOperatorSpec() to populate field OperatorSpec")
		}
		destination.OperatorSpec = &operatorSpec
	} else {
		destination.OperatorSpec = nil
	}

	// OriginalVersion
	destination.OriginalVersion = configuration.OriginalVersion()

	// Owner
	if configuration.Owner != nil {
		owner := configuration.Owner.Copy()
		destination.Owner = &owner
	} else {
		destination.Owner = nil
	}

	// Version
	destination.Version = genruntime.ClonePointerToString(configuration.Version)

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

// Initialize_From_NetworkSecurityPerimetersLoggingConfiguration_STATUS populates our NetworkSecurityPerimetersLoggingConfiguration_Spec from the provided source NetworkSecurityPerimetersLoggingConfiguration_STATUS
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) Initialize_From_NetworkSecurityPerimetersLoggingConfiguration_STATUS(source *NetworkSecurityPerimetersLoggingConfiguration_STATUS) error {

	// EnabledLogCategories
	configuration.EnabledLogCategories = genruntime.CloneSliceOfString(source.EnabledLogCategories)

	// Version
	configuration.Version = genruntime.ClonePointerToString(source.Version)

	// No error
	return nil
}

// OriginalVersion returns the original API version used to create the resource.
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) OriginalVersion() string {
	return GroupVersion.Version
}

// SetAzureName sets the Azure name of the resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) SetAzureName(azureName string) {
	configuration.AzureName = azureName
}

type NetworkSecurityPerimetersLoggingConfiguration_STATUS struct {
	// Conditions: The observed state of the resource
	Conditions []conditions.Condition `json:"conditions,omitempty"`

	// EnabledLogCategories: The log categories to enable in the NSP logging configuration.
	EnabledLogCategories []string `json:"enabledLogCategories,omitempty"`

	// Id: Fully qualified resource ID for the resource. E.g.
	// "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id *string `json:"id,omitempty"`

	// Name: The name of the resource
	Name *string `json:"name,omitempty"`

	// SystemData: Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SecurityPerimeterSystemData_STATUS `json:"systemData,omitempty"`

	// Type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`

	// Version: The version of the NSP logging configuration.
	Version *string `json:"version,omitempty"`
}

var _ genruntime.ConvertibleStatus = &NetworkSecurityPerimetersLoggingConfiguration_STATUS{}

// ConvertStatusFrom populates our NetworkSecurityPerimetersLoggingConfiguration_STATUS from the provided source
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_STATUS) ConvertStatusFrom(source genruntime.ConvertibleStatus) error {
	src, ok := source.(*storage.NetworkSecurityPerimetersLoggingConfiguration_STATUS)
	if ok {
		// Populate our instance from source
		return configuration.AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration_STATUS(src)
	}

	// Convert to an intermediate form
	src = &storage.NetworkSecurityPerimetersLoggingConfiguration_STATUS{}
	err := src.ConvertStatusFrom(source)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertStatusFrom()")
	}

	// Update our instance from src
	err = configuration.AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration_STATUS(src)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertStatusFrom()")
	}

	return nil
}

// ConvertStatusTo populates the provided destination from our NetworkSecurityPerimetersLoggingConfiguration_STATUS
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_STATUS) ConvertStatusTo(destination genruntime.ConvertibleStatus) error {
	dst, ok := destination.(*storage.NetworkSecurityPerimetersLoggingConfiguration_STATUS)
	if ok {
		// Populate destination from our instance
		return configuration.AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration_STATUS(dst)
	}

	// Convert to an intermediate form
	dst = &storage.NetworkSecurityPerimetersLoggingConfiguration_STATUS{}
	err := configuration.AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration_STATUS(dst)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertStatusTo()")
	}

	// Update dst from our instance
	err = dst.ConvertStatusTo(destination)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertStatusTo()")
	}

	return nil
}

var _ genruntime.FromARMConverter = &NetworkSecurityPerimetersLoggingConfiguration_STATUS{}

// NewEmptyARMValue returns an empty ARM value suitable for deserializing into
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_STATUS) NewEmptyARMValue() genruntime.ARMResourceStatus {
	return &arm.NetworkSecurityPerimetersLoggingConfiguration_STATUS{}
}

// PopulateFromARM populates a Kubernetes CRD object from an Azure ARM object
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_STATUS) PopulateFromARM(owner genruntime.ArbitraryOwnerReference, armInput interface{}) error {
	typedInput, ok := armInput.(arm.NetworkSecurityPerimetersLoggingConfiguration_STATUS)
	if !ok {
		return fmt.Errorf("unexpected type supplied for PopulateFromARM() function. Expected arm.NetworkSecurityPerimetersLoggingConfiguration_STATUS, got %T", armInput)
	}

	// no assignment for property "Conditions"

	// Set property "EnabledLogCategories":
	// copying flattened property:
	if typedInput.Properties != nil {
		for _, item := range typedInput.Properties.EnabledLogCategories {
			configuration.EnabledLogCategories = append(configuration.EnabledLogCategories, item)
		}
	}

	// Set property "Id":
	if typedInput.Id != nil {
		id := *typedInput.Id
		configuration.Id = &id
	}

	// Set property "Name":
	if typedInput.Name != nil {
		name := *typedInput.Name
		configuration.Name = &name
	}

	// Set property "SystemData":
	if typedInput.SystemData != nil {
		var systemData1 SecurityPerimeterSystemData_STATUS
		err := systemData1.PopulateFromARM(owner, *typedInput.SystemData)
		if err != nil {
			return err
		}
		systemData := systemData1
		configuration.SystemData = &systemData
	}

	// Set property "Type":
	if typedInput.Type != nil {
		typeVar := *typedInput.Type
		configuration.Type = &typeVar
	}

	// Set property "Version":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.Version != nil {
			version := *typedInput.Properties.Version
			configuration.Version = &version
		}
	}

	// No error
	return nil
}

// AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration_STATUS populates our NetworkSecurityPerimetersLoggingConfiguration_STATUS from the provided source NetworkSecurityPerimetersLoggingConfiguration_STATUS
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_STATUS) AssignProperties_From_NetworkSecurityPerimetersLoggingConfiguration_STATUS(source *storage.NetworkSecurityPerimetersLoggingConfiguration_STATUS) error {

	// Conditions
	configuration.Conditions = genruntime.CloneSliceOfCondition(source.Conditions)

	// EnabledLogCategories
	configuration.EnabledLogCategories = genruntime.CloneSliceOfString(source.EnabledLogCategories)

	// Id
	configuration.Id = genruntime.ClonePointerToString(source.Id)

	// Name
	configuration.Name = genruntime.ClonePointerToString(source.Name)

	// SystemData
	if source.SystemData != nil {
		var systemDatum SecurityPerimeterSystemData_STATUS
		err := systemDatum.AssignProperties_From_SecurityPerimeterSystemData_STATUS(source.SystemData)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_From_SecurityPerimeterSystemData_STATUS() to populate field SystemData")
		}
		configuration.SystemData = &systemDatum
	} else {
		configuration.SystemData = nil
	}

	// Type
	configuration.Type = genruntime.ClonePointerToString(source.Type)

	// Version
	configuration.Version = genruntime.ClonePointerToString(source.Version)

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration_STATUS populates the provided destination NetworkSecurityPerimetersLoggingConfiguration_STATUS from our NetworkSecurityPerimetersLoggingConfiguration_STATUS
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_STATUS) AssignProperties_To_NetworkSecurityPerimetersLoggingConfiguration_STATUS(destination *storage.NetworkSecurityPerimetersLoggingConfiguration_STATUS) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// Conditions
	destination.Conditions = genruntime.CloneSliceOfCondition(configuration.Conditions)

	// EnabledLogCategories
	destination.EnabledLogCategories = genruntime.CloneSliceOfString(configuration.EnabledLogCategories)

	// Id
	destination.Id = genruntime.ClonePointerToString(configuration.Id)

	// Name
	destination.Name = genruntime.ClonePointerToString(configuration.Name)

	// SystemData
	if configuration.SystemData != nil {
		var systemDatum storage.SecurityPerimeterSystemData_STATUS
		err := configuration.SystemData.AssignProperties_To_SecurityPerimeterSystemData_STATUS(&systemDatum)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_To_SecurityPerimeterSystemData_STATUS() to populate field SystemData")
		}
		destination.SystemData = &systemDatum
	} else {
		destination.SystemData = nil
	}

	// Type
	destination.Type = genruntime.ClonePointerToString(configuration.Type)

	// Version
	destination.Version = genruntime.ClonePointerToString(configuration.Version)

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

// Details for configuring operator behavior. Fields in this struct are interpreted by the operator directly rather than being passed to Azure
type NetworkSecurityPerimetersLoggingConfigurationOperatorSpec struct {
	// ConfigMapExpressions: configures where to place operator written dynamic ConfigMaps (created with CEL expressions).
	ConfigMapExpressions []*core.DestinationExpression `json:"configMapExpressions,omitempty"`

	// SecretExpressions: configures where to place operator written dynamic secrets (created with CEL expressions).
	SecretExpressions []*core.DestinationExpression `json:"secretExpressions,omitempty"`
}

// AssignProperties_From_NetworkSecurityPerimetersLoggingConfigurationOperatorSpec populates our NetworkSecurityPerimetersLoggingConfigurationOperatorSpec from the provided source NetworkSecurityPerimetersLoggingConfigurationOperatorSpec
func (operator *NetworkSecurityPerimetersLoggingConfigurationOperatorSpec) AssignProperties_From_NetworkSecurityPerimetersLoggingConfigurationOperatorSpec(source *storage.NetworkSecurityPerimetersLoggingConfigurationOperatorSpec) error {

	// ConfigMapExpressions
	if source.ConfigMapExpressions != nil {
		configMapExpressionList := make([]*core.DestinationExpression, len(source.ConfigMapExpressions))
		for configMapExpressionIndex, configMapExpressionItem := range source.ConfigMapExpressions {
			if configMapExpressionItem != nil {
				configMapExpression := *configMapExpressionItem.DeepCopy()
				configMapExpressionList[configMapExpressionIndex] = &configMapExpression
			} else {
				configMapExpressionList[configMapExpressionIndex] = nil
			}
		}
		operator.ConfigMapExpressions = configMapExpressionList
	} else {
		operator.ConfigMapExpressions = nil
	}

	// SecretExpressions
	if source.SecretExpressions != nil {
		secretExpressionList := make([]*core.DestinationExpression, len(source.SecretExpressions))
		for secretExpressionIndex, secretExpressionItem := range source.SecretExpressions {
			if secretExpressionItem != nil {
				secretExpression := *secretExpressionItem.DeepCopy()
				secretExpressionList[secretExpressionIndex] = &secretExpression
			} else {
				secretExpressionList[secretExpressionIndex] = nil
			}
		}
		operator.SecretExpressions = secretExpressionList
	} else {
		operator.SecretExpressions = nil
	}

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersLoggingConfigurationOperatorSpec populates the provided destination NetworkSecurityPerimetersLoggingConfigurationOperatorSpec from our NetworkSecurityPerimetersLoggingConfigurationOperatorSpec
func (operator *NetworkSecurityPerimetersLoggingConfigurationOperatorSpec) AssignProperties_To_NetworkSecurityPerimetersLoggingConfigurationOperatorSpec(destination *storage.NetworkSecurityPerimetersLoggingConfigurationOperatorSpec) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// ConfigMapExpressions
	if operator.ConfigMapExpressions != nil {
		configMapExpressionList := make([]*core.DestinationExpression, len(operator.ConfigMapExpressions))
		for configMapExpressionIndex, configMapExpressionItem := range operator.ConfigMapExpressions {
			if configMapExpressionItem != nil {
				configMapExpression := *configMapExpressionItem.DeepCopy()
				configMapExpressionList[configMapExpressionIndex] = &configMapExpression
			} else {
				configMapExpressionList[configMapExpressionIndex] = nil
			}
		}
		destination.ConfigMapExpressions = configMapExpressionList
	} else {
		destination.ConfigMapExpressions = nil
	}

	// SecretExpressions
	if operator.SecretExpressions != nil {
		secretExpressionList := make([]*core.DestinationExpression, len(operator.SecretExpressions))
		for secretExpressionIndex, secretExpressionItem := range operator.SecretExpressions {
			if secretExpressionItem != nil {
				secretExpression := *secretExpressionItem.DeepCopy()
				secretExpressionList[secretExpressionIndex] = &secretExpression
			} else {
				secretExpressionList[secretExpressionIndex] = nil
			}
		}
		destination.SecretExpressions = secretExpressionList
	} else {
		destination.SecretExpressions = nil
	}

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

func init() {
	SchemeBuilder.Register(&NetworkSecurityPerimetersLoggingConfiguration{}, &NetworkSecurityPerimetersLoggingConfigurationList{})
}
