// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v20250701

import (
	"encoding/json"
	storage "github.com/Azure/azure-service-operator/v2/api/network/v20250701/storage"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_NetworkSecurityPerimeter_WhenConvertedToHub_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	parameters.MinSuccessfulTests = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from NetworkSecurityPerimeter to hub returns original",
		prop.ForAll(RunResourceConversionTestForNetworkSecurityPerimeter, NetworkSecurityPerimeterGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunResourceConversionTestForNetworkSecurityPerimeter tests if a specific instance of NetworkSecurityPerimeter round trips to the hub storage version and back losslessly
func RunResourceConversionTestForNetworkSecurityPerimeter(subject NetworkSecurityPerimeter) string {
	// Copy subject to make sure conversion doesn't modify it
	copied := subject.DeepCopy()

	// Convert to our hub version
	var hub storage.NetworkSecurityPerimeter
	err := copied.ConvertTo(&hub)
	if err != nil {
		return err.Error()
	}

	// Convert from our hub version
	var actual NetworkSecurityPerimeter
	err = actual.ConvertFrom(&hub)
	if err != nil {
		return err.Error()
	}

	// Compare actual with what we started with
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_NetworkSecurityPerimeter_WhenPropertiesConverted_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from NetworkSecurityPerimeter to NetworkSecurityPerimeter via AssignProperties_To_NetworkSecurityPerimeter & AssignProperties_From_NetworkSecurityPerimeter returns original",
		prop.ForAll(RunPropertyAssignmentTestForNetworkSecurityPerimeter, NetworkSecurityPerimeterGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunPropertyAssignmentTestForNetworkSecurityPerimeter tests if a specific instance of NetworkSecurityPerimeter can be assigned to storage and back losslessly
func RunPropertyAssignmentTestForNetworkSecurityPerimeter(subject NetworkSecurityPerimeter) string {
	// Copy subject to make sure assignment doesn't modify it
	copied := subject.DeepCopy()

	// Use AssignPropertiesTo() for the first stage of conversion
	var other storage.NetworkSecurityPerimeter
	err := copied.AssignProperties_To_NetworkSecurityPerimeter(&other)
	if err != nil {
		return err.Error()
	}

	// Use AssignPropertiesFrom() to convert back to our original type
	var actual NetworkSecurityPerimeter
	err = actual.AssignProperties_From_NetworkSecurityPerimeter(&other)
	if err != nil {
		return err.Error()
	}

	// Check for a match
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_NetworkSecurityPerimeter_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 20
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimeter via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimeter, NetworkSecurityPerimeterGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimeter runs a test to see if a specific instance of NetworkSecurityPerimeter round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimeter(subject NetworkSecurityPerimeter) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimeter
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimeter instances for property testing - lazily instantiated by
// NetworkSecurityPerimeterGenerator()
var networkSecurityPerimeterGenerator gopter.Gen

// NetworkSecurityPerimeterGenerator returns a generator of NetworkSecurityPerimeter instances for property testing.
func NetworkSecurityPerimeterGenerator() gopter.Gen {
	if networkSecurityPerimeterGenerator != nil {
		return networkSecurityPerimeterGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimeter(generators)
	networkSecurityPerimeterGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimeter{}), generators)

	return networkSecurityPerimeterGenerator
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimeter is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimeter(gens map[string]gopter.Gen) {
	gens["Spec"] = NetworkSecurityPerimeter_SpecGenerator()
	gens["Status"] = NetworkSecurityPerimeter_STATUSGenerator()
}

func Test_NetworkSecurityPerimeterOperatorSpec_WhenPropertiesConverted_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from NetworkSecurityPerimeterOperatorSpec to NetworkSecurityPerimeterOperatorSpec via AssignProperties_To_NetworkSecurityPerimeterOperatorSpec & AssignProperties_From_NetworkSecurityPerimeterOperatorSpec returns original",
		prop.ForAll(RunPropertyAssignmentTestForNetworkSecurityPerimeterOperatorSpec, NetworkSecurityPerimeterOperatorSpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunPropertyAssignmentTestForNetworkSecurityPerimeterOperatorSpec tests if a specific instance of NetworkSecurityPerimeterOperatorSpec can be assigned to storage and back losslessly
func RunPropertyAssignmentTestForNetworkSecurityPerimeterOperatorSpec(subject NetworkSecurityPerimeterOperatorSpec) string {
	// Copy subject to make sure assignment doesn't modify it
	copied := subject.DeepCopy()

	// Use AssignPropertiesTo() for the first stage of conversion
	var other storage.NetworkSecurityPerimeterOperatorSpec
	err := copied.AssignProperties_To_NetworkSecurityPerimeterOperatorSpec(&other)
	if err != nil {
		return err.Error()
	}

	// Use AssignPropertiesFrom() to convert back to our original type
	var actual NetworkSecurityPerimeterOperatorSpec
	err = actual.AssignProperties_From_NetworkSecurityPerimeterOperatorSpec(&other)
	if err != nil {
		return err.Error()
	}

	// Check for a match
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_NetworkSecurityPerimeterOperatorSpec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimeterOperatorSpec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimeterOperatorSpec, NetworkSecurityPerimeterOperatorSpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimeterOperatorSpec runs a test to see if a specific instance of NetworkSecurityPerimeterOperatorSpec round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimeterOperatorSpec(subject NetworkSecurityPerimeterOperatorSpec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimeterOperatorSpec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimeterOperatorSpec instances for property testing - lazily instantiated by
// NetworkSecurityPerimeterOperatorSpecGenerator()
var networkSecurityPerimeterOperatorSpecGenerator gopter.Gen

// NetworkSecurityPerimeterOperatorSpecGenerator returns a generator of NetworkSecurityPerimeterOperatorSpec instances for property testing.
func NetworkSecurityPerimeterOperatorSpecGenerator() gopter.Gen {
	if networkSecurityPerimeterOperatorSpecGenerator != nil {
		return networkSecurityPerimeterOperatorSpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	networkSecurityPerimeterOperatorSpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimeterOperatorSpec{}), generators)

	return networkSecurityPerimeterOperatorSpecGenerator
}

func Test_NetworkSecurityPerimeter_STATUS_WhenPropertiesConverted_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from NetworkSecurityPerimeter_STATUS to NetworkSecurityPerimeter_STATUS via AssignProperties_To_NetworkSecurityPerimeter_STATUS & AssignProperties_From_NetworkSecurityPerimeter_STATUS returns original",
		prop.ForAll(RunPropertyAssignmentTestForNetworkSecurityPerimeter_STATUS, NetworkSecurityPerimeter_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunPropertyAssignmentTestForNetworkSecurityPerimeter_STATUS tests if a specific instance of NetworkSecurityPerimeter_STATUS can be assigned to storage and back losslessly
func RunPropertyAssignmentTestForNetworkSecurityPerimeter_STATUS(subject NetworkSecurityPerimeter_STATUS) string {
	// Copy subject to make sure assignment doesn't modify it
	copied := subject.DeepCopy()

	// Use AssignPropertiesTo() for the first stage of conversion
	var other storage.NetworkSecurityPerimeter_STATUS
	err := copied.AssignProperties_To_NetworkSecurityPerimeter_STATUS(&other)
	if err != nil {
		return err.Error()
	}

	// Use AssignPropertiesFrom() to convert back to our original type
	var actual NetworkSecurityPerimeter_STATUS
	err = actual.AssignProperties_From_NetworkSecurityPerimeter_STATUS(&other)
	if err != nil {
		return err.Error()
	}

	// Check for a match
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_NetworkSecurityPerimeter_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimeter_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimeter_STATUS, NetworkSecurityPerimeter_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimeter_STATUS runs a test to see if a specific instance of NetworkSecurityPerimeter_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimeter_STATUS(subject NetworkSecurityPerimeter_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimeter_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimeter_STATUS instances for property testing - lazily instantiated by
// NetworkSecurityPerimeter_STATUSGenerator()
var networkSecurityPerimeter_STATUSGenerator gopter.Gen

// NetworkSecurityPerimeter_STATUSGenerator returns a generator of NetworkSecurityPerimeter_STATUS instances for property testing.
// We first initialize networkSecurityPerimeter_STATUSGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimeter_STATUSGenerator() gopter.Gen {
	if networkSecurityPerimeter_STATUSGenerator != nil {
		return networkSecurityPerimeter_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimeter_STATUS(generators)
	networkSecurityPerimeter_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimeter_STATUS{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimeter_STATUS(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimeter_STATUS(generators)
	networkSecurityPerimeter_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimeter_STATUS{}), generators)

	return networkSecurityPerimeter_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimeter_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimeter_STATUS(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Location"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["PerimeterGuid"] = gen.PtrOf(gen.AlphaString())
	gens["ProvisioningState"] = gen.PtrOf(gen.OneConstOf(
		NspProvisioningState_STATUS_Accepted,
		NspProvisioningState_STATUS_Creating,
		NspProvisioningState_STATUS_Deleting,
		NspProvisioningState_STATUS_Failed,
		NspProvisioningState_STATUS_Succeeded,
		NspProvisioningState_STATUS_Updating))
	gens["Tags"] = gen.MapOf(
		gen.AlphaString(),
		gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimeter_STATUS is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimeter_STATUS(gens map[string]gopter.Gen) {
	gens["SystemData"] = gen.PtrOf(SecurityPerimeterSystemData_STATUSGenerator())
}

func Test_NetworkSecurityPerimeter_Spec_WhenPropertiesConverted_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from NetworkSecurityPerimeter_Spec to NetworkSecurityPerimeter_Spec via AssignProperties_To_NetworkSecurityPerimeter_Spec & AssignProperties_From_NetworkSecurityPerimeter_Spec returns original",
		prop.ForAll(RunPropertyAssignmentTestForNetworkSecurityPerimeter_Spec, NetworkSecurityPerimeter_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunPropertyAssignmentTestForNetworkSecurityPerimeter_Spec tests if a specific instance of NetworkSecurityPerimeter_Spec can be assigned to storage and back losslessly
func RunPropertyAssignmentTestForNetworkSecurityPerimeter_Spec(subject NetworkSecurityPerimeter_Spec) string {
	// Copy subject to make sure assignment doesn't modify it
	copied := subject.DeepCopy()

	// Use AssignPropertiesTo() for the first stage of conversion
	var other storage.NetworkSecurityPerimeter_Spec
	err := copied.AssignProperties_To_NetworkSecurityPerimeter_Spec(&other)
	if err != nil {
		return err.Error()
	}

	// Use AssignPropertiesFrom() to convert back to our original type
	var actual NetworkSecurityPerimeter_Spec
	err = actual.AssignProperties_From_NetworkSecurityPerimeter_Spec(&other)
	if err != nil {
		return err.Error()
	}

	// Check for a match
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_NetworkSecurityPerimeter_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimeter_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimeter_Spec, NetworkSecurityPerimeter_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimeter_Spec runs a test to see if a specific instance of NetworkSecurityPerimeter_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimeter_Spec(subject NetworkSecurityPerimeter_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimeter_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimeter_Spec instances for property testing - lazily instantiated by
// NetworkSecurityPerimeter_SpecGenerator()
var networkSecurityPerimeter_SpecGenerator gopter.Gen

// NetworkSecurityPerimeter_SpecGenerator returns a generator of NetworkSecurityPerimeter_Spec instances for property testing.
// We first initialize networkSecurityPerimeter_SpecGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimeter_SpecGenerator() gopter.Gen {
	if networkSecurityPerimeter_SpecGenerator != nil {
		return networkSecurityPerimeter_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimeter_Spec(generators)
	networkSecurityPerimeter_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimeter_Spec{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimeter_Spec(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimeter_Spec(generators)
	networkSecurityPerimeter_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimeter_Spec{}), generators)

	return networkSecurityPerimeter_SpecGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimeter_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimeter_Spec(gens map[string]gopter.Gen) {
	gens["AzureName"] = gen.AlphaString()
	gens["Location"] = gen.PtrOf(gen.AlphaString())
	gens["Tags"] = gen.MapOf(
		gen.AlphaString(),
		gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimeter_Spec is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimeter_Spec(gens map[string]gopter.Gen) {
	gens["OperatorSpec"] = gen.PtrOf(NetworkSecurityPerimeterOperatorSpecGenerator())
}

func Test_SecurityPerimeterSystemData_STATUS_WhenPropertiesConverted_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from SecurityPerimeterSystemData_STATUS to SecurityPerimeterSystemData_STATUS via AssignProperties_To_SecurityPerimeterSystemData_STATUS & AssignProperties_From_SecurityPerimeterSystemData_STATUS returns original",
		prop.ForAll(RunPropertyAssignmentTestForSecurityPerimeterSystemData_STATUS, SecurityPerimeterSystemData_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunPropertyAssignmentTestForSecurityPerimeterSystemData_STATUS tests if a specific instance of SecurityPerimeterSystemData_STATUS can be assigned to storage and back losslessly
func RunPropertyAssignmentTestForSecurityPerimeterSystemData_STATUS(subject SecurityPerimeterSystemData_STATUS) string {
	// Copy subject to make sure assignment doesn't modify it
	copied := subject.DeepCopy()

	// Use AssignPropertiesTo() for the first stage of conversion
	var other storage.SecurityPerimeterSystemData_STATUS
	err := copied.AssignProperties_To_SecurityPerimeterSystemData_STATUS(&other)
	if err != nil {
		return err.Error()
	}

	// Use AssignPropertiesFrom() to convert back to our original type
	var actual SecurityPerimeterSystemData_STATUS
	err = actual.AssignProperties_From_SecurityPerimeterSystemData_STATUS(&other)
	if err != nil {
		return err.Error()
	}

	// Check for a match
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_SecurityPerimeterSystemData_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of SecurityPerimeterSystemData_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForSecurityPerimeterSystemData_STATUS, SecurityPerimeterSystemData_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForSecurityPerimeterSystemData_STATUS runs a test to see if a specific instance of SecurityPerimeterSystemData_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForSecurityPerimeterSystemData_STATUS(subject SecurityPerimeterSystemData_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual SecurityPerimeterSystemData_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of SecurityPerimeterSystemData_STATUS instances for property testing - lazily instantiated by
// SecurityPerimeterSystemData_STATUSGenerator()
var securityPerimeterSystemData_STATUSGenerator gopter.Gen

// SecurityPerimeterSystemData_STATUSGenerator returns a generator of SecurityPerimeterSystemData_STATUS instances for property testing.
func SecurityPerimeterSystemData_STATUSGenerator() gopter.Gen {
	if securityPerimeterSystemData_STATUSGenerator != nil {
		return securityPerimeterSystemData_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForSecurityPerimeterSystemData_STATUS(generators)
	securityPerimeterSystemData_STATUSGenerator = gen.Struct(reflect.TypeOf(SecurityPerimeterSystemData_STATUS{}), generators)

	return securityPerimeterSystemData_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForSecurityPerimeterSystemData_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForSecurityPerimeterSystemData_STATUS(gens map[string]gopter.Gen) {
	gens["CreatedAt"] = gen.PtrOf(gen.AlphaString())
	gens["CreatedBy"] = gen.PtrOf(gen.AlphaString())
	gens["CreatedByType"] = gen.PtrOf(gen.OneConstOf(
		CreatedByType_STATUS_Application,
		CreatedByType_STATUS_Key,
		CreatedByType_STATUS_ManagedIdentity,
		CreatedByType_STATUS_User))
	gens["LastModifiedAt"] = gen.PtrOf(gen.AlphaString())
	gens["LastModifiedBy"] = gen.PtrOf(gen.AlphaString())
	gens["LastModifiedByType"] = gen.PtrOf(gen.OneConstOf(
		CreatedByType_STATUS_Application,
		CreatedByType_STATUS_Key,
		CreatedByType_STATUS_ManagedIdentity,
		CreatedByType_STATUS_User))
}
