// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v20250701

import (
	"fmt"
	arm "github.com/Azure/azure-service-operator/v2/api/network/v20250701/arm"
	storage "github.com/Azure/azure-service-operator/v2/api/network/v20250701/storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/conditions"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/configmaps"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/core"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/secrets"
	"github.com/rotisserie/eris"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/conversion"
)

// +kubebuilder:object:root=true
// +kubebuilder:resource:categories={azure,network}
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Severity",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].severity"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].message"
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-07-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/resourceAssociations/{associationName}
type NetworkSecurityPerimetersResourceAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkSecurityPerimetersResourceAssociation_Spec   `json:"spec,omitempty"`
	Status            NetworkSecurityPerimetersResourceAssociation_STATUS `json:"status,omitempty"`
}

var _ conditions.Conditioner = &NetworkSecurityPerimetersResourceAssociation{}

// GetConditions returns the conditions of the resource
func (association *NetworkSecurityPerimetersResourceAssociation) GetConditions() conditions.Conditions {
	return association.Status.Conditions
}

// SetConditions sets the conditions on the resource status
func (association *NetworkSecurityPerimetersResourceAssociation) SetConditions(conditions conditions.Conditions) {
	association.Status.Conditions = conditions
}

var _ conversion.Convertible = &NetworkSecurityPerimetersResourceAssociation{}

// ConvertFrom populates our NetworkSecurityPerimetersResourceAssociation from the provided hub NetworkSecurityPerimetersResourceAssociation
func (association *NetworkSecurityPerimetersResourceAssociation) ConvertFrom(hub conversion.Hub) error {
	source, ok := hub.(*storage.NetworkSecurityPerimetersResourceAssociation)
	if !ok {
		return fmt.Errorf("expected network/v20250701/storage/NetworkSecurityPerimetersResourceAssociation but received %T instead", hub)
	}

	return association.AssignProperties_From_NetworkSecurityPerimetersResourceAssociation(source)
}

// ConvertTo populates the provided hub NetworkSecurityPerimetersResourceAssociation from our NetworkSecurityPerimetersResourceAssociation
func (association *NetworkSecurityPerimetersResourceAssociation) ConvertTo(hub conversion.Hub) error {
	destination, ok := hub.(*storage.NetworkSecurityPerimetersResourceAssociation)
	if !ok {
		return fmt.Errorf("expected network/v20250701/storage/NetworkSecurityPerimetersResourceAssociation but received %T instead", hub)
	}

	return association.AssignProperties_To_NetworkSecurityPerimetersResourceAssociation(destination)
}

var _ configmaps.Exporter = &NetworkSecurityPerimetersResourceAssociation{}

// ConfigMapDestinationExpressions returns the Spec.OperatorSpec.ConfigMapExpressions property
func (association *NetworkSecurityPerimetersResourceAssociation) ConfigMapDestinationExpressions() []*core.DestinationExpression {
	if association.Spec.OperatorSpec == nil {
		return nil
	}
	return association.Spec.OperatorSpec.ConfigMapExpressions
}

var _ secrets.Exporter = &NetworkSecurityPerimetersResourceAssociation{}

// SecretDestinationExpressions returns the Spec.OperatorSpec.SecretExpressions property
func (association *NetworkSecurityPerimetersResourceAssociation) SecretDestinationExpressions() []*core.DestinationExpression {
	if association.Spec.OperatorSpec == nil {
		return nil
	}
	return association.Spec.OperatorSpec.SecretExpressions
}

var _ genruntime.ImportableResource = &NetworkSecurityPerimetersResourceAssociation{}

// InitializeSpec initializes the spec for this resource from the given status
func (association *NetworkSecurityPerimetersResourceAssociation) InitializeSpec(status genruntime.ConvertibleStatus) error {
	if s, ok := status.(*NetworkSecurityPerimetersResourceAssociation_STATUS); ok {
		return association.Spec.Initialize_From_NetworkSecurityPerimetersResourceAssociation_STATUS(s)
	}

	return fmt.Errorf("expected Status of type NetworkSecurityPerimetersResourceAssociation_STATUS but received %T instead", status)
}

var _ genruntime.KubernetesResource = &NetworkSecurityPerimetersResourceAssociation{}

// AzureName returns the Azure name of the resource
func (association *NetworkSecurityPerimetersResourceAssociation) AzureName() string {
	return association.Spec.AzureName
}

// GetAPIVersion returns the ARM API version of the resource. This is always "2025-07-01"
func (association NetworkSecurityPerimetersResourceAssociation) GetAPIVersion() string {
	return "2025-07-01"
}

// GetResourceScope returns the scope of the resource
func (association *NetworkSecurityPerimetersResourceAssociation) GetResourceScope() genruntime.ResourceScope {
	return genruntime.ResourceScopeResourceGroup
}

// GetSpec returns the specification of this resource
func (association *NetworkSecurityPerimetersResourceAssociation) GetSpec() genruntime.ConvertibleSpec {
	return &association.Spec
}

// GetStatus returns the status of this resource
func (association *NetworkSecurityPerimetersResourceAssociation) GetStatus() genruntime.ConvertibleStatus {
	return &association.Status
}

// GetSupportedOperations returns the operations supported by the resource
func (association *NetworkSecurityPerimetersResourceAssociation) GetSupportedOperations() []genruntime.ResourceOperation {
	return []genruntime.ResourceOperation{
		genruntime.ResourceOperationDelete,
		genruntime.ResourceOperationGet,
		genruntime.ResourceOperationPut,
	}
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Network/networkSecurityPerimeters/resourceAssociations"
func (association *NetworkSecurityPerimetersResourceAssociation) GetType() string {
	return "Microsoft.Network/networkSecurityPerimeters/resourceAssociations"
}

// NewEmptyStatus returns a new empty (blank) status
func (association *NetworkSecurityPerimetersResourceAssociation) NewEmptyStatus() genruntime.ConvertibleStatus {
	return &NetworkSecurityPerimetersResourceAssociation_STATUS{}
}

// Owner returns the ResourceReference of the owner
func (association *NetworkSecurityPerimetersResourceAssociation) Owner() *genruntime.ResourceReference {
	if association.Spec.Owner == nil {
		return nil
	}

	group, kind := genruntime.LookupOwnerGroupKind(association.Spec)
	return association.Spec.Owner.AsResourceReference(group, kind)
}

// SetStatus sets the status of this resource
func (association *NetworkSecurityPerimetersResourceAssociation) SetStatus(status genruntime.ConvertibleStatus) error {
	// If we have exactly the right type of status, assign it
	if st, ok := status.(*NetworkSecurityPerimetersResourceAssociation_STATUS); ok {
		association.Status = *st
		return nil
	}

	// Convert status to required version
	var st NetworkSecurityPerimetersResourceAssociation_STATUS
	err := status.ConvertStatusTo(&st)
	if err != nil {
		return eris.Wrap(err, "failed to convert status")
	}

	association.Status = st
	return nil
}

// AssignProperties_From_NetworkSecurityPerimetersResourceAssociation populates our NetworkSecurityPerimetersResourceAssociation from the provided source NetworkSecurityPerimetersResourceAssociation
func (association *NetworkSecurityPerimetersResourceAssociation) AssignProperties_From_NetworkSecurityPerimetersResourceAssociation(source *storage.NetworkSecurityPerimetersResourceAssociation) error {

	// ObjectMeta
	association.ObjectMeta = *source.ObjectMeta.DeepCopy()

	// Spec
	var spec NetworkSecurityPerimetersResourceAssociation_Spec
	err := spec.AssignProperties_From_NetworkSecurityPerimetersResourceAssociation_Spec(&source.Spec)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_From_NetworkSecurityPerimetersResourceAssociation_Spec() to populate field Spec")
	}
	association.Spec = spec

	// Status
	var status NetworkSecurityPerimetersResourceAssociation_STATUS
	err = status.AssignProperties_From_NetworkSecurityPerimetersResourceAssociation_STATUS(&source.Status)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_From_NetworkSecurityPerimetersResourceAssociation_STATUS() to populate field Status")
	}
	association.Status = status

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersResourceAssociation populates the provided destination NetworkSecurityPerimetersResourceAssociation from our NetworkSecurityPerimetersResourceAssociation
func (association *NetworkSecurityPerimetersResourceAssociation) AssignProperties_To_NetworkSecurityPerimetersResourceAssociation(destination *storage.NetworkSecurityPerimetersResourceAssociation) error {

	// ObjectMeta
	destination.ObjectMeta = *association.ObjectMeta.DeepCopy()

	// Spec
	var spec storage.NetworkSecurityPerimetersResourceAssociation_Spec
	err := association.Spec.AssignProperties_To_NetworkSecurityPerimetersResourceAssociation_Spec(&spec)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_To_NetworkSecurityPerimetersResourceAssociation_Spec() to populate field Spec")
	}
	destination.Spec = spec

	// Status
	var status storage.NetworkSecurityPerimetersResourceAssociation_STATUS
	err = association.Status.AssignProperties_To_NetworkSecurityPerimetersResourceAssociation_STATUS(&status)
	if err != nil {
		return eris.Wrap(err, "calling AssignProperties_To_NetworkSecurityPerimetersResourceAssociation_STATUS() to populate field Status")
	}
	destination.Status = status

	// No error
	return nil
}

// OriginalGVK returns a GroupValueKind for the original API version used to create the resource
func (association *NetworkSecurityPerimetersResourceAssociation) OriginalGVK() *schema.GroupVersionKind {
	return &schema.GroupVersionKind{
		Group:   GroupVersion.Group,
		Version: association.Spec.OriginalVersion(),
		Kind:    "NetworkSecurityPerimetersResourceAssociation",
	}
}

// +kubebuilder:object:root=true
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-07-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/resourceAssociations/{associationName}
type NetworkSecurityPerimetersResourceAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkSecurityPerimetersResourceAssociation `json:"items"`
}

type NetworkSecurityPerimetersResourceAssociation_Spec struct {
	// AccessMode: Access mode on the association.
	AccessMode *AssociationAccessMode `json:"accessMode,omitempty"`

	// +kubebuilder:validation:MaxLength=80
	// +kubebuilder:validation:Pattern="(^[a-zA-Z0-9]+[a-zA-Z0-9_.-]*[a-zA-Z0-9_]+$)|(^[a-zA-Z0-9]$)"
	// AzureName: The name of the resource in Azure. This is often the same as the name of the resource in Kubernetes but it
	// doesn't have to be.
	AzureName string `json:"azureName,omitempty"`

	// OperatorSpec: The specification for configuring operator behavior. This field is interpreted by the operator and not
	// passed directly to Azure
	OperatorSpec *NetworkSecurityPerimetersResourceAssociationOperatorSpec `json:"operatorSpec,omitempty"`

	// +kubebuilder:validation:Required
	// Owner: The owner of the resource. The owner controls where the resource goes when it is deployed. The owner also
	// controls the resources lifecycle. When the owner is deleted the resource will also be deleted. Owner is expected to be a
	// reference to a network.azure.com/NetworkSecurityPerimeter resource
	Owner *genruntime.KnownResourceReference `group:"network.azure.com" json:"owner,omitempty" kind:"NetworkSecurityPerimeter"`

	// PrivateLinkResource: The PaaS resource to be associated.
	PrivateLinkResource *CommonSubResource `json:"privateLinkResource,omitempty"`

	// Profile: Profile id to which the PaaS resource is associated.
	Profile *CommonSubResource `json:"profile,omitempty"`
}

var _ genruntime.ARMTransformer = &NetworkSecurityPerimetersResourceAssociation_Spec{}

// ConvertToARM converts from a Kubernetes CRD object to an ARM object
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) ConvertToARM(resolved genruntime.ConvertToARMResolvedDetails) (interface{}, error) {
	if association == nil {
		return nil, nil
	}
	result := &arm.NetworkSecurityPerimetersResourceAssociation_Spec{}

	// Set property "Name":
	result.Name = resolved.Name

	// Set property "Properties":
	if association.AccessMode != nil ||
		association.PrivateLinkResource != nil ||
		association.Profile != nil {
		result.Properties = &arm.NspAssociationProperties{}
	}
	if association.AccessMode != nil {
		var temp string
		temp = string(*association.AccessMode)
		accessMode := arm.AssociationAccessMode(temp)
		result.Properties.AccessMode = &accessMode
	}
	if association.PrivateLinkResource != nil {
		privateLinkResource_ARM, err := association.PrivateLinkResource.ConvertToARM(resolved)
		if err != nil {
			return nil, err
		}
		privateLinkResource := *privateLinkResource_ARM.(*arm.CommonSubResource)
		result.Properties.PrivateLinkResource = &privateLinkResource
	}
	if association.Profile != nil {
		profile_ARM, err := association.Profile.ConvertToARM(resolved)
		if err != nil {
			return nil, err
		}
		profile := *profile_ARM.(*arm.CommonSubResource)
		result.Properties.Profile = &profile
	}
	return result, nil
}

// NewEmptyARMValue returns an empty ARM value suitable for deserializing into
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) NewEmptyARMValue() genruntime.ARMResourceStatus {
	return &arm.NetworkSecurityPerimetersResourceAssociation_Spec{}
}

// PopulateFromARM populates a Kubernetes CRD object from an Azure ARM object
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) PopulateFromARM(owner genruntime.ArbitraryOwnerReference, armInput interface{}) error {
	typedInput, ok := armInput.(arm.NetworkSecurityPerimetersResourceAssociation_Spec)
	if !ok {
		return fmt.Errorf("unexpected type supplied for PopulateFromARM() function. Expected arm.NetworkSecurityPerimetersResourceAssociation_Spec, got %T", armInput)
	}

	// Set property "AccessMode":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.AccessMode != nil {
			var temp string
			temp = string(*typedInput.Properties.AccessMode)
			accessMode := AssociationAccessMode(temp)
			association.AccessMode = &accessMode
		}
	}

	// Set property "AzureName":
	association.SetAzureName(genruntime.ExtractKubernetesResourceNameFromARMName(typedInput.Name))

	// no assignment for property "OperatorSpec"

	// Set property "Owner":
	association.Owner = &genruntime.KnownResourceReference{
		Name:  owner.Name,
		ARMID: owner.ARMID,
	}

	// Set property "PrivateLinkResource":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.PrivateLinkResource != nil {
			var privateLinkResource1 CommonSubResource
			err := privateLinkResource1.PopulateFromARM(owner, *typedInput.Properties.PrivateLinkResource)
			if err != nil {
				return err
			}
			privateLinkResource := privateLinkResource1
			association.PrivateLinkResource = &privateLinkResource
		}
	}

	// Set property "Profile":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.Profile != nil {
			var profile1 CommonSubResource
			err := profile1.PopulateFromARM(owner, *typedInput.Properties.Profile)
			if err != nil {
				return err
			}
			profile := profile1
			association.Profile = &profile
		}
	}

	// No error
	return nil
}

var _ genruntime.ConvertibleSpec = &NetworkSecurityPerimetersResourceAssociation_Spec{}

// ConvertSpecFrom populates our NetworkSecurityPerimetersResourceAssociation_Spec from the provided source
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) ConvertSpecFrom(source genruntime.ConvertibleSpec) error {
	src, ok := source.(*storage.NetworkSecurityPerimetersResourceAssociation_Spec)
	if ok {
		// Populate our instance from source
		return association.AssignProperties_From_NetworkSecurityPerimetersResourceAssociation_Spec(src)
	}

	// Convert to an intermediate form
	src = &storage.NetworkSecurityPerimetersResourceAssociation_Spec{}
	err := src.ConvertSpecFrom(source)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertSpecFrom()")
	}

	// Update our instance from src
	err = association.AssignProperties_From_NetworkSecurityPerimetersResourceAssociation_Spec(src)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertSpecFrom()")
	}

	return nil
}

// ConvertSpecTo populates the provided destination from our NetworkSecurityPerimetersResourceAssociation_Spec
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) ConvertSpecTo(destination genruntime.ConvertibleSpec) error {
	dst, ok := destination.(*storage.NetworkSecurityPerimetersResourceAssociation_Spec)
	if ok {
		// Populate destination from our instance
		return association.AssignProperties_To_NetworkSecurityPerimetersResourceAssociation_Spec(dst)
	}

	// Convert to an intermediate form
	dst = &storage.NetworkSecurityPerimetersResourceAssociation_Spec{}
	err := association.AssignProperties_To_NetworkSecurityPerimetersResourceAssociation_Spec(dst)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertSpecTo()")
	}

	// Update dst from our instance
	err = dst.ConvertSpecTo(destination)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertSpecTo()")
	}

	return nil
}

// AssignProperties_From_NetworkSecurityPerimetersResourceAssociation_Spec populates our NetworkSecurityPerimetersResourceAssociation_Spec from the provided source NetworkSecurityPerimetersResourceAssociation_Spec
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) AssignProperties_From_NetworkSecurityPerimetersResourceAssociation_Spec(source *storage.NetworkSecurityPerimetersResourceAssociation_Spec) error {

	// AccessMode
	if source.AccessMode != nil {
		accessMode := *source.AccessMode
		accessModeTemp := genruntime.ToEnum(accessMode, associationAccessMode_Values)
		association.AccessMode = &accessModeTemp
	} else {
		association.AccessMode = nil
	}

	// AzureName
	association.AzureName = source.AzureName

	// OperatorSpec
	if source.OperatorSpec != nil {
		var operatorSpec NetworkSecurityPerimetersResourceAssociationOperatorSpec
		err := operatorSpec.AssignProperties_From_NetworkSecurityPerimetersResourceAssociationOperatorSpec(source.OperatorSpec)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_From_NetworkSecurityPerimetersResourceAssociationOperatorSpec() to populate field OperatorSpec")
		}
		association.OperatorSpec = &operatorSpec
	} else {
		association.OperatorSpec = nil
	}

	// Owner
	if source.Owner != nil {
		owner := source.Owner.Copy()
		association.Owner = &owner
	} else {
		association.Owner = nil
	}

	// PrivateLinkResource
	if source.PrivateLinkResource != nil {
		var privateLinkResource CommonSubResource
		err := privateLinkResource.AssignProperties_From_CommonSubResource(source.PrivateLinkResource)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_From_CommonSubResource() to populate field PrivateLinkResource")
		}
		association.PrivateLinkResource = &privateLinkResource
	} else {
		association.PrivateLinkResource = nil
	}

	// Profile
	if source.Profile != nil {
		var profile CommonSubResource
		err := profile.AssignProperties_From_CommonSubResource(source.Profile)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_From_CommonSubResource() to populate field Profile")
		}
		association.Profile = &profile
	} else {
		association.Profile = nil
	}

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersResourceAssociation_Spec populates the provided destination NetworkSecurityPerimetersResourceAssociation_Spec from our NetworkSecurityPerimetersResourceAssociation_Spec
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) AssignProperties_To_NetworkSecurityPerimetersResourceAssociation_Spec(destination *storage.NetworkSecurityPerimetersResourceAssociation_Spec) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// AccessMode
	if association.AccessMode != nil {
		accessMode := string(*association.AccessMode)
		destination.AccessMode = &accessMode
	} else {
		destination.AccessMode = nil
	}

	// AzureName
	destination.AzureName = association.AzureName

	// OperatorSpec
	if association.OperatorSpec != nil {
		var operatorSpec storage.NetworkSecurityPerimetersResourceAssociationOperatorSpec
		err := association.OperatorSpec.AssignProperties_To_NetworkSecurityPerimetersResourceAssociationOperatorSpec(&operatorSpec)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_To_NetworkSecurityPerimetersResourceAssociationOperatorSpec() to populate field OperatorSpec")
		}
		destination.OperatorSpec = &operatorSpec
	} else {
		destination.OperatorSpec = nil
	}

	// OriginalVersion
	destination.OriginalVersion = association.OriginalVersion()

	// Owner
	if association.Owner != nil {
		owner := association.Owner.Copy()
		destination.Owner = &owner
	} else {
		destination.Owner = nil
	}

	// PrivateLinkResource
	if association.PrivateLinkResource != nil {
		var privateLinkResource storage.CommonSubResource
		err := association.PrivateLinkResource.AssignProperties_To_CommonSubResource(&privateLinkResource)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_To_CommonSubResource() to populate field PrivateLinkResource")
		}
		destination.PrivateLinkResource = &privateLinkResource
	} else {
		destination.PrivateLinkResource = nil
	}

	// Profile
	if association.Profile != nil {
		var profile storage.CommonSubResource
		err := association.Profile.AssignProperties_To_CommonSubResource(&profile)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_To_CommonSubResource() to populate field Profile")
		}
		destination.Profile = &profile
	} else {
		destination.Profile = nil
	}

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

// Initialize_From_NetworkSecurityPerimetersResourceAssociation_STATUS populates our NetworkSecurityPerimetersResourceAssociation_Spec from the provided source NetworkSecurityPerimetersResourceAssociation_STATUS
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) Initialize_From_NetworkSecurityPerimetersResourceAssociation_STATUS(source *NetworkSecurityPerimetersResourceAssociation_STATUS) error {

	// AccessMode
	if source.AccessMode != nil {
		accessMode := genruntime.ToEnum(string(*source.AccessMode), associationAccessMode_Values)
		association.AccessMode = &accessMode
	} else {
		association.AccessMode = nil
	}

	// PrivateLinkResource
	if source.PrivateLinkResource != nil {
		var privateLinkResource CommonSubResource
		err := privateLinkResource.Initialize_From_CommonSubResource_STATUS(source.PrivateLinkResource)
		if err != nil {
			return eris.Wrap(err, "calling Initialize_From_CommonSubResource_STATUS() to populate field PrivateLinkResource")
		}
		association.PrivateLinkResource = &privateLinkResource
	} else {
		association.PrivateLinkResource = nil
	}

	// Profile
	if source.Profile != nil {
		var profile CommonSubResource
		err := profile.Initialize_From_CommonSubResource_STATUS(source.Profile)
		if err != nil {
			return eris.Wrap(err, "calling Initialize_From_CommonSubResource_STATUS() to populate field Profile")
		}
		association.Profile = &profile
	} else {
		association.Profile = nil
	}

	// No error
	return nil
}

// OriginalVersion returns the original API version used to create the resource.
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) OriginalVersion() string {
	return GroupVersion.Version
}

// SetAzureName sets the Azure name of the resource
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) SetAzureName(azureName string) {
	association.AzureName = azureName
}

type NetworkSecurityPerimetersResourceAssociation_STATUS struct {
	// AccessMode: Access mode on the association.
	AccessMode *AssociationAccessMode_STATUS `json:"accessMode,omitempty"`

	// Conditions: The observed state of the resource
	Conditions []conditions.Condition `json:"conditions,omitempty"`

	// HasProvisioningIssues: Specifies if there are provisioning issues
	HasProvisioningIssues *string `json:"hasProvisioningIssues,omitempty"`

	// Id: Fully qualified resource ID for the resource. E.g.
	// "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id *string `json:"id,omitempty"`

	// Name: The name of the resource
	Name *string `json:"name,omitempty"`

	// PrivateLinkResource: The PaaS resource to be associated.
	PrivateLinkResource *CommonSubResource_STATUS `json:"privateLinkResource,omitempty"`

	// Profile: Profile id to which the PaaS resource is associated.
	Profile *CommonSubResource_STATUS `json:"profile,omitempty"`

	// ProvisioningState: The provisioning state of the resource  association resource.
	ProvisioningState *NspProvisioningState_STATUS `json:"provisioningState,omitempty"`

	// SystemData: Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SecurityPerimeterSystemData_STATUS `json:"systemData,omitempty"`

	// Type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`
}

var _ genruntime.ConvertibleStatus = &NetworkSecurityPerimetersResourceAssociation_STATUS{}

// ConvertStatusFrom populates our NetworkSecurityPerimetersResourceAssociation_STATUS from the provided source
func (association *NetworkSecurityPerimetersResourceAssociation_STATUS) ConvertStatusFrom(source genruntime.ConvertibleStatus) error {
	src, ok := source.(*storage.NetworkSecurityPerimetersResourceAssociation_STATUS)
	if ok {
		// Populate our instance from source
		return association.AssignProperties_From_NetworkSecurityPerimetersResourceAssociation_STATUS(src)
	}

	// Convert to an intermediate form
	src = &storage.NetworkSecurityPerimetersResourceAssociation_STATUS{}
	err := src.ConvertStatusFrom(source)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertStatusFrom()")
	}

	// Update our instance from src
	err = association.AssignProperties_From_NetworkSecurityPerimetersResourceAssociation_STATUS(src)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertStatusFrom()")
	}

	return nil
}

// ConvertStatusTo populates the provided destination from our NetworkSecurityPerimetersResourceAssociation_STATUS
func (association *NetworkSecurityPerimetersResourceAssociation_STATUS) ConvertStatusTo(destination genruntime.ConvertibleStatus) error {
	dst, ok := destination.(*storage.NetworkSecurityPerimetersResourceAssociation_STATUS)
	if ok {
		// Populate destination from our instance
		return association.AssignProperties_To_NetworkSecurityPerimetersResourceAssociation_STATUS(dst)
	}

	// Convert to an intermediate form
	dst = &storage.NetworkSecurityPerimetersResourceAssociation_STATUS{}
	err := association.AssignProperties_To_NetworkSecurityPerimetersResourceAssociation_STATUS(dst)
	if err != nil {
		return eris.Wrap(err, "initial step of conversion in ConvertStatusTo()")
	}

	// Update dst from our instance
	err = dst.ConvertStatusTo(destination)
	if err != nil {
		return eris.Wrap(err, "final step of conversion in ConvertStatusTo()")
	}

	return nil
}

var _ genruntime.FromARMConverter = &NetworkSecurityPerimetersResourceAssociation_STATUS{}

// NewEmptyARMValue returns an empty ARM value suitable for deserializing into
func (association *NetworkSecurityPerimetersResourceAssociation_STATUS) NewEmptyARMValue() genruntime.ARMResourceStatus {
	return &arm.NetworkSecurityPerimetersResourceAssociation_STATUS{}
}

// PopulateFromARM populates a Kubernetes CRD object from an Azure ARM object
func (association *NetworkSecurityPerimetersResourceAssociation_STATUS) PopulateFromARM(owner genruntime.ArbitraryOwnerReference, armInput interface{}) error {
	typedInput, ok := armInput.(arm.NetworkSecurityPerimetersResourceAssociation_STATUS)
	if !ok {
		return fmt.Errorf("unexpected type supplied for PopulateFromARM() function. Expected arm.NetworkSecurityPerimetersResourceAssociation_STATUS, got %T", armInput)
	}

	// Set property "AccessMode":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.AccessMode != nil {
			var temp string
			temp = string(*typedInput.Properties.AccessMode)
			accessMode := AssociationAccessMode_STATUS(temp)
			association.AccessMode = &accessMode
		}
	}

	// no assignment for property "Conditions"

	// Set property "HasProvisioningIssues":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.HasProvisioningIssues != nil {
			hasProvisioningIssues := *typedInput.Properties.HasProvisioningIssues
			association.HasProvisioningIssues = &hasProvisioningIssues
		}
	}

	// Set property "Id":
	if typedInput.Id != nil {
		id := *typedInput.Id
		association.Id = &id
	}

	// Set property "Name":
	if typedInput.Name != nil {
		name := *typedInput.Name
		association.Name = &name
	}

	// Set property "PrivateLinkResource":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.PrivateLinkResource != nil {
			var privateLinkResource1 CommonSubResource_STATUS
			err := privateLinkResource1.PopulateFromARM(owner, *typedInput.Properties.PrivateLinkResource)
			if err != nil {
				return err
			}
			privateLinkResource := privateLinkResource1
			association.PrivateLinkResource = &privateLinkResource
		}
	}

	// Set property "Profile":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.Profile != nil {
			var profile1 CommonSubResource_STATUS
			err := profile1.PopulateFromARM(owner, *typedInput.Properties.Profile)
			if err != nil {
				return err
			}
			profile := profile1
			association.Profile = &profile
		}
	}

	// Set property "ProvisioningState":
	// copying flattened property:
	if typedInput.Properties != nil {
		if typedInput.Properties.ProvisioningState != nil {
			var temp string
			temp = string(*typedInput.Properties.ProvisioningState)
			provisioningState := NspProvisioningState_STATUS(temp)
			association.ProvisioningState = &provisioningState
		}
	}

	// Set property "SystemData":
	if typedInput.SystemData != nil {
		var systemData1 SecurityPerimeterSystemData_STATUS
		err := systemData1.PopulateFromARM(owner, *typedInput.SystemData)
		if err != nil {
			return err
		}
		systemData := systemData1
		association.SystemData = &systemData
	}

	// Set property "Type":
	if typedInput.Type != nil {
		typeVar := *typedInput.Type
		association.Type = &typeVar
	}

	// No error
	return nil
}

// AssignProperties_From_NetworkSecurityPerimetersResourceAssociation_STATUS populates our NetworkSecurityPerimetersResourceAssociation_STATUS from the provided source NetworkSecurityPerimetersResourceAssociation_STATUS
func (association *NetworkSecurityPerimetersResourceAssociation_STATUS) AssignProperties_From_NetworkSecurityPerimetersResourceAssociation_STATUS(source *storage.NetworkSecurityPerimetersResourceAssociation_STATUS) error {

	// AccessMode
	if source.AccessMode != nil {
		accessMode := *source.AccessMode
		accessModeTemp := genruntime.ToEnum(accessMode, associationAccessMode_STATUS_Values)
		association.AccessMode = &accessModeTemp
	} else {
		association.AccessMode = nil
	}

	// Conditions
	association.Conditions = genruntime.CloneSliceOfCondition(source.Conditions)

	// HasProvisioningIssues
	association.HasProvisioningIssues = genruntime.ClonePointerToString(source.HasProvisioningIssues)

	// Id
	association.Id = genruntime.ClonePointerToString(source.Id)

	// Name
	association.Name = genruntime.ClonePointerToString(source.Name)

	// PrivateLinkResource
	if source.PrivateLinkResource != nil {
		var privateLinkResource CommonSubResource_STATUS
		err := privateLinkResource.AssignProperties_From_CommonSubResource_STATUS(source.PrivateLinkResource)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_From_CommonSubResource_STATUS() to populate field PrivateLinkResource")
		}
		association.PrivateLinkResource = &privateLinkResource
	} else {
		association.PrivateLinkResource = nil
	}

	// Profile
	if source.Profile != nil {
		var profile CommonSubResource_STATUS
		err := profile.AssignProperties_From_CommonSubResource_STATUS(source.Profile)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_From_CommonSubResource_STATUS() to populate field Profile")
		}
		association.Profile = &profile
	} else {
		association.Profile = nil
	}

	// ProvisioningState
	if source.ProvisioningState != nil {
		provisioningState := *source.ProvisioningState
		provisioningStateTemp := genruntime.ToEnum(provisioningState, nspProvisioningState_STATUS_Values)
		association.ProvisioningState = &provisioningStateTemp
	} else {
		association.ProvisioningState = nil
	}

	// SystemData
	if source.SystemData != nil {
		var systemDatum SecurityPerimeterSystemData_STATUS
		err := systemDatum.AssignProperties_From_SecurityPerimeterSystemData_STATUS(source.SystemData)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_From_SecurityPerimeterSystemData_STATUS() to populate field SystemData")
		}
		association.SystemData = &systemDatum
	} else {
		association.SystemData = nil
	}

	// Type
	association.Type = genruntime.ClonePointerToString(source.Type)

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersResourceAssociation_STATUS populates the provided destination NetworkSecurityPerimetersResourceAssociation_STATUS from our NetworkSecurityPerimetersResourceAssociation_STATUS
func (association *NetworkSecurityPerimetersResourceAssociation_STATUS) AssignProperties_To_NetworkSecurityPerimetersResourceAssociation_STATUS(destination *storage.NetworkSecurityPerimetersResourceAssociation_STATUS) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// AccessMode
	if association.AccessMode != nil {
		accessMode := string(*association.AccessMode)
		destination.AccessMode = &accessMode
	} else {
		destination.AccessMode = nil
	}

	// Conditions
	destination.Conditions = genruntime.CloneSliceOfCondition(association.Conditions)

	// HasProvisioningIssues
	destination.HasProvisioningIssues = genruntime.ClonePointerToString(association.HasProvisioningIssues)

	// Id
	destination.Id = genruntime.ClonePointerToString(association.Id)

	// Name
	destination.Name = genruntime.ClonePointerToString(association.Name)

	// PrivateLinkResource
	if association.PrivateLinkResource != nil {
		var privateLinkResource storage.CommonSubResource_STATUS
		err := association.PrivateLinkResource.AssignProperties_To_CommonSubResource_STATUS(&privateLinkResource)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_To_CommonSubResource_STATUS() to populate field PrivateLinkResource")
		}
		destination.PrivateLinkResource = &privateLinkResource
	} else {
		destination.PrivateLinkResource = nil
	}

	// Profile
	if association.Profile != nil {
		var profile storage.CommonSubResource_STATUS
		err := association.Profile.AssignProperties_To_CommonSubResource_STATUS(&profile)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_To_CommonSubResource_STATUS() to populate field Profile")
		}
		destination.Profile = &profile
	} else {
		destination.Profile = nil
	}

	// ProvisioningState
	if association.ProvisioningState != nil {
		provisioningState := string(*association.ProvisioningState)
		destination.ProvisioningState = &provisioningState
	} else {
		destination.ProvisioningState = nil
	}

	// SystemData
	if association.SystemData != nil {
		var systemDatum storage.SecurityPerimeterSystemData_STATUS
		err := association.SystemData.AssignProperties_To_SecurityPerimeterSystemData_STATUS(&systemDatum)
		if err != nil {
			return eris.Wrap(err, "calling AssignProperties_To_SecurityPerimeterSystemData_STATUS() to populate field SystemData")
		}
		destination.SystemData = &systemDatum
	} else {
		destination.SystemData = nil
	}

	// Type
	destination.Type = genruntime.ClonePointerToString(association.Type)

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

// Access mode on the association.
// +kubebuilder:validation:Enum={"Audit","Enforced","Learning"}
type AssociationAccessMode string

const (
	AssociationAccessMode_Audit    = AssociationAccessMode("Audit")
	AssociationAccessMode_Enforced = AssociationAccessMode("Enforced")
	AssociationAccessMode_Learning = AssociationAccessMode("Learning")
)

// Mapping from string to AssociationAccessMode
var associationAccessMode_Values = map[string]AssociationAccessMode{
	"audit":    AssociationAccessMode_Audit,
	"enforced": AssociationAccessMode_Enforced,
	"learning": AssociationAccessMode_Learning,
}

// Access mode on the association.
type AssociationAccessMode_STATUS string

const (
	AssociationAccessMode_STATUS_Audit    = AssociationAccessMode_STATUS("Audit")
	AssociationAccessMode_STATUS_Enforced = AssociationAccessMode_STATUS("Enforced")
	AssociationAccessMode_STATUS_Learning = AssociationAccessMode_STATUS("Learning")
)

// Mapping from string to AssociationAccessMode_STATUS
var associationAccessMode_STATUS_Values = map[string]AssociationAccessMode_STATUS{
	"audit":    AssociationAccessMode_STATUS_Audit,
	"enforced": AssociationAccessMode_STATUS_Enforced,
	"learning": AssociationAccessMode_STATUS_Learning,
}

// Reference to another subresource.
type CommonSubResource struct {
	// Reference: Resource ID.
	Reference *genruntime.ResourceReference `armReference:"Id" json:"reference,omitempty"`
}

var _ genruntime.ARMTransformer = &CommonSubResource{}

// ConvertToARM converts from a Kubernetes CRD object to an ARM object
func (resource *CommonSubResource) ConvertToARM(resolved genruntime.ConvertToARMResolvedDetails) (interface{}, error) {
	if resource == nil {
		return nil, nil
	}
	result := &arm.CommonSubResource{}

	// Set property "Id":
	if resource.Reference != nil {
		referenceARMID, err := resolved.ResolvedReferences.Lookup(*resource.Reference)
		if err != nil {
			return nil, err
		}
		reference := referenceARMID
		result.Id = &reference
	}
	return result, nil
}

// NewEmptyARMValue returns an empty ARM value suitable for deserializing into
func (resource *CommonSubResource) NewEmptyARMValue() genruntime.ARMResourceStatus {
	return &arm.CommonSubResource{}
}

// PopulateFromARM populates a Kubernetes CRD object from an Azure ARM object
func (resource *CommonSubResource) PopulateFromARM(owner genruntime.ArbitraryOwnerReference, armInput interface{}) error {
	_, ok := armInput.(arm.CommonSubResource)
	if !ok {
		return fmt.Errorf("unexpected type supplied for PopulateFromARM() function. Expected arm.CommonSubResource, got %T", armInput)
	}

	// no assignment for property "Reference"

	// No error
	return nil
}

// AssignProperties_From_CommonSubResource populates our CommonSubResource from the provided source CommonSubResource
func (resource *CommonSubResource) AssignProperties_From_CommonSubResource(source *storage.CommonSubResource) error {

	// Reference
	if source.Reference != nil {
		reference := source.Reference.Copy()
		resource.Reference = &reference
	} else {
		resource.Reference = nil
	}

	// No error
	return nil
}

// AssignProperties_To_CommonSubResource populates the provided destination CommonSubResource from our CommonSubResource
func (resource *CommonSubResource) AssignProperties_To_CommonSubResource(destination *storage.CommonSubResource) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// Reference
	if resource.Reference != nil {
		reference := resource.Reference.Copy()
		destination.Reference = &reference
	} else {
		destination.Reference = nil
	}

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

// Initialize_From_CommonSubResource_STATUS populates our CommonSubResource from the provided source CommonSubResource_STATUS
func (resource *CommonSubResource) Initialize_From_CommonSubResource_STATUS(source *CommonSubResource_STATUS) error {

	// Reference
	if source.Id != nil {
		reference := genruntime.CreateResourceReferenceFromARMID(*source.Id)
		resource.Reference = &reference
	} else {
		resource.Reference = nil
	}

	// No error
	return nil
}

// Reference to another subresource.
type CommonSubResource_STATUS struct {
	// Id: Resource ID.
	Id *string `json:"id,omitempty"`
}

var _ genruntime.FromARMConverter = &CommonSubResource_STATUS{}

// NewEmptyARMValue returns an empty ARM value suitable for deserializing into
func (resource *CommonSubResource_STATUS) NewEmptyARMValue() genruntime.ARMResourceStatus {
	return &arm.CommonSubResource_STATUS{}
}

// PopulateFromARM populates a Kubernetes CRD object from an Azure ARM object
func (resource *CommonSubResource_STATUS) PopulateFromARM(owner genruntime.ArbitraryOwnerReference, armInput interface{}) error {
	typedInput, ok := armInput.(arm.CommonSubResource_STATUS)
	if !ok {
		return fmt.Errorf("unexpected type supplied for PopulateFromARM() function. Expected arm.CommonSubResource_STATUS, got %T", armInput)
	}

	// Set property "Id":
	if typedInput.Id != nil {
		id := *typedInput.Id
		resource.Id = &id
	}

	// No error
	return nil
}

// AssignProperties_From_CommonSubResource_STATUS populates our CommonSubResource_STATUS from the provided source CommonSubResource_STATUS
func (resource *CommonSubResource_STATUS) AssignProperties_From_CommonSubResource_STATUS(source *storage.CommonSubResource_STATUS) error {

	// Id
	resource.Id = genruntime.ClonePointerToString(source.Id)

	// No error
	return nil
}

// AssignProperties_To_CommonSubResource_STATUS populates the provided destination CommonSubResource_STATUS from our CommonSubResource_STATUS
func (resource *CommonSubResource_STATUS) AssignProperties_To_CommonSubResource_STATUS(destination *storage.CommonSubResource_STATUS) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// Id
	destination.Id = genruntime.ClonePointerToString(resource.Id)

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

// Details for configuring operator behavior. Fields in this struct are interpreted by the operator directly rather than being passed to Azure
type NetworkSecurityPerimetersResourceAssociationOperatorSpec struct {
	// ConfigMapExpressions: configures where to place operator written dynamic ConfigMaps (created with CEL expressions).
	ConfigMapExpressions []*core.DestinationExpression `json:"configMapExpressions,omitempty"`

	// SecretExpressions: configures where to place operator written dynamic secrets (created with CEL expressions).
	SecretExpressions []*core.DestinationExpression `json:"secretExpressions,omitempty"`
}

// AssignProperties_From_NetworkSecurityPerimetersResourceAssociationOperatorSpec populates our NetworkSecurityPerimetersResourceAssociationOperatorSpec from the provided source NetworkSecurityPerimetersResourceAssociationOperatorSpec
func (operator *NetworkSecurityPerimetersResourceAssociationOperatorSpec) AssignProperties_From_NetworkSecurityPerimetersResourceAssociationOperatorSpec(source *storage.NetworkSecurityPerimetersResourceAssociationOperatorSpec) error {

	// ConfigMapExpressions
	if source.ConfigMapExpressions != nil {
		configMapExpressionList := make([]*core.DestinationExpression, len(source.ConfigMapExpressions))
		for configMapExpressionIndex, configMapExpressionItem := range source.ConfigMapExpressions {
			if configMapExpressionItem != nil {
				configMapExpression := *configMapExpressionItem.DeepCopy()
				configMapExpressionList[configMapExpressionIndex] = &configMapExpression
			} else {
				configMapExpressionList[configMapExpressionIndex] = nil
			}
		}
		operator.ConfigMapExpressions = configMapExpressionList
	} else {
		operator.ConfigMapExpressions = nil
	}

	// SecretExpressions
	if source.SecretExpressions != nil {
		secretExpressionList := make([]*core.DestinationExpression, len(source.SecretExpressions))
		for secretExpressionIndex, secretExpressionItem := range source.SecretExpressions {
			if secretExpressionItem != nil {
				secretExpression := *secretExpressionItem.DeepCopy()
				secretExpressionList[secretExpressionIndex] = &secretExpression
			} else {
				secretExpressionList[secretExpressionIndex] = nil
			}
		}
		operator.SecretExpressions = secretExpressionList
	} else {
		operator.SecretExpressions = nil
	}

	// No error
	return nil
}

// AssignProperties_To_NetworkSecurityPerimetersResourceAssociationOperatorSpec populates the provided destination NetworkSecurityPerimetersResourceAssociationOperatorSpec from our NetworkSecurityPerimetersResourceAssociationOperatorSpec
func (operator *NetworkSecurityPerimetersResourceAssociationOperatorSpec) AssignProperties_To_NetworkSecurityPerimetersResourceAssociationOperatorSpec(destination *storage.NetworkSecurityPerimetersResourceAssociationOperatorSpec) error {
	// Create a new property bag
	propertyBag := genruntime.NewPropertyBag()

	// ConfigMapExpressions
	if operator.ConfigMapExpressions != nil {
		configMapExpressionList := make([]*core.DestinationExpression, len(operator.ConfigMapExpressions))
		for configMapExpressionIndex, configMapExpressionItem := range operator.ConfigMapExpressions {
			if configMapExpressionItem != nil {
				configMapExpression := *configMapExpressionItem.DeepCopy()
				configMapExpressionList[configMapExpressionIndex] = &configMapExpression
			} else {
				configMapExpressionList[configMapExpressionIndex] = nil
			}
		}
		destination.ConfigMapExpressions = configMapExpressionList
	} else {
		destination.ConfigMapExpressions = nil
	}

	// SecretExpressions
	if operator.SecretExpressions != nil {
		secretExpressionList := make([]*core.DestinationExpression, len(operator.SecretExpressions))
		for secretExpressionIndex, secretExpressionItem := range operator.SecretExpressions {
			if secretExpressionItem != nil {
				secretExpression := *secretExpressionItem.DeepCopy()
				secretExpressionList[secretExpressionIndex] = &secretExpression
			} else {
				secretExpressionList[secretExpressionIndex] = nil
			}
		}
		destination.SecretExpressions = secretExpressionList
	} else {
		destination.SecretExpressions = nil
	}

	// Update the property bag
	if len(propertyBag) > 0 {
		destination.PropertyBag = propertyBag
	} else {
		destination.PropertyBag = nil
	}

	// No error
	return nil
}

func init() {
	SchemeBuilder.Register(&NetworkSecurityPerimetersResourceAssociation{}, &NetworkSecurityPerimetersResourceAssociationList{})
}
