// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package storage

import (
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/conditions"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/configmaps"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/core"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/secrets"
	"github.com/rotisserie/eris"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// +kubebuilder:rbac:groups=network.azure.com,resources=networksecurityperimetersresourceassociations,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=network.azure.com,resources={networksecurityperimetersresourceassociations/status,networksecurityperimetersresourceassociations/finalizers},verbs=get;update;patch

// +kubebuilder:object:root=true
// +kubebuilder:resource:categories={azure,network}
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Severity",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].severity"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].message"
// Storage version of v20250501.NetworkSecurityPerimetersResourceAssociation
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-05-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/resourceAssociations/{associationName}
type NetworkSecurityPerimetersResourceAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkSecurityPerimetersResourceAssociation_Spec   `json:"spec,omitempty"`
	Status            NetworkSecurityPerimetersResourceAssociation_STATUS `json:"status,omitempty"`
}

var _ conditions.Conditioner = &NetworkSecurityPerimetersResourceAssociation{}

// GetConditions returns the conditions of the resource
func (association *NetworkSecurityPerimetersResourceAssociation) GetConditions() conditions.Conditions {
	return association.Status.Conditions
}

// SetConditions sets the conditions on the resource status
func (association *NetworkSecurityPerimetersResourceAssociation) SetConditions(conditions conditions.Conditions) {
	association.Status.Conditions = conditions
}

var _ configmaps.Exporter = &NetworkSecurityPerimetersResourceAssociation{}

// ConfigMapDestinationExpressions returns the Spec.OperatorSpec.ConfigMapExpressions property
func (association *NetworkSecurityPerimetersResourceAssociation) ConfigMapDestinationExpressions() []*core.DestinationExpression {
	if association.Spec.OperatorSpec == nil {
		return nil
	}
	return association.Spec.OperatorSpec.ConfigMapExpressions
}

var _ secrets.Exporter = &NetworkSecurityPerimetersResourceAssociation{}

// SecretDestinationExpressions returns the Spec.OperatorSpec.SecretExpressions property
func (association *NetworkSecurityPerimetersResourceAssociation) SecretDestinationExpressions() []*core.DestinationExpression {
	if association.Spec.OperatorSpec == nil {
		return nil
	}
	return association.Spec.OperatorSpec.SecretExpressions
}

var _ genruntime.KubernetesResource = &NetworkSecurityPerimetersResourceAssociation{}

// AzureName returns the Azure name of the resource
func (association *NetworkSecurityPerimetersResourceAssociation) AzureName() string {
	return association.Spec.AzureName
}

// GetAPIVersion returns the ARM API version of the resource. This is always "2025-05-01"
func (association NetworkSecurityPerimetersResourceAssociation) GetAPIVersion() string {
	return "2025-05-01"
}

// GetResourceScope returns the scope of the resource
func (association *NetworkSecurityPerimetersResourceAssociation) GetResourceScope() genruntime.ResourceScope {
	return genruntime.ResourceScopeResourceGroup
}

// GetSpec returns the specification of this resource
func (association *NetworkSecurityPerimetersResourceAssociation) GetSpec() genruntime.ConvertibleSpec {
	return &association.Spec
}

// GetStatus returns the status of this resource
func (association *NetworkSecurityPerimetersResourceAssociation) GetStatus() genruntime.ConvertibleStatus {
	return &association.Status
}

// GetSupportedOperations returns the operations supported by the resource
func (association *NetworkSecurityPerimetersResourceAssociation) GetSupportedOperations() []genruntime.ResourceOperation {
	return []genruntime.ResourceOperation{
		genruntime.ResourceOperationDelete,
		genruntime.ResourceOperationGet,
		genruntime.ResourceOperationPut,
	}
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Network/networkSecurityPerimeters/resourceAssociations"
func (association *NetworkSecurityPerimetersResourceAssociation) GetType() string {
	return "Microsoft.Network/networkSecurityPerimeters/resourceAssociations"
}

// NewEmptyStatus returns a new empty (blank) status
func (association *NetworkSecurityPerimetersResourceAssociation) NewEmptyStatus() genruntime.ConvertibleStatus {
	return &NetworkSecurityPerimetersResourceAssociation_STATUS{}
}

// Owner returns the ResourceReference of the owner
func (association *NetworkSecurityPerimetersResourceAssociation) Owner() *genruntime.ResourceReference {
	if association.Spec.Owner == nil {
		return nil
	}

	group, kind := genruntime.LookupOwnerGroupKind(association.Spec)
	return association.Spec.Owner.AsResourceReference(group, kind)
}

// SetStatus sets the status of this resource
func (association *NetworkSecurityPerimetersResourceAssociation) SetStatus(status genruntime.ConvertibleStatus) error {
	// If we have exactly the right type of status, assign it
	if st, ok := status.(*NetworkSecurityPerimetersResourceAssociation_STATUS); ok {
		association.Status = *st
		return nil
	}

	// Convert status to required version
	var st NetworkSecurityPerimetersResourceAssociation_STATUS
	err := status.ConvertStatusTo(&st)
	if err != nil {
		return eris.Wrap(err, "failed to convert status")
	}

	association.Status = st
	return nil
}

// Hub marks that this NetworkSecurityPerimetersResourceAssociation is the hub type for conversion
func (association *NetworkSecurityPerimetersResourceAssociation) Hub() {}

// OriginalGVK returns a GroupValueKind for the original API version used to create the resource
func (association *NetworkSecurityPerimetersResourceAssociation) OriginalGVK() *schema.GroupVersionKind {
	return &schema.GroupVersionKind{
		Group:   GroupVersion.Group,
		Version: association.Spec.OriginalVersion,
		Kind:    "NetworkSecurityPerimetersResourceAssociation",
	}
}

// +kubebuilder:object:root=true
// Storage version of v20250501.NetworkSecurityPerimetersResourceAssociation
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-05-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/resourceAssociations/{associationName}
type NetworkSecurityPerimetersResourceAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkSecurityPerimetersResourceAssociation `json:"items"`
}

// Storage version of v20250501.NetworkSecurityPerimetersResourceAssociation_Spec
type NetworkSecurityPerimetersResourceAssociation_Spec struct {
	// AzureName: The name of the resource in Azure. This is often the same as the name of the resource in Kubernetes but it
	// doesn't have to be.
	AzureName       string                                                    `json:"azureName,omitempty"`
	OperatorSpec    *NetworkSecurityPerimetersResourceAssociationOperatorSpec `json:"operatorSpec,omitempty"`
	OriginalVersion string                                                    `json:"originalVersion,omitempty"`

	// +kubebuilder:validation:Required
	// Owner: The owner of the resource. The owner controls where the resource goes when it is deployed. The owner also
	// controls the resources lifecycle. When the owner is deleted the resource will also be deleted. Owner is expected to be a
	// reference to a network.azure.com/NetworkSecurityPerimeter resource
	Owner       *genruntime.KnownResourceReference `group:"network.azure.com" json:"owner,omitempty" kind:"NetworkSecurityPerimeter"`
	PropertyBag genruntime.PropertyBag             `json:"$propertyBag,omitempty"`
}

var _ genruntime.ConvertibleSpec = &NetworkSecurityPerimetersResourceAssociation_Spec{}

// ConvertSpecFrom populates our NetworkSecurityPerimetersResourceAssociation_Spec from the provided source
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) ConvertSpecFrom(source genruntime.ConvertibleSpec) error {
	if source == association {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return source.ConvertSpecTo(association)
}

// ConvertSpecTo populates the provided destination from our NetworkSecurityPerimetersResourceAssociation_Spec
func (association *NetworkSecurityPerimetersResourceAssociation_Spec) ConvertSpecTo(destination genruntime.ConvertibleSpec) error {
	if destination == association {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return destination.ConvertSpecFrom(association)
}

// Storage version of v20250501.NetworkSecurityPerimetersResourceAssociation_STATUS
type NetworkSecurityPerimetersResourceAssociation_STATUS struct {
	AccessMode            *string                                     `json:"accessMode,omitempty"`
	Conditions            []conditions.Condition                      `json:"conditions,omitempty"`
	HasProvisioningIssues *string                                     `json:"hasProvisioningIssues,omitempty"`
	Id                    *string                                     `json:"id,omitempty"`
	Name                  *string                                     `json:"name,omitempty"`
	PrivateLinkResource   *NetworkSecurityPerimeterSubResource_STATUS `json:"privateLinkResource,omitempty"`
	Profile               *NetworkSecurityPerimeterSubResource_STATUS `json:"profile,omitempty"`
	PropertyBag           genruntime.PropertyBag                      `json:"$propertyBag,omitempty"`
	ProvisioningState     *string                                     `json:"provisioningState,omitempty"`
	SystemData            *CommonSystemData_STATUS                    `json:"systemData,omitempty"`
	Type                  *string                                     `json:"type,omitempty"`
}

var _ genruntime.ConvertibleStatus = &NetworkSecurityPerimetersResourceAssociation_STATUS{}

// ConvertStatusFrom populates our NetworkSecurityPerimetersResourceAssociation_STATUS from the provided source
func (association *NetworkSecurityPerimetersResourceAssociation_STATUS) ConvertStatusFrom(source genruntime.ConvertibleStatus) error {
	if source == association {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return source.ConvertStatusTo(association)
}

// ConvertStatusTo populates the provided destination from our NetworkSecurityPerimetersResourceAssociation_STATUS
func (association *NetworkSecurityPerimetersResourceAssociation_STATUS) ConvertStatusTo(destination genruntime.ConvertibleStatus) error {
	if destination == association {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return destination.ConvertStatusFrom(association)
}

// Storage version of v20250501.NetworkSecurityPerimetersResourceAssociationOperatorSpec
// Details for configuring operator behavior. Fields in this struct are interpreted by the operator directly rather than being passed to Azure
type NetworkSecurityPerimetersResourceAssociationOperatorSpec struct {
	ConfigMapExpressions []*core.DestinationExpression `json:"configMapExpressions,omitempty"`
	PropertyBag          genruntime.PropertyBag        `json:"$propertyBag,omitempty"`
	SecretExpressions    []*core.DestinationExpression `json:"secretExpressions,omitempty"`
}

// Storage version of v20250501.NetworkSecurityPerimeterSubResource_STATUS
// Reference to another subresource.
type NetworkSecurityPerimeterSubResource_STATUS struct {
	Id          *string                `json:"id,omitempty"`
	PropertyBag genruntime.PropertyBag `json:"$propertyBag,omitempty"`
}

func init() {
	SchemeBuilder.Register(&NetworkSecurityPerimetersResourceAssociation{}, &NetworkSecurityPerimetersResourceAssociationList{})
}
