// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package storage

import (
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/conditions"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/configmaps"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/core"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/secrets"
	"github.com/rotisserie/eris"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// +kubebuilder:rbac:groups=network.azure.com,resources=networksecurityperimeterslinks,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=network.azure.com,resources={networksecurityperimeterslinks/status,networksecurityperimeterslinks/finalizers},verbs=get;update;patch

// +kubebuilder:object:root=true
// +kubebuilder:resource:categories={azure,network}
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Severity",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].severity"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].message"
// Storage version of v20250501.NetworkSecurityPerimetersLink
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-05-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/links/{linkName}
type NetworkSecurityPerimetersLink struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkSecurityPerimetersLink_Spec   `json:"spec,omitempty"`
	Status            NetworkSecurityPerimetersLink_STATUS `json:"status,omitempty"`
}

var _ conditions.Conditioner = &NetworkSecurityPerimetersLink{}

// GetConditions returns the conditions of the resource
func (link *NetworkSecurityPerimetersLink) GetConditions() conditions.Conditions {
	return link.Status.Conditions
}

// SetConditions sets the conditions on the resource status
func (link *NetworkSecurityPerimetersLink) SetConditions(conditions conditions.Conditions) {
	link.Status.Conditions = conditions
}

var _ configmaps.Exporter = &NetworkSecurityPerimetersLink{}

// ConfigMapDestinationExpressions returns the Spec.OperatorSpec.ConfigMapExpressions property
func (link *NetworkSecurityPerimetersLink) ConfigMapDestinationExpressions() []*core.DestinationExpression {
	if link.Spec.OperatorSpec == nil {
		return nil
	}
	return link.Spec.OperatorSpec.ConfigMapExpressions
}

var _ secrets.Exporter = &NetworkSecurityPerimetersLink{}

// SecretDestinationExpressions returns the Spec.OperatorSpec.SecretExpressions property
func (link *NetworkSecurityPerimetersLink) SecretDestinationExpressions() []*core.DestinationExpression {
	if link.Spec.OperatorSpec == nil {
		return nil
	}
	return link.Spec.OperatorSpec.SecretExpressions
}

var _ genruntime.KubernetesResource = &NetworkSecurityPerimetersLink{}

// AzureName returns the Azure name of the resource
func (link *NetworkSecurityPerimetersLink) AzureName() string {
	return link.Spec.AzureName
}

// GetAPIVersion returns the ARM API version of the resource. This is always "2025-05-01"
func (link NetworkSecurityPerimetersLink) GetAPIVersion() string {
	return "2025-05-01"
}

// GetResourceScope returns the scope of the resource
func (link *NetworkSecurityPerimetersLink) GetResourceScope() genruntime.ResourceScope {
	return genruntime.ResourceScopeResourceGroup
}

// GetSpec returns the specification of this resource
func (link *NetworkSecurityPerimetersLink) GetSpec() genruntime.ConvertibleSpec {
	return &link.Spec
}

// GetStatus returns the status of this resource
func (link *NetworkSecurityPerimetersLink) GetStatus() genruntime.ConvertibleStatus {
	return &link.Status
}

// GetSupportedOperations returns the operations supported by the resource
func (link *NetworkSecurityPerimetersLink) GetSupportedOperations() []genruntime.ResourceOperation {
	return []genruntime.ResourceOperation{
		genruntime.ResourceOperationDelete,
		genruntime.ResourceOperationGet,
		genruntime.ResourceOperationPut,
	}
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Network/networkSecurityPerimeters/links"
func (link *NetworkSecurityPerimetersLink) GetType() string {
	return "Microsoft.Network/networkSecurityPerimeters/links"
}

// NewEmptyStatus returns a new empty (blank) status
func (link *NetworkSecurityPerimetersLink) NewEmptyStatus() genruntime.ConvertibleStatus {
	return &NetworkSecurityPerimetersLink_STATUS{}
}

// Owner returns the ResourceReference of the owner
func (link *NetworkSecurityPerimetersLink) Owner() *genruntime.ResourceReference {
	if link.Spec.Owner == nil {
		return nil
	}

	group, kind := genruntime.LookupOwnerGroupKind(link.Spec)
	return link.Spec.Owner.AsResourceReference(group, kind)
}

// SetStatus sets the status of this resource
func (link *NetworkSecurityPerimetersLink) SetStatus(status genruntime.ConvertibleStatus) error {
	// If we have exactly the right type of status, assign it
	if st, ok := status.(*NetworkSecurityPerimetersLink_STATUS); ok {
		link.Status = *st
		return nil
	}

	// Convert status to required version
	var st NetworkSecurityPerimetersLink_STATUS
	err := status.ConvertStatusTo(&st)
	if err != nil {
		return eris.Wrap(err, "failed to convert status")
	}

	link.Status = st
	return nil
}

// Hub marks that this NetworkSecurityPerimetersLink is the hub type for conversion
func (link *NetworkSecurityPerimetersLink) Hub() {}

// OriginalGVK returns a GroupValueKind for the original API version used to create the resource
func (link *NetworkSecurityPerimetersLink) OriginalGVK() *schema.GroupVersionKind {
	return &schema.GroupVersionKind{
		Group:   GroupVersion.Group,
		Version: link.Spec.OriginalVersion,
		Kind:    "NetworkSecurityPerimetersLink",
	}
}

// +kubebuilder:object:root=true
// Storage version of v20250501.NetworkSecurityPerimetersLink
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-05-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/links/{linkName}
type NetworkSecurityPerimetersLinkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkSecurityPerimetersLink `json:"items"`
}

// Storage version of v20250501.NetworkSecurityPerimetersLink_Spec
type NetworkSecurityPerimetersLink_Spec struct {
	// AzureName: The name of the resource in Azure. This is often the same as the name of the resource in Kubernetes but it
	// doesn't have to be.
	AzureName       string                                     `json:"azureName,omitempty"`
	OperatorSpec    *NetworkSecurityPerimetersLinkOperatorSpec `json:"operatorSpec,omitempty"`
	OriginalVersion string                                     `json:"originalVersion,omitempty"`

	// +kubebuilder:validation:Required
	// Owner: The owner of the resource. The owner controls where the resource goes when it is deployed. The owner also
	// controls the resources lifecycle. When the owner is deleted the resource will also be deleted. Owner is expected to be a
	// reference to a network.azure.com/NetworkSecurityPerimeter resource
	Owner       *genruntime.KnownResourceReference `group:"network.azure.com" json:"owner,omitempty" kind:"NetworkSecurityPerimeter"`
	PropertyBag genruntime.PropertyBag             `json:"$propertyBag,omitempty"`
}

var _ genruntime.ConvertibleSpec = &NetworkSecurityPerimetersLink_Spec{}

// ConvertSpecFrom populates our NetworkSecurityPerimetersLink_Spec from the provided source
func (link *NetworkSecurityPerimetersLink_Spec) ConvertSpecFrom(source genruntime.ConvertibleSpec) error {
	if source == link {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return source.ConvertSpecTo(link)
}

// ConvertSpecTo populates the provided destination from our NetworkSecurityPerimetersLink_Spec
func (link *NetworkSecurityPerimetersLink_Spec) ConvertSpecTo(destination genruntime.ConvertibleSpec) error {
	if destination == link {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return destination.ConvertSpecFrom(link)
}

// Storage version of v20250501.NetworkSecurityPerimetersLink_STATUS
type NetworkSecurityPerimetersLink_STATUS struct {
	AutoApprovedRemotePerimeterResourceId *string                  `json:"autoApprovedRemotePerimeterResourceId,omitempty"`
	Conditions                            []conditions.Condition   `json:"conditions,omitempty"`
	Description                           *string                  `json:"description,omitempty"`
	Id                                    *string                  `json:"id,omitempty"`
	LocalInboundProfiles                  []string                 `json:"localInboundProfiles,omitempty"`
	LocalOutboundProfiles                 []string                 `json:"localOutboundProfiles,omitempty"`
	Name                                  *string                  `json:"name,omitempty"`
	PropertyBag                           genruntime.PropertyBag   `json:"$propertyBag,omitempty"`
	ProvisioningState                     *string                  `json:"provisioningState,omitempty"`
	RemoteInboundProfiles                 []string                 `json:"remoteInboundProfiles,omitempty"`
	RemoteOutboundProfiles                []string                 `json:"remoteOutboundProfiles,omitempty"`
	RemotePerimeterGuid                   *string                  `json:"remotePerimeterGuid,omitempty"`
	RemotePerimeterLocation               *string                  `json:"remotePerimeterLocation,omitempty"`
	Status                                *string                  `json:"status,omitempty"`
	SystemData                            *CommonSystemData_STATUS `json:"systemData,omitempty"`
	Type                                  *string                  `json:"type,omitempty"`
}

var _ genruntime.ConvertibleStatus = &NetworkSecurityPerimetersLink_STATUS{}

// ConvertStatusFrom populates our NetworkSecurityPerimetersLink_STATUS from the provided source
func (link *NetworkSecurityPerimetersLink_STATUS) ConvertStatusFrom(source genruntime.ConvertibleStatus) error {
	if source == link {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return source.ConvertStatusTo(link)
}

// ConvertStatusTo populates the provided destination from our NetworkSecurityPerimetersLink_STATUS
func (link *NetworkSecurityPerimetersLink_STATUS) ConvertStatusTo(destination genruntime.ConvertibleStatus) error {
	if destination == link {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return destination.ConvertStatusFrom(link)
}

// Storage version of v20250501.NetworkSecurityPerimetersLinkOperatorSpec
// Details for configuring operator behavior. Fields in this struct are interpreted by the operator directly rather than being passed to Azure
type NetworkSecurityPerimetersLinkOperatorSpec struct {
	ConfigMapExpressions []*core.DestinationExpression `json:"configMapExpressions,omitempty"`
	PropertyBag          genruntime.PropertyBag        `json:"$propertyBag,omitempty"`
	SecretExpressions    []*core.DestinationExpression `json:"secretExpressions,omitempty"`
}

func init() {
	SchemeBuilder.Register(&NetworkSecurityPerimetersLink{}, &NetworkSecurityPerimetersLinkList{})
}
