// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package storage

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_NetworkSecurityPerimetersLink_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 20
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersLink via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersLink, NetworkSecurityPerimetersLinkGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersLink runs a test to see if a specific instance of NetworkSecurityPerimetersLink round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersLink(subject NetworkSecurityPerimetersLink) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersLink
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersLink instances for property testing - lazily instantiated by
// NetworkSecurityPerimetersLinkGenerator()
var networkSecurityPerimetersLinkGenerator gopter.Gen

// NetworkSecurityPerimetersLinkGenerator returns a generator of NetworkSecurityPerimetersLink instances for property testing.
func NetworkSecurityPerimetersLinkGenerator() gopter.Gen {
	if networkSecurityPerimetersLinkGenerator != nil {
		return networkSecurityPerimetersLinkGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink(generators)
	networkSecurityPerimetersLinkGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLink{}), generators)

	return networkSecurityPerimetersLinkGenerator
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink(gens map[string]gopter.Gen) {
	gens["Spec"] = NetworkSecurityPerimetersLink_SpecGenerator()
	gens["Status"] = NetworkSecurityPerimetersLink_STATUSGenerator()
}

func Test_NetworkSecurityPerimetersLinkOperatorSpec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersLinkOperatorSpec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersLinkOperatorSpec, NetworkSecurityPerimetersLinkOperatorSpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersLinkOperatorSpec runs a test to see if a specific instance of NetworkSecurityPerimetersLinkOperatorSpec round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersLinkOperatorSpec(subject NetworkSecurityPerimetersLinkOperatorSpec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersLinkOperatorSpec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersLinkOperatorSpec instances for property testing - lazily instantiated by
// NetworkSecurityPerimetersLinkOperatorSpecGenerator()
var networkSecurityPerimetersLinkOperatorSpecGenerator gopter.Gen

// NetworkSecurityPerimetersLinkOperatorSpecGenerator returns a generator of NetworkSecurityPerimetersLinkOperatorSpec instances for property testing.
func NetworkSecurityPerimetersLinkOperatorSpecGenerator() gopter.Gen {
	if networkSecurityPerimetersLinkOperatorSpecGenerator != nil {
		return networkSecurityPerimetersLinkOperatorSpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	networkSecurityPerimetersLinkOperatorSpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLinkOperatorSpec{}), generators)

	return networkSecurityPerimetersLinkOperatorSpecGenerator
}

func Test_NetworkSecurityPerimetersLink_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersLink_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersLink_STATUS, NetworkSecurityPerimetersLink_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersLink_STATUS runs a test to see if a specific instance of NetworkSecurityPerimetersLink_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersLink_STATUS(subject NetworkSecurityPerimetersLink_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersLink_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersLink_STATUS instances for property testing - lazily instantiated by
// NetworkSecurityPerimetersLink_STATUSGenerator()
var networkSecurityPerimetersLink_STATUSGenerator gopter.Gen

// NetworkSecurityPerimetersLink_STATUSGenerator returns a generator of NetworkSecurityPerimetersLink_STATUS instances for property testing.
// We first initialize networkSecurityPerimetersLink_STATUSGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimetersLink_STATUSGenerator() gopter.Gen {
	if networkSecurityPerimetersLink_STATUSGenerator != nil {
		return networkSecurityPerimetersLink_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS(generators)
	networkSecurityPerimetersLink_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLink_STATUS{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS(generators)
	networkSecurityPerimetersLink_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLink_STATUS{}), generators)

	return networkSecurityPerimetersLink_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS(gens map[string]gopter.Gen) {
	gens["AutoApprovedRemotePerimeterResourceId"] = gen.PtrOf(gen.AlphaString())
	gens["Description"] = gen.PtrOf(gen.AlphaString())
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["LocalInboundProfiles"] = gen.SliceOf(gen.AlphaString())
	gens["LocalOutboundProfiles"] = gen.SliceOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["ProvisioningState"] = gen.PtrOf(gen.AlphaString())
	gens["RemoteInboundProfiles"] = gen.SliceOf(gen.AlphaString())
	gens["RemoteOutboundProfiles"] = gen.SliceOf(gen.AlphaString())
	gens["RemotePerimeterGuid"] = gen.PtrOf(gen.AlphaString())
	gens["RemotePerimeterLocation"] = gen.PtrOf(gen.AlphaString())
	gens["Status"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink_STATUS(gens map[string]gopter.Gen) {
	gens["SystemData"] = gen.PtrOf(CommonSystemData_STATUSGenerator())
}

func Test_NetworkSecurityPerimetersLink_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersLink_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersLink_Spec, NetworkSecurityPerimetersLink_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersLink_Spec runs a test to see if a specific instance of NetworkSecurityPerimetersLink_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersLink_Spec(subject NetworkSecurityPerimetersLink_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersLink_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersLink_Spec instances for property testing - lazily instantiated by
// NetworkSecurityPerimetersLink_SpecGenerator()
var networkSecurityPerimetersLink_SpecGenerator gopter.Gen

// NetworkSecurityPerimetersLink_SpecGenerator returns a generator of NetworkSecurityPerimetersLink_Spec instances for property testing.
// We first initialize networkSecurityPerimetersLink_SpecGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimetersLink_SpecGenerator() gopter.Gen {
	if networkSecurityPerimetersLink_SpecGenerator != nil {
		return networkSecurityPerimetersLink_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec(generators)
	networkSecurityPerimetersLink_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLink_Spec{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec(generators)
	networkSecurityPerimetersLink_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLink_Spec{}), generators)

	return networkSecurityPerimetersLink_SpecGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec(gens map[string]gopter.Gen) {
	gens["AzureName"] = gen.AlphaString()
	gens["OriginalVersion"] = gen.AlphaString()
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec(gens map[string]gopter.Gen) {
	gens["OperatorSpec"] = gen.PtrOf(NetworkSecurityPerimetersLinkOperatorSpecGenerator())
}
