// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package storage

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_NetworkSecurityPerimetersProfile_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 20
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersProfile via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersProfile, NetworkSecurityPerimetersProfileGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersProfile runs a test to see if a specific instance of NetworkSecurityPerimetersProfile round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersProfile(subject NetworkSecurityPerimetersProfile) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersProfile
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersProfile instances for property testing - lazily instantiated by
// NetworkSecurityPerimetersProfileGenerator()
var networkSecurityPerimetersProfileGenerator gopter.Gen

// NetworkSecurityPerimetersProfileGenerator returns a generator of NetworkSecurityPerimetersProfile instances for property testing.
func NetworkSecurityPerimetersProfileGenerator() gopter.Gen {
	if networkSecurityPerimetersProfileGenerator != nil {
		return networkSecurityPerimetersProfileGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfile(generators)
	networkSecurityPerimetersProfileGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersProfile{}), generators)

	return networkSecurityPerimetersProfileGenerator
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfile is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfile(gens map[string]gopter.Gen) {
	gens["Spec"] = NetworkSecurityPerimetersProfile_SpecGenerator()
	gens["Status"] = NetworkSecurityPerimetersProfile_STATUSGenerator()
}

func Test_NetworkSecurityPerimetersProfileOperatorSpec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersProfileOperatorSpec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersProfileOperatorSpec, NetworkSecurityPerimetersProfileOperatorSpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersProfileOperatorSpec runs a test to see if a specific instance of NetworkSecurityPerimetersProfileOperatorSpec round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersProfileOperatorSpec(subject NetworkSecurityPerimetersProfileOperatorSpec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersProfileOperatorSpec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersProfileOperatorSpec instances for property testing - lazily instantiated by
// NetworkSecurityPerimetersProfileOperatorSpecGenerator()
var networkSecurityPerimetersProfileOperatorSpecGenerator gopter.Gen

// NetworkSecurityPerimetersProfileOperatorSpecGenerator returns a generator of NetworkSecurityPerimetersProfileOperatorSpec instances for property testing.
func NetworkSecurityPerimetersProfileOperatorSpecGenerator() gopter.Gen {
	if networkSecurityPerimetersProfileOperatorSpecGenerator != nil {
		return networkSecurityPerimetersProfileOperatorSpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	networkSecurityPerimetersProfileOperatorSpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersProfileOperatorSpec{}), generators)

	return networkSecurityPerimetersProfileOperatorSpecGenerator
}

func Test_NetworkSecurityPerimetersProfile_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersProfile_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersProfile_STATUS, NetworkSecurityPerimetersProfile_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersProfile_STATUS runs a test to see if a specific instance of NetworkSecurityPerimetersProfile_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersProfile_STATUS(subject NetworkSecurityPerimetersProfile_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersProfile_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersProfile_STATUS instances for property testing - lazily instantiated by
// NetworkSecurityPerimetersProfile_STATUSGenerator()
var networkSecurityPerimetersProfile_STATUSGenerator gopter.Gen

// NetworkSecurityPerimetersProfile_STATUSGenerator returns a generator of NetworkSecurityPerimetersProfile_STATUS instances for property testing.
// We first initialize networkSecurityPerimetersProfile_STATUSGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimetersProfile_STATUSGenerator() gopter.Gen {
	if networkSecurityPerimetersProfile_STATUSGenerator != nil {
		return networkSecurityPerimetersProfile_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS(generators)
	networkSecurityPerimetersProfile_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersProfile_STATUS{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS(generators)
	networkSecurityPerimetersProfile_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersProfile_STATUS{}), generators)

	return networkSecurityPerimetersProfile_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS(gens map[string]gopter.Gen) {
	gens["AccessRulesVersion"] = gen.PtrOf(gen.AlphaString())
	gens["DiagnosticSettingsVersion"] = gen.PtrOf(gen.AlphaString())
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfile_STATUS(gens map[string]gopter.Gen) {
	gens["SystemData"] = gen.PtrOf(CommonSystemData_STATUSGenerator())
}

func Test_NetworkSecurityPerimetersProfile_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersProfile_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersProfile_Spec, NetworkSecurityPerimetersProfile_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersProfile_Spec runs a test to see if a specific instance of NetworkSecurityPerimetersProfile_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersProfile_Spec(subject NetworkSecurityPerimetersProfile_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersProfile_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersProfile_Spec instances for property testing - lazily instantiated by
// NetworkSecurityPerimetersProfile_SpecGenerator()
var networkSecurityPerimetersProfile_SpecGenerator gopter.Gen

// NetworkSecurityPerimetersProfile_SpecGenerator returns a generator of NetworkSecurityPerimetersProfile_Spec instances for property testing.
// We first initialize networkSecurityPerimetersProfile_SpecGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimetersProfile_SpecGenerator() gopter.Gen {
	if networkSecurityPerimetersProfile_SpecGenerator != nil {
		return networkSecurityPerimetersProfile_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfile_Spec(generators)
	networkSecurityPerimetersProfile_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersProfile_Spec{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfile_Spec(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfile_Spec(generators)
	networkSecurityPerimetersProfile_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersProfile_Spec{}), generators)

	return networkSecurityPerimetersProfile_SpecGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfile_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfile_Spec(gens map[string]gopter.Gen) {
	gens["AzureName"] = gen.AlphaString()
	gens["OriginalVersion"] = gen.AlphaString()
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfile_Spec is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfile_Spec(gens map[string]gopter.Gen) {
	gens["OperatorSpec"] = gen.PtrOf(NetworkSecurityPerimetersProfileOperatorSpecGenerator())
}
