// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package storage

import (
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/conditions"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/configmaps"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/core"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/secrets"
	"github.com/rotisserie/eris"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// +kubebuilder:rbac:groups=network.azure.com,resources=networksecurityperimeters,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=network.azure.com,resources={networksecurityperimeters/status,networksecurityperimeters/finalizers},verbs=get;update;patch

// +kubebuilder:object:root=true
// +kubebuilder:resource:categories={azure,network}
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Severity",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].severity"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].message"
// Storage version of v20250501.NetworkSecurityPerimeter
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-05-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}
type NetworkSecurityPerimeter struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkSecurityPerimeter_Spec   `json:"spec,omitempty"`
	Status            NetworkSecurityPerimeter_STATUS `json:"status,omitempty"`
}

var _ conditions.Conditioner = &NetworkSecurityPerimeter{}

// GetConditions returns the conditions of the resource
func (perimeter *NetworkSecurityPerimeter) GetConditions() conditions.Conditions {
	return perimeter.Status.Conditions
}

// SetConditions sets the conditions on the resource status
func (perimeter *NetworkSecurityPerimeter) SetConditions(conditions conditions.Conditions) {
	perimeter.Status.Conditions = conditions
}

var _ configmaps.Exporter = &NetworkSecurityPerimeter{}

// ConfigMapDestinationExpressions returns the Spec.OperatorSpec.ConfigMapExpressions property
func (perimeter *NetworkSecurityPerimeter) ConfigMapDestinationExpressions() []*core.DestinationExpression {
	if perimeter.Spec.OperatorSpec == nil {
		return nil
	}
	return perimeter.Spec.OperatorSpec.ConfigMapExpressions
}

var _ secrets.Exporter = &NetworkSecurityPerimeter{}

// SecretDestinationExpressions returns the Spec.OperatorSpec.SecretExpressions property
func (perimeter *NetworkSecurityPerimeter) SecretDestinationExpressions() []*core.DestinationExpression {
	if perimeter.Spec.OperatorSpec == nil {
		return nil
	}
	return perimeter.Spec.OperatorSpec.SecretExpressions
}

var _ genruntime.KubernetesResource = &NetworkSecurityPerimeter{}

// AzureName returns the Azure name of the resource
func (perimeter *NetworkSecurityPerimeter) AzureName() string {
	return perimeter.Spec.AzureName
}

// GetAPIVersion returns the ARM API version of the resource. This is always "2025-05-01"
func (perimeter NetworkSecurityPerimeter) GetAPIVersion() string {
	return "2025-05-01"
}

// GetResourceScope returns the scope of the resource
func (perimeter *NetworkSecurityPerimeter) GetResourceScope() genruntime.ResourceScope {
	return genruntime.ResourceScopeResourceGroup
}

// GetSpec returns the specification of this resource
func (perimeter *NetworkSecurityPerimeter) GetSpec() genruntime.ConvertibleSpec {
	return &perimeter.Spec
}

// GetStatus returns the status of this resource
func (perimeter *NetworkSecurityPerimeter) GetStatus() genruntime.ConvertibleStatus {
	return &perimeter.Status
}

// GetSupportedOperations returns the operations supported by the resource
func (perimeter *NetworkSecurityPerimeter) GetSupportedOperations() []genruntime.ResourceOperation {
	return []genruntime.ResourceOperation{
		genruntime.ResourceOperationDelete,
		genruntime.ResourceOperationGet,
		genruntime.ResourceOperationPut,
	}
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Network/networkSecurityPerimeters"
func (perimeter *NetworkSecurityPerimeter) GetType() string {
	return "Microsoft.Network/networkSecurityPerimeters"
}

// NewEmptyStatus returns a new empty (blank) status
func (perimeter *NetworkSecurityPerimeter) NewEmptyStatus() genruntime.ConvertibleStatus {
	return &NetworkSecurityPerimeter_STATUS{}
}

// Owner returns the ResourceReference of the owner
func (perimeter *NetworkSecurityPerimeter) Owner() *genruntime.ResourceReference {
	if perimeter.Spec.Owner == nil {
		return nil
	}

	group, kind := genruntime.LookupOwnerGroupKind(perimeter.Spec)
	return perimeter.Spec.Owner.AsResourceReference(group, kind)
}

// SetStatus sets the status of this resource
func (perimeter *NetworkSecurityPerimeter) SetStatus(status genruntime.ConvertibleStatus) error {
	// If we have exactly the right type of status, assign it
	if st, ok := status.(*NetworkSecurityPerimeter_STATUS); ok {
		perimeter.Status = *st
		return nil
	}

	// Convert status to required version
	var st NetworkSecurityPerimeter_STATUS
	err := status.ConvertStatusTo(&st)
	if err != nil {
		return eris.Wrap(err, "failed to convert status")
	}

	perimeter.Status = st
	return nil
}

// Hub marks that this NetworkSecurityPerimeter is the hub type for conversion
func (perimeter *NetworkSecurityPerimeter) Hub() {}

// OriginalGVK returns a GroupValueKind for the original API version used to create the resource
func (perimeter *NetworkSecurityPerimeter) OriginalGVK() *schema.GroupVersionKind {
	return &schema.GroupVersionKind{
		Group:   GroupVersion.Group,
		Version: perimeter.Spec.OriginalVersion,
		Kind:    "NetworkSecurityPerimeter",
	}
}

// +kubebuilder:object:root=true
// Storage version of v20250501.NetworkSecurityPerimeter
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-05-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}
type NetworkSecurityPerimeterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkSecurityPerimeter `json:"items"`
}

// Storage version of v20250501.APIVersion
// +kubebuilder:validation:Enum={"2025-05-01"}
type APIVersion string

const APIVersion_Value = APIVersion("2025-05-01")

// Storage version of v20250501.NetworkSecurityPerimeter_Spec
type NetworkSecurityPerimeter_Spec struct {
	// AzureName: The name of the resource in Azure. This is often the same as the name of the resource in Kubernetes but it
	// doesn't have to be.
	AzureName       string                                `json:"azureName,omitempty"`
	OperatorSpec    *NetworkSecurityPerimeterOperatorSpec `json:"operatorSpec,omitempty"`
	OriginalVersion string                                `json:"originalVersion,omitempty"`

	// +kubebuilder:validation:Required
	// Owner: The owner of the resource. The owner controls where the resource goes when it is deployed. The owner also
	// controls the resources lifecycle. When the owner is deleted the resource will also be deleted. Owner is expected to be a
	// reference to a resources.azure.com/ResourceGroup resource
	Owner       *genruntime.KnownResourceReference `group:"resources.azure.com" json:"owner,omitempty" kind:"ResourceGroup"`
	PropertyBag genruntime.PropertyBag             `json:"$propertyBag,omitempty"`
}

var _ genruntime.ConvertibleSpec = &NetworkSecurityPerimeter_Spec{}

// ConvertSpecFrom populates our NetworkSecurityPerimeter_Spec from the provided source
func (perimeter *NetworkSecurityPerimeter_Spec) ConvertSpecFrom(source genruntime.ConvertibleSpec) error {
	if source == perimeter {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return source.ConvertSpecTo(perimeter)
}

// ConvertSpecTo populates the provided destination from our NetworkSecurityPerimeter_Spec
func (perimeter *NetworkSecurityPerimeter_Spec) ConvertSpecTo(destination genruntime.ConvertibleSpec) error {
	if destination == perimeter {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return destination.ConvertSpecFrom(perimeter)
}

// Storage version of v20250501.NetworkSecurityPerimeter_STATUS
// The Network Security Perimeter resource
type NetworkSecurityPerimeter_STATUS struct {
	Conditions        []conditions.Condition   `json:"conditions,omitempty"`
	Id                *string                  `json:"id,omitempty"`
	Location          *string                  `json:"location,omitempty"`
	Name              *string                  `json:"name,omitempty"`
	PerimeterGuid     *string                  `json:"perimeterGuid,omitempty"`
	PropertyBag       genruntime.PropertyBag   `json:"$propertyBag,omitempty"`
	ProvisioningState *string                  `json:"provisioningState,omitempty"`
	SystemData        *CommonSystemData_STATUS `json:"systemData,omitempty"`
	Tags              map[string]string        `json:"tags,omitempty"`
	Type              *string                  `json:"type,omitempty"`
}

var _ genruntime.ConvertibleStatus = &NetworkSecurityPerimeter_STATUS{}

// ConvertStatusFrom populates our NetworkSecurityPerimeter_STATUS from the provided source
func (perimeter *NetworkSecurityPerimeter_STATUS) ConvertStatusFrom(source genruntime.ConvertibleStatus) error {
	if source == perimeter {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return source.ConvertStatusTo(perimeter)
}

// ConvertStatusTo populates the provided destination from our NetworkSecurityPerimeter_STATUS
func (perimeter *NetworkSecurityPerimeter_STATUS) ConvertStatusTo(destination genruntime.ConvertibleStatus) error {
	if destination == perimeter {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return destination.ConvertStatusFrom(perimeter)
}

// Storage version of v20250501.CommonSystemData_STATUS
// Metadata pertaining to creation and last modification of the resource.
type CommonSystemData_STATUS struct {
	CreatedAt          *string                `json:"createdAt,omitempty"`
	CreatedBy          *string                `json:"createdBy,omitempty"`
	CreatedByType      *string                `json:"createdByType,omitempty"`
	LastModifiedAt     *string                `json:"lastModifiedAt,omitempty"`
	LastModifiedBy     *string                `json:"lastModifiedBy,omitempty"`
	LastModifiedByType *string                `json:"lastModifiedByType,omitempty"`
	PropertyBag        genruntime.PropertyBag `json:"$propertyBag,omitempty"`
}

// Storage version of v20250501.NetworkSecurityPerimeterOperatorSpec
// Details for configuring operator behavior. Fields in this struct are interpreted by the operator directly rather than being passed to Azure
type NetworkSecurityPerimeterOperatorSpec struct {
	ConfigMapExpressions []*core.DestinationExpression `json:"configMapExpressions,omitempty"`
	PropertyBag          genruntime.PropertyBag        `json:"$propertyBag,omitempty"`
	SecretExpressions    []*core.DestinationExpression `json:"secretExpressions,omitempty"`
}

func init() {
	SchemeBuilder.Register(&NetworkSecurityPerimeter{}, &NetworkSecurityPerimeterList{})
}
