// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package storage

import (
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/conditions"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/configmaps"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/core"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/secrets"
	"github.com/rotisserie/eris"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// +kubebuilder:rbac:groups=network.azure.com,resources=networksecurityperimetersloggingconfigurations,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=network.azure.com,resources={networksecurityperimetersloggingconfigurations/status,networksecurityperimetersloggingconfigurations/finalizers},verbs=get;update;patch

// +kubebuilder:object:root=true
// +kubebuilder:resource:categories={azure,network}
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Severity",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].severity"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].message"
// Storage version of v20250701.NetworkSecurityPerimetersLoggingConfiguration
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-07-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/loggingConfigurations/{loggingConfigurationName}
type NetworkSecurityPerimetersLoggingConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkSecurityPerimetersLoggingConfiguration_Spec   `json:"spec,omitempty"`
	Status            NetworkSecurityPerimetersLoggingConfiguration_STATUS `json:"status,omitempty"`
}

var _ conditions.Conditioner = &NetworkSecurityPerimetersLoggingConfiguration{}

// GetConditions returns the conditions of the resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) GetConditions() conditions.Conditions {
	return configuration.Status.Conditions
}

// SetConditions sets the conditions on the resource status
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) SetConditions(conditions conditions.Conditions) {
	configuration.Status.Conditions = conditions
}

var _ configmaps.Exporter = &NetworkSecurityPerimetersLoggingConfiguration{}

// ConfigMapDestinationExpressions returns the Spec.OperatorSpec.ConfigMapExpressions property
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) ConfigMapDestinationExpressions() []*core.DestinationExpression {
	if configuration.Spec.OperatorSpec == nil {
		return nil
	}
	return configuration.Spec.OperatorSpec.ConfigMapExpressions
}

var _ secrets.Exporter = &NetworkSecurityPerimetersLoggingConfiguration{}

// SecretDestinationExpressions returns the Spec.OperatorSpec.SecretExpressions property
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) SecretDestinationExpressions() []*core.DestinationExpression {
	if configuration.Spec.OperatorSpec == nil {
		return nil
	}
	return configuration.Spec.OperatorSpec.SecretExpressions
}

var _ genruntime.KubernetesResource = &NetworkSecurityPerimetersLoggingConfiguration{}

// AzureName returns the Azure name of the resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) AzureName() string {
	return configuration.Spec.AzureName
}

// GetAPIVersion returns the ARM API version of the resource. This is always "2025-07-01"
func (configuration NetworkSecurityPerimetersLoggingConfiguration) GetAPIVersion() string {
	return "2025-07-01"
}

// GetResourceScope returns the scope of the resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) GetResourceScope() genruntime.ResourceScope {
	return genruntime.ResourceScopeResourceGroup
}

// GetSpec returns the specification of this resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) GetSpec() genruntime.ConvertibleSpec {
	return &configuration.Spec
}

// GetStatus returns the status of this resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) GetStatus() genruntime.ConvertibleStatus {
	return &configuration.Status
}

// GetSupportedOperations returns the operations supported by the resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) GetSupportedOperations() []genruntime.ResourceOperation {
	return []genruntime.ResourceOperation{
		genruntime.ResourceOperationDelete,
		genruntime.ResourceOperationGet,
		genruntime.ResourceOperationPut,
	}
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Network/networkSecurityPerimeters/loggingConfigurations"
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) GetType() string {
	return "Microsoft.Network/networkSecurityPerimeters/loggingConfigurations"
}

// NewEmptyStatus returns a new empty (blank) status
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) NewEmptyStatus() genruntime.ConvertibleStatus {
	return &NetworkSecurityPerimetersLoggingConfiguration_STATUS{}
}

// Owner returns the ResourceReference of the owner
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) Owner() *genruntime.ResourceReference {
	if configuration.Spec.Owner == nil {
		return nil
	}

	group, kind := genruntime.LookupOwnerGroupKind(configuration.Spec)
	return configuration.Spec.Owner.AsResourceReference(group, kind)
}

// SetStatus sets the status of this resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) SetStatus(status genruntime.ConvertibleStatus) error {
	// If we have exactly the right type of status, assign it
	if st, ok := status.(*NetworkSecurityPerimetersLoggingConfiguration_STATUS); ok {
		configuration.Status = *st
		return nil
	}

	// Convert status to required version
	var st NetworkSecurityPerimetersLoggingConfiguration_STATUS
	err := status.ConvertStatusTo(&st)
	if err != nil {
		return eris.Wrap(err, "failed to convert status")
	}

	configuration.Status = st
	return nil
}

// Hub marks that this NetworkSecurityPerimetersLoggingConfiguration is the hub type for conversion
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) Hub() {}

// OriginalGVK returns a GroupValueKind for the original API version used to create the resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration) OriginalGVK() *schema.GroupVersionKind {
	return &schema.GroupVersionKind{
		Group:   GroupVersion.Group,
		Version: configuration.Spec.OriginalVersion,
		Kind:    "NetworkSecurityPerimetersLoggingConfiguration",
	}
}

// +kubebuilder:object:root=true
// Storage version of v20250701.NetworkSecurityPerimetersLoggingConfiguration
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-07-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/loggingConfigurations/{loggingConfigurationName}
type NetworkSecurityPerimetersLoggingConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkSecurityPerimetersLoggingConfiguration `json:"items"`
}

// Storage version of v20250701.NetworkSecurityPerimetersLoggingConfiguration_Spec
type NetworkSecurityPerimetersLoggingConfiguration_Spec struct {
	// AzureName: The name of the resource in Azure. This is often the same as the name of the resource in Kubernetes but it
	// doesn't have to be.
	AzureName            string                                                     `json:"azureName,omitempty"`
	EnabledLogCategories []string                                                   `json:"enabledLogCategories,omitempty"`
	OperatorSpec         *NetworkSecurityPerimetersLoggingConfigurationOperatorSpec `json:"operatorSpec,omitempty"`
	OriginalVersion      string                                                     `json:"originalVersion,omitempty"`

	// +kubebuilder:validation:Required
	// Owner: The owner of the resource. The owner controls where the resource goes when it is deployed. The owner also
	// controls the resources lifecycle. When the owner is deleted the resource will also be deleted. Owner is expected to be a
	// reference to a network.azure.com/NetworkSecurityPerimeter resource
	Owner       *genruntime.KnownResourceReference `group:"network.azure.com" json:"owner,omitempty" kind:"NetworkSecurityPerimeter"`
	PropertyBag genruntime.PropertyBag             `json:"$propertyBag,omitempty"`
	Version     *string                            `json:"version,omitempty"`
}

var _ genruntime.ConvertibleSpec = &NetworkSecurityPerimetersLoggingConfiguration_Spec{}

// ConvertSpecFrom populates our NetworkSecurityPerimetersLoggingConfiguration_Spec from the provided source
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) ConvertSpecFrom(source genruntime.ConvertibleSpec) error {
	if source == configuration {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return source.ConvertSpecTo(configuration)
}

// ConvertSpecTo populates the provided destination from our NetworkSecurityPerimetersLoggingConfiguration_Spec
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) ConvertSpecTo(destination genruntime.ConvertibleSpec) error {
	if destination == configuration {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return destination.ConvertSpecFrom(configuration)
}

// Storage version of v20250701.NetworkSecurityPerimetersLoggingConfiguration_STATUS
type NetworkSecurityPerimetersLoggingConfiguration_STATUS struct {
	Conditions           []conditions.Condition              `json:"conditions,omitempty"`
	EnabledLogCategories []string                            `json:"enabledLogCategories,omitempty"`
	Id                   *string                             `json:"id,omitempty"`
	Name                 *string                             `json:"name,omitempty"`
	PropertyBag          genruntime.PropertyBag              `json:"$propertyBag,omitempty"`
	SystemData           *SecurityPerimeterSystemData_STATUS `json:"systemData,omitempty"`
	Type                 *string                             `json:"type,omitempty"`
	Version              *string                             `json:"version,omitempty"`
}

var _ genruntime.ConvertibleStatus = &NetworkSecurityPerimetersLoggingConfiguration_STATUS{}

// ConvertStatusFrom populates our NetworkSecurityPerimetersLoggingConfiguration_STATUS from the provided source
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_STATUS) ConvertStatusFrom(source genruntime.ConvertibleStatus) error {
	if source == configuration {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return source.ConvertStatusTo(configuration)
}

// ConvertStatusTo populates the provided destination from our NetworkSecurityPerimetersLoggingConfiguration_STATUS
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_STATUS) ConvertStatusTo(destination genruntime.ConvertibleStatus) error {
	if destination == configuration {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return destination.ConvertStatusFrom(configuration)
}

// Storage version of v20250701.NetworkSecurityPerimetersLoggingConfigurationOperatorSpec
// Details for configuring operator behavior. Fields in this struct are interpreted by the operator directly rather than being passed to Azure
type NetworkSecurityPerimetersLoggingConfigurationOperatorSpec struct {
	ConfigMapExpressions []*core.DestinationExpression `json:"configMapExpressions,omitempty"`
	PropertyBag          genruntime.PropertyBag        `json:"$propertyBag,omitempty"`
	SecretExpressions    []*core.DestinationExpression `json:"secretExpressions,omitempty"`
}

func init() {
	SchemeBuilder.Register(&NetworkSecurityPerimetersLoggingConfiguration{}, &NetworkSecurityPerimetersLoggingConfigurationList{})
}
