// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package storage

import (
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/conditions"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/configmaps"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/core"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/secrets"
	"github.com/rotisserie/eris"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// +kubebuilder:rbac:groups=network.azure.com,resources=networksecurityperimetersprofilesaccessrules,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=network.azure.com,resources={networksecurityperimetersprofilesaccessrules/status,networksecurityperimetersprofilesaccessrules/finalizers},verbs=get;update;patch

// +kubebuilder:object:root=true
// +kubebuilder:resource:categories={azure,network}
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Severity",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].severity"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].message"
// Storage version of v20250701.NetworkSecurityPerimetersProfilesAccessRule
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-07-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/profiles/{profileName}/accessRules/{accessRuleName}
type NetworkSecurityPerimetersProfilesAccessRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkSecurityPerimetersProfilesAccessRule_Spec   `json:"spec,omitempty"`
	Status            NetworkSecurityPerimetersProfilesAccessRule_STATUS `json:"status,omitempty"`
}

var _ conditions.Conditioner = &NetworkSecurityPerimetersProfilesAccessRule{}

// GetConditions returns the conditions of the resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) GetConditions() conditions.Conditions {
	return rule.Status.Conditions
}

// SetConditions sets the conditions on the resource status
func (rule *NetworkSecurityPerimetersProfilesAccessRule) SetConditions(conditions conditions.Conditions) {
	rule.Status.Conditions = conditions
}

var _ configmaps.Exporter = &NetworkSecurityPerimetersProfilesAccessRule{}

// ConfigMapDestinationExpressions returns the Spec.OperatorSpec.ConfigMapExpressions property
func (rule *NetworkSecurityPerimetersProfilesAccessRule) ConfigMapDestinationExpressions() []*core.DestinationExpression {
	if rule.Spec.OperatorSpec == nil {
		return nil
	}
	return rule.Spec.OperatorSpec.ConfigMapExpressions
}

var _ secrets.Exporter = &NetworkSecurityPerimetersProfilesAccessRule{}

// SecretDestinationExpressions returns the Spec.OperatorSpec.SecretExpressions property
func (rule *NetworkSecurityPerimetersProfilesAccessRule) SecretDestinationExpressions() []*core.DestinationExpression {
	if rule.Spec.OperatorSpec == nil {
		return nil
	}
	return rule.Spec.OperatorSpec.SecretExpressions
}

var _ genruntime.KubernetesResource = &NetworkSecurityPerimetersProfilesAccessRule{}

// AzureName returns the Azure name of the resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) AzureName() string {
	return rule.Spec.AzureName
}

// GetAPIVersion returns the ARM API version of the resource. This is always "2025-07-01"
func (rule NetworkSecurityPerimetersProfilesAccessRule) GetAPIVersion() string {
	return "2025-07-01"
}

// GetResourceScope returns the scope of the resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) GetResourceScope() genruntime.ResourceScope {
	return genruntime.ResourceScopeResourceGroup
}

// GetSpec returns the specification of this resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) GetSpec() genruntime.ConvertibleSpec {
	return &rule.Spec
}

// GetStatus returns the status of this resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) GetStatus() genruntime.ConvertibleStatus {
	return &rule.Status
}

// GetSupportedOperations returns the operations supported by the resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) GetSupportedOperations() []genruntime.ResourceOperation {
	return []genruntime.ResourceOperation{
		genruntime.ResourceOperationDelete,
		genruntime.ResourceOperationGet,
		genruntime.ResourceOperationPut,
	}
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Network/networkSecurityPerimeters/profiles/accessRules"
func (rule *NetworkSecurityPerimetersProfilesAccessRule) GetType() string {
	return "Microsoft.Network/networkSecurityPerimeters/profiles/accessRules"
}

// NewEmptyStatus returns a new empty (blank) status
func (rule *NetworkSecurityPerimetersProfilesAccessRule) NewEmptyStatus() genruntime.ConvertibleStatus {
	return &NetworkSecurityPerimetersProfilesAccessRule_STATUS{}
}

// Owner returns the ResourceReference of the owner
func (rule *NetworkSecurityPerimetersProfilesAccessRule) Owner() *genruntime.ResourceReference {
	if rule.Spec.Owner == nil {
		return nil
	}

	group, kind := genruntime.LookupOwnerGroupKind(rule.Spec)
	return rule.Spec.Owner.AsResourceReference(group, kind)
}

// SetStatus sets the status of this resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) SetStatus(status genruntime.ConvertibleStatus) error {
	// If we have exactly the right type of status, assign it
	if st, ok := status.(*NetworkSecurityPerimetersProfilesAccessRule_STATUS); ok {
		rule.Status = *st
		return nil
	}

	// Convert status to required version
	var st NetworkSecurityPerimetersProfilesAccessRule_STATUS
	err := status.ConvertStatusTo(&st)
	if err != nil {
		return eris.Wrap(err, "failed to convert status")
	}

	rule.Status = st
	return nil
}

// Hub marks that this NetworkSecurityPerimetersProfilesAccessRule is the hub type for conversion
func (rule *NetworkSecurityPerimetersProfilesAccessRule) Hub() {}

// OriginalGVK returns a GroupValueKind for the original API version used to create the resource
func (rule *NetworkSecurityPerimetersProfilesAccessRule) OriginalGVK() *schema.GroupVersionKind {
	return &schema.GroupVersionKind{
		Group:   GroupVersion.Group,
		Version: rule.Spec.OriginalVersion,
		Kind:    "NetworkSecurityPerimetersProfilesAccessRule",
	}
}

// +kubebuilder:object:root=true
// Storage version of v20250701.NetworkSecurityPerimetersProfilesAccessRule
// Generator information:
// - Generated from: /network/resource-manager/Microsoft.Network/Network/stable/2025-07-01/networkSecurityPerimeter.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/profiles/{profileName}/accessRules/{accessRuleName}
type NetworkSecurityPerimetersProfilesAccessRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkSecurityPerimetersProfilesAccessRule `json:"items"`
}

// Storage version of v20250701.NetworkSecurityPerimetersProfilesAccessRule_Spec
type NetworkSecurityPerimetersProfilesAccessRule_Spec struct {
	AddressPrefixes []string `json:"addressPrefixes,omitempty"`

	// AzureName: The name of the resource in Azure. This is often the same as the name of the resource in Kubernetes but it
	// doesn't have to be.
	AzureName                 string                                                   `json:"azureName,omitempty"`
	Direction                 *string                                                  `json:"direction,omitempty"`
	EmailAddresses            []string                                                 `json:"emailAddresses,omitempty"`
	FullyQualifiedDomainNames []string                                                 `json:"fullyQualifiedDomainNames,omitempty"`
	OperatorSpec              *NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec `json:"operatorSpec,omitempty"`
	OriginalVersion           string                                                   `json:"originalVersion,omitempty"`

	// +kubebuilder:validation:Required
	// Owner: The owner of the resource. The owner controls where the resource goes when it is deployed. The owner also
	// controls the resources lifecycle. When the owner is deleted the resource will also be deleted. Owner is expected to be a
	// reference to a network.azure.com/NetworkSecurityPerimetersProfile resource
	Owner         *genruntime.KnownResourceReference `group:"network.azure.com" json:"owner,omitempty" kind:"NetworkSecurityPerimetersProfile"`
	PhoneNumbers  []string                           `json:"phoneNumbers,omitempty"`
	PropertyBag   genruntime.PropertyBag             `json:"$propertyBag,omitempty"`
	ServiceTags   []string                           `json:"serviceTags,omitempty"`
	Subscriptions []SubscriptionId                   `json:"subscriptions,omitempty"`
}

var _ genruntime.ConvertibleSpec = &NetworkSecurityPerimetersProfilesAccessRule_Spec{}

// ConvertSpecFrom populates our NetworkSecurityPerimetersProfilesAccessRule_Spec from the provided source
func (rule *NetworkSecurityPerimetersProfilesAccessRule_Spec) ConvertSpecFrom(source genruntime.ConvertibleSpec) error {
	if source == rule {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return source.ConvertSpecTo(rule)
}

// ConvertSpecTo populates the provided destination from our NetworkSecurityPerimetersProfilesAccessRule_Spec
func (rule *NetworkSecurityPerimetersProfilesAccessRule_Spec) ConvertSpecTo(destination genruntime.ConvertibleSpec) error {
	if destination == rule {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return destination.ConvertSpecFrom(rule)
}

// Storage version of v20250701.NetworkSecurityPerimetersProfilesAccessRule_STATUS
type NetworkSecurityPerimetersProfilesAccessRule_STATUS struct {
	AddressPrefixes           []string                            `json:"addressPrefixes,omitempty"`
	Conditions                []conditions.Condition              `json:"conditions,omitempty"`
	Direction                 *string                             `json:"direction,omitempty"`
	EmailAddresses            []string                            `json:"emailAddresses,omitempty"`
	FullyQualifiedDomainNames []string                            `json:"fullyQualifiedDomainNames,omitempty"`
	Id                        *string                             `json:"id,omitempty"`
	Name                      *string                             `json:"name,omitempty"`
	NetworkSecurityPerimeters []PerimeterBasedAccessRule_STATUS   `json:"networkSecurityPerimeters,omitempty"`
	PhoneNumbers              []string                            `json:"phoneNumbers,omitempty"`
	PropertyBag               genruntime.PropertyBag              `json:"$propertyBag,omitempty"`
	ProvisioningState         *string                             `json:"provisioningState,omitempty"`
	ServiceTags               []string                            `json:"serviceTags,omitempty"`
	Subscriptions             []SubscriptionId_STATUS             `json:"subscriptions,omitempty"`
	SystemData                *SecurityPerimeterSystemData_STATUS `json:"systemData,omitempty"`
	Type                      *string                             `json:"type,omitempty"`
}

var _ genruntime.ConvertibleStatus = &NetworkSecurityPerimetersProfilesAccessRule_STATUS{}

// ConvertStatusFrom populates our NetworkSecurityPerimetersProfilesAccessRule_STATUS from the provided source
func (rule *NetworkSecurityPerimetersProfilesAccessRule_STATUS) ConvertStatusFrom(source genruntime.ConvertibleStatus) error {
	if source == rule {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return source.ConvertStatusTo(rule)
}

// ConvertStatusTo populates the provided destination from our NetworkSecurityPerimetersProfilesAccessRule_STATUS
func (rule *NetworkSecurityPerimetersProfilesAccessRule_STATUS) ConvertStatusTo(destination genruntime.ConvertibleStatus) error {
	if destination == rule {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return destination.ConvertStatusFrom(rule)
}

// Storage version of v20250701.NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec
// Details for configuring operator behavior. Fields in this struct are interpreted by the operator directly rather than being passed to Azure
type NetworkSecurityPerimetersProfilesAccessRuleOperatorSpec struct {
	ConfigMapExpressions []*core.DestinationExpression `json:"configMapExpressions,omitempty"`
	PropertyBag          genruntime.PropertyBag        `json:"$propertyBag,omitempty"`
	SecretExpressions    []*core.DestinationExpression `json:"secretExpressions,omitempty"`
}

// Storage version of v20250701.PerimeterBasedAccessRule_STATUS
type PerimeterBasedAccessRule_STATUS struct {
	Id            *string                `json:"id,omitempty"`
	Location      *string                `json:"location,omitempty"`
	PerimeterGuid *string                `json:"perimeterGuid,omitempty"`
	PropertyBag   genruntime.PropertyBag `json:"$propertyBag,omitempty"`
}

// Storage version of v20250701.SubscriptionId
type SubscriptionId struct {
	PropertyBag genruntime.PropertyBag `json:"$propertyBag,omitempty"`

	// Reference: Subscription id in the ARM id format.
	Reference *genruntime.ResourceReference `armReference:"Id" json:"reference,omitempty"`
}

// Storage version of v20250701.SubscriptionId_STATUS
type SubscriptionId_STATUS struct {
	Id          *string                `json:"id,omitempty"`
	PropertyBag genruntime.PropertyBag `json:"$propertyBag,omitempty"`
}

func init() {
	SchemeBuilder.Register(&NetworkSecurityPerimetersProfilesAccessRule{}, &NetworkSecurityPerimetersProfilesAccessRuleList{})
}
