// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package webhook

import (
	"context"
	"fmt"
	v20250501 "github.com/Azure/azure-service-operator/v2/api/network/v20250501"
	"github.com/Azure/azure-service-operator/v2/internal/reflecthelpers"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/configmaps"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/secrets"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

type NetworkSecurityPerimetersResourceAssociation struct {
}

// +kubebuilder:webhook:path=/mutate-network-azure-com-v20250501-networksecurityperimetersresourceassociation,mutating=true,sideEffects=None,matchPolicy=Exact,failurePolicy=fail,groups=network.azure.com,resources=networksecurityperimetersresourceassociations,verbs=create;update,versions=v20250501,name=default.v20250501.networksecurityperimetersresourceassociations.network.azure.com,admissionReviewVersions=v1

var _ webhook.CustomDefaulter = &NetworkSecurityPerimetersResourceAssociation{}

// Default applies defaults to the NetworkSecurityPerimetersResourceAssociation resource
func (association *NetworkSecurityPerimetersResourceAssociation) Default(ctx context.Context, obj runtime.Object) error {
	resource, ok := obj.(*v20250501.NetworkSecurityPerimetersResourceAssociation)
	if !ok {
		return fmt.Errorf("expected github.com/Azure/azure-service-operator/v2/api/network/v20250501/NetworkSecurityPerimetersResourceAssociation, but got %T", obj)
	}
	err := association.defaultImpl(ctx, resource)
	if err != nil {
		return err
	}
	var temp any = association
	if runtimeDefaulter, ok := temp.(genruntime.Defaulter); ok {
		err = runtimeDefaulter.CustomDefault(ctx, resource)
		if err != nil {
			return err
		}
	}
	return nil
}

// defaultAzureName defaults the Azure name of the resource to the Kubernetes name
func (association *NetworkSecurityPerimetersResourceAssociation) defaultAzureName(ctx context.Context, obj *v20250501.NetworkSecurityPerimetersResourceAssociation) error {
	if obj.Spec.AzureName == "" {
		obj.Spec.AzureName = obj.Name
	}
	return nil
}

// defaultImpl applies the code generated defaults to the NetworkSecurityPerimetersResourceAssociation resource
func (association *NetworkSecurityPerimetersResourceAssociation) defaultImpl(ctx context.Context, obj *v20250501.NetworkSecurityPerimetersResourceAssociation) error {
	err := association.defaultAzureName(ctx, obj)
	if err != nil {
		return err
	}
	return nil
}

// +kubebuilder:webhook:path=/validate-network-azure-com-v20250501-networksecurityperimetersresourceassociation,mutating=false,sideEffects=None,matchPolicy=Exact,failurePolicy=fail,groups=network.azure.com,resources=networksecurityperimetersresourceassociations,verbs=create;update,versions=v20250501,name=validate.v20250501.networksecurityperimetersresourceassociations.network.azure.com,admissionReviewVersions=v1

var _ webhook.CustomValidator = &NetworkSecurityPerimetersResourceAssociation{}

// ValidateCreate validates the creation of the resource
func (association *NetworkSecurityPerimetersResourceAssociation) ValidateCreate(ctx context.Context, resource runtime.Object) (admission.Warnings, error) {
	obj, ok := resource.(*v20250501.NetworkSecurityPerimetersResourceAssociation)
	if !ok {
		return nil, fmt.Errorf("expected github.com/Azure/azure-service-operator/v2/api/network/v20250501/NetworkSecurityPerimetersResourceAssociation, but got %T", resource)
	}
	validations := association.createValidations()
	var temp any = association
	if runtimeValidator, ok := temp.(genruntime.Validator[*v20250501.NetworkSecurityPerimetersResourceAssociation]); ok {
		validations = append(validations, runtimeValidator.CreateValidations()...)
	}
	return genruntime.ValidateCreate(ctx, obj, validations)
}

// ValidateDelete validates the deletion of the resource
func (association *NetworkSecurityPerimetersResourceAssociation) ValidateDelete(ctx context.Context, resource runtime.Object) (admission.Warnings, error) {
	obj, ok := resource.(*v20250501.NetworkSecurityPerimetersResourceAssociation)
	if !ok {
		return nil, fmt.Errorf("expected github.com/Azure/azure-service-operator/v2/api/network/v20250501/NetworkSecurityPerimetersResourceAssociation, but got %T", resource)
	}
	validations := association.deleteValidations()
	var temp any = association
	if runtimeValidator, ok := temp.(genruntime.Validator[*v20250501.NetworkSecurityPerimetersResourceAssociation]); ok {
		validations = append(validations, runtimeValidator.DeleteValidations()...)
	}
	return genruntime.ValidateDelete(ctx, obj, validations)
}

// ValidateUpdate validates an update of the resource
func (association *NetworkSecurityPerimetersResourceAssociation) ValidateUpdate(ctx context.Context, oldResource runtime.Object, newResource runtime.Object) (admission.Warnings, error) {
	newObj, ok := newResource.(*v20250501.NetworkSecurityPerimetersResourceAssociation)
	if !ok {
		return nil, fmt.Errorf("expected github.com/Azure/azure-service-operator/v2/api/network/v20250501/NetworkSecurityPerimetersResourceAssociation, but got %T", newResource)
	}
	oldObj, ok := oldResource.(*v20250501.NetworkSecurityPerimetersResourceAssociation)
	if !ok {
		return nil, fmt.Errorf("expected github.com/Azure/azure-service-operator/v2/api/network/v20250501/NetworkSecurityPerimetersResourceAssociation, but got %T", oldResource)
	}
	validations := association.updateValidations()
	var temp any = association
	if runtimeValidator, ok := temp.(genruntime.Validator[*v20250501.NetworkSecurityPerimetersResourceAssociation]); ok {
		validations = append(validations, runtimeValidator.UpdateValidations()...)
	}
	return genruntime.ValidateUpdate(
		ctx,
		oldObj,
		newObj,
		validations)
}

// createValidations validates the creation of the resource
func (association *NetworkSecurityPerimetersResourceAssociation) createValidations() []func(ctx context.Context, obj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error) {
	return []func(ctx context.Context, obj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error){
		association.validateResourceReferences,
		association.validateOwnerReference,
		association.validateSecretDestinations,
		association.validateConfigMapDestinations,
	}
}

// deleteValidations validates the deletion of the resource
func (association *NetworkSecurityPerimetersResourceAssociation) deleteValidations() []func(ctx context.Context, obj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error) {
	return nil
}

// updateValidations validates the update of the resource
func (association *NetworkSecurityPerimetersResourceAssociation) updateValidations() []func(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimetersResourceAssociation, newObj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error) {
	return []func(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimetersResourceAssociation, newObj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error){
		func(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimetersResourceAssociation, newObj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error) {
			return association.validateResourceReferences(ctx, newObj)
		},
		association.validateWriteOnceProperties,
		func(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimetersResourceAssociation, newObj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error) {
			return association.validateOwnerReference(ctx, newObj)
		},
		func(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimetersResourceAssociation, newObj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error) {
			return association.validateSecretDestinations(ctx, newObj)
		},
		func(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimetersResourceAssociation, newObj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error) {
			return association.validateConfigMapDestinations(ctx, newObj)
		},
	}
}

// validateConfigMapDestinations validates there are no colliding genruntime.ConfigMapDestinations
func (association *NetworkSecurityPerimetersResourceAssociation) validateConfigMapDestinations(ctx context.Context, obj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error) {
	if obj.Spec.OperatorSpec == nil {
		return nil, nil
	}
	return configmaps.ValidateDestinations(obj, nil, obj.Spec.OperatorSpec.ConfigMapExpressions)
}

// validateOwnerReference validates the owner field
func (association *NetworkSecurityPerimetersResourceAssociation) validateOwnerReference(ctx context.Context, obj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error) {
	return genruntime.ValidateOwner(obj)
}

// validateResourceReferences validates all resource references
func (association *NetworkSecurityPerimetersResourceAssociation) validateResourceReferences(ctx context.Context, obj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error) {
	refs, err := reflecthelpers.FindResourceReferences(&obj.Spec)
	if err != nil {
		return nil, err
	}
	return genruntime.ValidateResourceReferences(refs)
}

// validateSecretDestinations validates there are no colliding genruntime.SecretDestination's
func (association *NetworkSecurityPerimetersResourceAssociation) validateSecretDestinations(ctx context.Context, obj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error) {
	if obj.Spec.OperatorSpec == nil {
		return nil, nil
	}
	return secrets.ValidateDestinations(obj, nil, obj.Spec.OperatorSpec.SecretExpressions)
}

// validateWriteOnceProperties validates all WriteOnce properties
func (association *NetworkSecurityPerimetersResourceAssociation) validateWriteOnceProperties(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimetersResourceAssociation, newObj *v20250501.NetworkSecurityPerimetersResourceAssociation) (admission.Warnings, error) {
	return genruntime.ValidateWriteOnceProperties(oldObj, newObj)
}
