// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package webhook

import (
	"context"
	"fmt"
	v20250501 "github.com/Azure/azure-service-operator/v2/api/network/v20250501"
	"github.com/Azure/azure-service-operator/v2/internal/reflecthelpers"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/configmaps"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/secrets"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

type NetworkSecurityPerimeter struct {
}

// +kubebuilder:webhook:path=/mutate-network-azure-com-v20250501-networksecurityperimeter,mutating=true,sideEffects=None,matchPolicy=Exact,failurePolicy=fail,groups=network.azure.com,resources=networksecurityperimeters,verbs=create;update,versions=v20250501,name=default.v20250501.networksecurityperimeters.network.azure.com,admissionReviewVersions=v1

var _ webhook.CustomDefaulter = &NetworkSecurityPerimeter{}

// Default applies defaults to the NetworkSecurityPerimeter resource
func (perimeter *NetworkSecurityPerimeter) Default(ctx context.Context, obj runtime.Object) error {
	resource, ok := obj.(*v20250501.NetworkSecurityPerimeter)
	if !ok {
		return fmt.Errorf("expected github.com/Azure/azure-service-operator/v2/api/network/v20250501/NetworkSecurityPerimeter, but got %T", obj)
	}
	err := perimeter.defaultImpl(ctx, resource)
	if err != nil {
		return err
	}
	var temp any = perimeter
	if runtimeDefaulter, ok := temp.(genruntime.Defaulter); ok {
		err = runtimeDefaulter.CustomDefault(ctx, resource)
		if err != nil {
			return err
		}
	}
	return nil
}

// defaultAzureName defaults the Azure name of the resource to the Kubernetes name
func (perimeter *NetworkSecurityPerimeter) defaultAzureName(ctx context.Context, obj *v20250501.NetworkSecurityPerimeter) error {
	if obj.Spec.AzureName == "" {
		obj.Spec.AzureName = obj.Name
	}
	return nil
}

// defaultImpl applies the code generated defaults to the NetworkSecurityPerimeter resource
func (perimeter *NetworkSecurityPerimeter) defaultImpl(ctx context.Context, obj *v20250501.NetworkSecurityPerimeter) error {
	err := perimeter.defaultAzureName(ctx, obj)
	if err != nil {
		return err
	}
	return nil
}

// +kubebuilder:webhook:path=/validate-network-azure-com-v20250501-networksecurityperimeter,mutating=false,sideEffects=None,matchPolicy=Exact,failurePolicy=fail,groups=network.azure.com,resources=networksecurityperimeters,verbs=create;update,versions=v20250501,name=validate.v20250501.networksecurityperimeters.network.azure.com,admissionReviewVersions=v1

var _ webhook.CustomValidator = &NetworkSecurityPerimeter{}

// ValidateCreate validates the creation of the resource
func (perimeter *NetworkSecurityPerimeter) ValidateCreate(ctx context.Context, resource runtime.Object) (admission.Warnings, error) {
	obj, ok := resource.(*v20250501.NetworkSecurityPerimeter)
	if !ok {
		return nil, fmt.Errorf("expected github.com/Azure/azure-service-operator/v2/api/network/v20250501/NetworkSecurityPerimeter, but got %T", resource)
	}
	validations := perimeter.createValidations()
	var temp any = perimeter
	if runtimeValidator, ok := temp.(genruntime.Validator[*v20250501.NetworkSecurityPerimeter]); ok {
		validations = append(validations, runtimeValidator.CreateValidations()...)
	}
	return genruntime.ValidateCreate(ctx, obj, validations)
}

// ValidateDelete validates the deletion of the resource
func (perimeter *NetworkSecurityPerimeter) ValidateDelete(ctx context.Context, resource runtime.Object) (admission.Warnings, error) {
	obj, ok := resource.(*v20250501.NetworkSecurityPerimeter)
	if !ok {
		return nil, fmt.Errorf("expected github.com/Azure/azure-service-operator/v2/api/network/v20250501/NetworkSecurityPerimeter, but got %T", resource)
	}
	validations := perimeter.deleteValidations()
	var temp any = perimeter
	if runtimeValidator, ok := temp.(genruntime.Validator[*v20250501.NetworkSecurityPerimeter]); ok {
		validations = append(validations, runtimeValidator.DeleteValidations()...)
	}
	return genruntime.ValidateDelete(ctx, obj, validations)
}

// ValidateUpdate validates an update of the resource
func (perimeter *NetworkSecurityPerimeter) ValidateUpdate(ctx context.Context, oldResource runtime.Object, newResource runtime.Object) (admission.Warnings, error) {
	newObj, ok := newResource.(*v20250501.NetworkSecurityPerimeter)
	if !ok {
		return nil, fmt.Errorf("expected github.com/Azure/azure-service-operator/v2/api/network/v20250501/NetworkSecurityPerimeter, but got %T", newResource)
	}
	oldObj, ok := oldResource.(*v20250501.NetworkSecurityPerimeter)
	if !ok {
		return nil, fmt.Errorf("expected github.com/Azure/azure-service-operator/v2/api/network/v20250501/NetworkSecurityPerimeter, but got %T", oldResource)
	}
	validations := perimeter.updateValidations()
	var temp any = perimeter
	if runtimeValidator, ok := temp.(genruntime.Validator[*v20250501.NetworkSecurityPerimeter]); ok {
		validations = append(validations, runtimeValidator.UpdateValidations()...)
	}
	return genruntime.ValidateUpdate(
		ctx,
		oldObj,
		newObj,
		validations)
}

// createValidations validates the creation of the resource
func (perimeter *NetworkSecurityPerimeter) createValidations() []func(ctx context.Context, obj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error) {
	return []func(ctx context.Context, obj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error){
		perimeter.validateResourceReferences,
		perimeter.validateOwnerReference,
		perimeter.validateSecretDestinations,
		perimeter.validateConfigMapDestinations,
	}
}

// deleteValidations validates the deletion of the resource
func (perimeter *NetworkSecurityPerimeter) deleteValidations() []func(ctx context.Context, obj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error) {
	return nil
}

// updateValidations validates the update of the resource
func (perimeter *NetworkSecurityPerimeter) updateValidations() []func(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimeter, newObj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error) {
	return []func(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimeter, newObj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error){
		func(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimeter, newObj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error) {
			return perimeter.validateResourceReferences(ctx, newObj)
		},
		perimeter.validateWriteOnceProperties,
		func(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimeter, newObj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error) {
			return perimeter.validateOwnerReference(ctx, newObj)
		},
		func(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimeter, newObj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error) {
			return perimeter.validateSecretDestinations(ctx, newObj)
		},
		func(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimeter, newObj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error) {
			return perimeter.validateConfigMapDestinations(ctx, newObj)
		},
	}
}

// validateConfigMapDestinations validates there are no colliding genruntime.ConfigMapDestinations
func (perimeter *NetworkSecurityPerimeter) validateConfigMapDestinations(ctx context.Context, obj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error) {
	if obj.Spec.OperatorSpec == nil {
		return nil, nil
	}
	return configmaps.ValidateDestinations(obj, nil, obj.Spec.OperatorSpec.ConfigMapExpressions)
}

// validateOwnerReference validates the owner field
func (perimeter *NetworkSecurityPerimeter) validateOwnerReference(ctx context.Context, obj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error) {
	return genruntime.ValidateOwner(obj)
}

// validateResourceReferences validates all resource references
func (perimeter *NetworkSecurityPerimeter) validateResourceReferences(ctx context.Context, obj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error) {
	refs, err := reflecthelpers.FindResourceReferences(&obj.Spec)
	if err != nil {
		return nil, err
	}
	return genruntime.ValidateResourceReferences(refs)
}

// validateSecretDestinations validates there are no colliding genruntime.SecretDestination's
func (perimeter *NetworkSecurityPerimeter) validateSecretDestinations(ctx context.Context, obj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error) {
	if obj.Spec.OperatorSpec == nil {
		return nil, nil
	}
	return secrets.ValidateDestinations(obj, nil, obj.Spec.OperatorSpec.SecretExpressions)
}

// validateWriteOnceProperties validates all WriteOnce properties
func (perimeter *NetworkSecurityPerimeter) validateWriteOnceProperties(ctx context.Context, oldObj *v20250501.NetworkSecurityPerimeter, newObj *v20250501.NetworkSecurityPerimeter) (admission.Warnings, error) {
	return genruntime.ValidateWriteOnceProperties(oldObj, newObj)
}
