// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_NetworkSecurityPerimetersLoggingConfiguration_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersLoggingConfiguration_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersLoggingConfiguration_STATUS, NetworkSecurityPerimetersLoggingConfiguration_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersLoggingConfiguration_STATUS runs a test to see if a specific instance of NetworkSecurityPerimetersLoggingConfiguration_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersLoggingConfiguration_STATUS(subject NetworkSecurityPerimetersLoggingConfiguration_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersLoggingConfiguration_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersLoggingConfiguration_STATUS instances for property testing - lazily
// instantiated by NetworkSecurityPerimetersLoggingConfiguration_STATUSGenerator()
var networkSecurityPerimetersLoggingConfiguration_STATUSGenerator gopter.Gen

// NetworkSecurityPerimetersLoggingConfiguration_STATUSGenerator returns a generator of NetworkSecurityPerimetersLoggingConfiguration_STATUS instances for property testing.
// We first initialize networkSecurityPerimetersLoggingConfiguration_STATUSGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimetersLoggingConfiguration_STATUSGenerator() gopter.Gen {
	if networkSecurityPerimetersLoggingConfiguration_STATUSGenerator != nil {
		return networkSecurityPerimetersLoggingConfiguration_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLoggingConfiguration_STATUS(generators)
	networkSecurityPerimetersLoggingConfiguration_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLoggingConfiguration_STATUS{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLoggingConfiguration_STATUS(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLoggingConfiguration_STATUS(generators)
	networkSecurityPerimetersLoggingConfiguration_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLoggingConfiguration_STATUS{}), generators)

	return networkSecurityPerimetersLoggingConfiguration_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLoggingConfiguration_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLoggingConfiguration_STATUS(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLoggingConfiguration_STATUS is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLoggingConfiguration_STATUS(gens map[string]gopter.Gen) {
	gens["Properties"] = gen.PtrOf(NspLoggingConfigurationProperties_STATUSGenerator())
	gens["SystemData"] = gen.PtrOf(SecurityPerimeterSystemData_STATUSGenerator())
}

func Test_NspLoggingConfigurationProperties_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NspLoggingConfigurationProperties_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNspLoggingConfigurationProperties_STATUS, NspLoggingConfigurationProperties_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNspLoggingConfigurationProperties_STATUS runs a test to see if a specific instance of NspLoggingConfigurationProperties_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNspLoggingConfigurationProperties_STATUS(subject NspLoggingConfigurationProperties_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NspLoggingConfigurationProperties_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NspLoggingConfigurationProperties_STATUS instances for property testing - lazily instantiated by
// NspLoggingConfigurationProperties_STATUSGenerator()
var nspLoggingConfigurationProperties_STATUSGenerator gopter.Gen

// NspLoggingConfigurationProperties_STATUSGenerator returns a generator of NspLoggingConfigurationProperties_STATUS instances for property testing.
func NspLoggingConfigurationProperties_STATUSGenerator() gopter.Gen {
	if nspLoggingConfigurationProperties_STATUSGenerator != nil {
		return nspLoggingConfigurationProperties_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNspLoggingConfigurationProperties_STATUS(generators)
	nspLoggingConfigurationProperties_STATUSGenerator = gen.Struct(reflect.TypeOf(NspLoggingConfigurationProperties_STATUS{}), generators)

	return nspLoggingConfigurationProperties_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNspLoggingConfigurationProperties_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNspLoggingConfigurationProperties_STATUS(gens map[string]gopter.Gen) {
	gens["EnabledLogCategories"] = gen.SliceOf(gen.AlphaString())
	gens["Version"] = gen.PtrOf(gen.AlphaString())
}
