// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_NetworkSecurityPerimeterProperties_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimeterProperties_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimeterProperties_STATUS, NetworkSecurityPerimeterProperties_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimeterProperties_STATUS runs a test to see if a specific instance of NetworkSecurityPerimeterProperties_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimeterProperties_STATUS(subject NetworkSecurityPerimeterProperties_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimeterProperties_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimeterProperties_STATUS instances for property testing - lazily instantiated by
// NetworkSecurityPerimeterProperties_STATUSGenerator()
var networkSecurityPerimeterProperties_STATUSGenerator gopter.Gen

// NetworkSecurityPerimeterProperties_STATUSGenerator returns a generator of NetworkSecurityPerimeterProperties_STATUS instances for property testing.
func NetworkSecurityPerimeterProperties_STATUSGenerator() gopter.Gen {
	if networkSecurityPerimeterProperties_STATUSGenerator != nil {
		return networkSecurityPerimeterProperties_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimeterProperties_STATUS(generators)
	networkSecurityPerimeterProperties_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimeterProperties_STATUS{}), generators)

	return networkSecurityPerimeterProperties_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimeterProperties_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimeterProperties_STATUS(gens map[string]gopter.Gen) {
	gens["PerimeterGuid"] = gen.PtrOf(gen.AlphaString())
	gens["ProvisioningState"] = gen.PtrOf(gen.OneConstOf(
		NspProvisioningState_STATUS_Accepted,
		NspProvisioningState_STATUS_Creating,
		NspProvisioningState_STATUS_Deleting,
		NspProvisioningState_STATUS_Failed,
		NspProvisioningState_STATUS_Succeeded,
		NspProvisioningState_STATUS_Updating))
}

func Test_NetworkSecurityPerimeter_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimeter_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimeter_STATUS, NetworkSecurityPerimeter_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimeter_STATUS runs a test to see if a specific instance of NetworkSecurityPerimeter_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimeter_STATUS(subject NetworkSecurityPerimeter_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimeter_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimeter_STATUS instances for property testing - lazily instantiated by
// NetworkSecurityPerimeter_STATUSGenerator()
var networkSecurityPerimeter_STATUSGenerator gopter.Gen

// NetworkSecurityPerimeter_STATUSGenerator returns a generator of NetworkSecurityPerimeter_STATUS instances for property testing.
// We first initialize networkSecurityPerimeter_STATUSGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimeter_STATUSGenerator() gopter.Gen {
	if networkSecurityPerimeter_STATUSGenerator != nil {
		return networkSecurityPerimeter_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimeter_STATUS(generators)
	networkSecurityPerimeter_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimeter_STATUS{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimeter_STATUS(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimeter_STATUS(generators)
	networkSecurityPerimeter_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimeter_STATUS{}), generators)

	return networkSecurityPerimeter_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimeter_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimeter_STATUS(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Location"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["Tags"] = gen.MapOf(
		gen.AlphaString(),
		gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimeter_STATUS is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimeter_STATUS(gens map[string]gopter.Gen) {
	gens["Properties"] = gen.PtrOf(NetworkSecurityPerimeterProperties_STATUSGenerator())
	gens["SystemData"] = gen.PtrOf(SecurityPerimeterSystemData_STATUSGenerator())
}

func Test_SecurityPerimeterSystemData_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of SecurityPerimeterSystemData_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForSecurityPerimeterSystemData_STATUS, SecurityPerimeterSystemData_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForSecurityPerimeterSystemData_STATUS runs a test to see if a specific instance of SecurityPerimeterSystemData_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForSecurityPerimeterSystemData_STATUS(subject SecurityPerimeterSystemData_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual SecurityPerimeterSystemData_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of SecurityPerimeterSystemData_STATUS instances for property testing - lazily instantiated by
// SecurityPerimeterSystemData_STATUSGenerator()
var securityPerimeterSystemData_STATUSGenerator gopter.Gen

// SecurityPerimeterSystemData_STATUSGenerator returns a generator of SecurityPerimeterSystemData_STATUS instances for property testing.
func SecurityPerimeterSystemData_STATUSGenerator() gopter.Gen {
	if securityPerimeterSystemData_STATUSGenerator != nil {
		return securityPerimeterSystemData_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForSecurityPerimeterSystemData_STATUS(generators)
	securityPerimeterSystemData_STATUSGenerator = gen.Struct(reflect.TypeOf(SecurityPerimeterSystemData_STATUS{}), generators)

	return securityPerimeterSystemData_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForSecurityPerimeterSystemData_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForSecurityPerimeterSystemData_STATUS(gens map[string]gopter.Gen) {
	gens["CreatedAt"] = gen.PtrOf(gen.AlphaString())
	gens["CreatedBy"] = gen.PtrOf(gen.AlphaString())
	gens["CreatedByType"] = gen.PtrOf(gen.OneConstOf(
		CreatedByType_STATUS_Application,
		CreatedByType_STATUS_Key,
		CreatedByType_STATUS_ManagedIdentity,
		CreatedByType_STATUS_User))
	gens["LastModifiedAt"] = gen.PtrOf(gen.AlphaString())
	gens["LastModifiedBy"] = gen.PtrOf(gen.AlphaString())
	gens["LastModifiedByType"] = gen.PtrOf(gen.OneConstOf(
		CreatedByType_STATUS_Application,
		CreatedByType_STATUS_Key,
		CreatedByType_STATUS_ManagedIdentity,
		CreatedByType_STATUS_User))
}
