// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import "github.com/Azure/azure-service-operator/v2/pkg/genruntime"

type NetworkSecurityPerimetersLoggingConfiguration_Spec struct {
	Name string `json:"name,omitempty"`

	// Properties: Properties of the NSP logging configuration.
	Properties *NspLoggingConfigurationProperties `json:"properties,omitempty"`
}

var _ genruntime.ARMResourceSpec = &NetworkSecurityPerimetersLoggingConfiguration_Spec{}

// GetAPIVersion returns the ARM API version of the resource. This is always "2025-07-01"
func (configuration NetworkSecurityPerimetersLoggingConfiguration_Spec) GetAPIVersion() string {
	return "2025-07-01"
}

// GetName returns the Name of the resource
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) GetName() string {
	return configuration.Name
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Network/networkSecurityPerimeters/loggingConfigurations"
func (configuration *NetworkSecurityPerimetersLoggingConfiguration_Spec) GetType() string {
	return "Microsoft.Network/networkSecurityPerimeters/loggingConfigurations"
}

// The NSP logging configuration properties.
type NspLoggingConfigurationProperties struct {
	// EnabledLogCategories: The log categories to enable in the NSP logging configuration.
	EnabledLogCategories []string `json:"enabledLogCategories,omitempty"`

	// Version: The version of the NSP logging configuration.
	Version *string `json:"version,omitempty"`
}
