// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_NetworkSecurityPerimetersProfilesAccessRule_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersProfilesAccessRule_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersProfilesAccessRule_STATUS, NetworkSecurityPerimetersProfilesAccessRule_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersProfilesAccessRule_STATUS runs a test to see if a specific instance of NetworkSecurityPerimetersProfilesAccessRule_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersProfilesAccessRule_STATUS(subject NetworkSecurityPerimetersProfilesAccessRule_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersProfilesAccessRule_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersProfilesAccessRule_STATUS instances for property testing - lazily instantiated
// by NetworkSecurityPerimetersProfilesAccessRule_STATUSGenerator()
var networkSecurityPerimetersProfilesAccessRule_STATUSGenerator gopter.Gen

// NetworkSecurityPerimetersProfilesAccessRule_STATUSGenerator returns a generator of NetworkSecurityPerimetersProfilesAccessRule_STATUS instances for property testing.
// We first initialize networkSecurityPerimetersProfilesAccessRule_STATUSGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimetersProfilesAccessRule_STATUSGenerator() gopter.Gen {
	if networkSecurityPerimetersProfilesAccessRule_STATUSGenerator != nil {
		return networkSecurityPerimetersProfilesAccessRule_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfilesAccessRule_STATUS(generators)
	networkSecurityPerimetersProfilesAccessRule_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersProfilesAccessRule_STATUS{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfilesAccessRule_STATUS(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfilesAccessRule_STATUS(generators)
	networkSecurityPerimetersProfilesAccessRule_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersProfilesAccessRule_STATUS{}), generators)

	return networkSecurityPerimetersProfilesAccessRule_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfilesAccessRule_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersProfilesAccessRule_STATUS(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfilesAccessRule_STATUS is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersProfilesAccessRule_STATUS(gens map[string]gopter.Gen) {
	gens["Properties"] = gen.PtrOf(NspAccessRuleProperties_STATUSGenerator())
	gens["SystemData"] = gen.PtrOf(SecurityPerimeterSystemData_STATUSGenerator())
}

func Test_NspAccessRuleProperties_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NspAccessRuleProperties_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNspAccessRuleProperties_STATUS, NspAccessRuleProperties_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNspAccessRuleProperties_STATUS runs a test to see if a specific instance of NspAccessRuleProperties_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNspAccessRuleProperties_STATUS(subject NspAccessRuleProperties_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NspAccessRuleProperties_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NspAccessRuleProperties_STATUS instances for property testing - lazily instantiated by
// NspAccessRuleProperties_STATUSGenerator()
var nspAccessRuleProperties_STATUSGenerator gopter.Gen

// NspAccessRuleProperties_STATUSGenerator returns a generator of NspAccessRuleProperties_STATUS instances for property testing.
// We first initialize nspAccessRuleProperties_STATUSGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NspAccessRuleProperties_STATUSGenerator() gopter.Gen {
	if nspAccessRuleProperties_STATUSGenerator != nil {
		return nspAccessRuleProperties_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNspAccessRuleProperties_STATUS(generators)
	nspAccessRuleProperties_STATUSGenerator = gen.Struct(reflect.TypeOf(NspAccessRuleProperties_STATUS{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNspAccessRuleProperties_STATUS(generators)
	AddRelatedPropertyGeneratorsForNspAccessRuleProperties_STATUS(generators)
	nspAccessRuleProperties_STATUSGenerator = gen.Struct(reflect.TypeOf(NspAccessRuleProperties_STATUS{}), generators)

	return nspAccessRuleProperties_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNspAccessRuleProperties_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNspAccessRuleProperties_STATUS(gens map[string]gopter.Gen) {
	gens["AddressPrefixes"] = gen.SliceOf(gen.AlphaString())
	gens["Direction"] = gen.PtrOf(gen.OneConstOf(AccessRuleDirection_STATUS_Inbound, AccessRuleDirection_STATUS_Outbound))
	gens["EmailAddresses"] = gen.SliceOf(gen.AlphaString())
	gens["FullyQualifiedDomainNames"] = gen.SliceOf(gen.AlphaString())
	gens["PhoneNumbers"] = gen.SliceOf(gen.AlphaString())
	gens["ProvisioningState"] = gen.PtrOf(gen.OneConstOf(
		NspProvisioningState_STATUS_Accepted,
		NspProvisioningState_STATUS_Creating,
		NspProvisioningState_STATUS_Deleting,
		NspProvisioningState_STATUS_Failed,
		NspProvisioningState_STATUS_Succeeded,
		NspProvisioningState_STATUS_Updating))
	gens["ServiceTags"] = gen.SliceOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForNspAccessRuleProperties_STATUS is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNspAccessRuleProperties_STATUS(gens map[string]gopter.Gen) {
	gens["NetworkSecurityPerimeters"] = gen.SliceOf(PerimeterBasedAccessRule_STATUSGenerator())
	gens["Subscriptions"] = gen.SliceOf(SubscriptionId_STATUSGenerator())
}

func Test_PerimeterBasedAccessRule_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of PerimeterBasedAccessRule_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForPerimeterBasedAccessRule_STATUS, PerimeterBasedAccessRule_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForPerimeterBasedAccessRule_STATUS runs a test to see if a specific instance of PerimeterBasedAccessRule_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForPerimeterBasedAccessRule_STATUS(subject PerimeterBasedAccessRule_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual PerimeterBasedAccessRule_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of PerimeterBasedAccessRule_STATUS instances for property testing - lazily instantiated by
// PerimeterBasedAccessRule_STATUSGenerator()
var perimeterBasedAccessRule_STATUSGenerator gopter.Gen

// PerimeterBasedAccessRule_STATUSGenerator returns a generator of PerimeterBasedAccessRule_STATUS instances for property testing.
func PerimeterBasedAccessRule_STATUSGenerator() gopter.Gen {
	if perimeterBasedAccessRule_STATUSGenerator != nil {
		return perimeterBasedAccessRule_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForPerimeterBasedAccessRule_STATUS(generators)
	perimeterBasedAccessRule_STATUSGenerator = gen.Struct(reflect.TypeOf(PerimeterBasedAccessRule_STATUS{}), generators)

	return perimeterBasedAccessRule_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForPerimeterBasedAccessRule_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForPerimeterBasedAccessRule_STATUS(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Location"] = gen.PtrOf(gen.AlphaString())
	gens["PerimeterGuid"] = gen.PtrOf(gen.AlphaString())
}

func Test_SubscriptionId_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of SubscriptionId_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForSubscriptionId_STATUS, SubscriptionId_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForSubscriptionId_STATUS runs a test to see if a specific instance of SubscriptionId_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForSubscriptionId_STATUS(subject SubscriptionId_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual SubscriptionId_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of SubscriptionId_STATUS instances for property testing - lazily instantiated by
// SubscriptionId_STATUSGenerator()
var subscriptionId_STATUSGenerator gopter.Gen

// SubscriptionId_STATUSGenerator returns a generator of SubscriptionId_STATUS instances for property testing.
func SubscriptionId_STATUSGenerator() gopter.Gen {
	if subscriptionId_STATUSGenerator != nil {
		return subscriptionId_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForSubscriptionId_STATUS(generators)
	subscriptionId_STATUSGenerator = gen.Struct(reflect.TypeOf(SubscriptionId_STATUS{}), generators)

	return subscriptionId_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForSubscriptionId_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForSubscriptionId_STATUS(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
}
