// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_NetworkSecurityPerimetersLink_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersLink_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersLink_Spec, NetworkSecurityPerimetersLink_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersLink_Spec runs a test to see if a specific instance of NetworkSecurityPerimetersLink_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersLink_Spec(subject NetworkSecurityPerimetersLink_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersLink_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersLink_Spec instances for property testing - lazily instantiated by
// NetworkSecurityPerimetersLink_SpecGenerator()
var networkSecurityPerimetersLink_SpecGenerator gopter.Gen

// NetworkSecurityPerimetersLink_SpecGenerator returns a generator of NetworkSecurityPerimetersLink_Spec instances for property testing.
// We first initialize networkSecurityPerimetersLink_SpecGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimetersLink_SpecGenerator() gopter.Gen {
	if networkSecurityPerimetersLink_SpecGenerator != nil {
		return networkSecurityPerimetersLink_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec(generators)
	networkSecurityPerimetersLink_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLink_Spec{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec(generators)
	networkSecurityPerimetersLink_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersLink_Spec{}), generators)

	return networkSecurityPerimetersLink_SpecGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec(gens map[string]gopter.Gen) {
	gens["Name"] = gen.AlphaString()
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersLink_Spec(gens map[string]gopter.Gen) {
	gens["Properties"] = gen.PtrOf(NspLinkPropertiesGenerator())
}

func Test_NspLinkProperties_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NspLinkProperties via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNspLinkProperties, NspLinkPropertiesGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNspLinkProperties runs a test to see if a specific instance of NspLinkProperties round trips to JSON and back losslessly
func RunJSONSerializationTestForNspLinkProperties(subject NspLinkProperties) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NspLinkProperties
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NspLinkProperties instances for property testing - lazily instantiated by NspLinkPropertiesGenerator()
var nspLinkPropertiesGenerator gopter.Gen

// NspLinkPropertiesGenerator returns a generator of NspLinkProperties instances for property testing.
func NspLinkPropertiesGenerator() gopter.Gen {
	if nspLinkPropertiesGenerator != nil {
		return nspLinkPropertiesGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNspLinkProperties(generators)
	nspLinkPropertiesGenerator = gen.Struct(reflect.TypeOf(NspLinkProperties{}), generators)

	return nspLinkPropertiesGenerator
}

// AddIndependentPropertyGeneratorsForNspLinkProperties is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNspLinkProperties(gens map[string]gopter.Gen) {
	gens["AutoApprovedRemotePerimeterResourceId"] = gen.PtrOf(gen.AlphaString())
	gens["Description"] = gen.PtrOf(gen.AlphaString())
	gens["LocalInboundProfiles"] = gen.SliceOf(gen.AlphaString())
	gens["RemoteInboundProfiles"] = gen.SliceOf(gen.AlphaString())
}
