// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

type NetworkSecurityPerimetersLink_STATUS struct {
	// Id: Fully qualified resource ID for the resource. E.g.
	// "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id *string `json:"id,omitempty"`

	// Name: The name of the resource
	Name *string `json:"name,omitempty"`

	// Properties: Properties of the network security perimeter link resource.
	Properties *NspLinkProperties_STATUS `json:"properties,omitempty"`

	// SystemData: Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SecurityPerimeterSystemData_STATUS `json:"systemData,omitempty"`

	// Type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`
}

// Properties of NSP Link resource.
type NspLinkProperties_STATUS struct {
	// AutoApprovedRemotePerimeterResourceId: Perimeter ARM Id for the remote NSP with which the link gets created in
	// Auto-approval mode. It should be used when the NSP admin have
	// Microsoft.Network/networkSecurityPerimeters/linkPerimeter/action permission on the remote NSP resource.
	AutoApprovedRemotePerimeterResourceId *string `json:"autoApprovedRemotePerimeterResourceId,omitempty"`

	// Description: A message passed to the owner of the remote NSP link resource with this connection request. In case of
	// Auto-approved flow, it is default to 'Auto Approved'. Restricted to 140 chars.
	Description *string `json:"description,omitempty"`

	// LocalInboundProfiles: Local Inbound profile names to which Inbound is allowed. Use ['*'] to allow inbound to all
	// profiles.
	LocalInboundProfiles []string `json:"localInboundProfiles,omitempty"`

	// LocalOutboundProfiles: Local Outbound profile names from which Outbound is allowed. In current version, it is readonly
	// property and it's value is set to ['*'] to allow outbound from all profiles. In later version, user will be able to
	// modify it.
	LocalOutboundProfiles []string `json:"localOutboundProfiles,omitempty"`

	// ProvisioningState: The provisioning state of the NSP Link resource.
	ProvisioningState *NspLinkProvisioningState_STATUS `json:"provisioningState,omitempty"`

	// RemoteInboundProfiles: Remote Inbound profile names to which Inbound is allowed. Use ['*'] to allow inbound to all
	// profiles. This property can only be updated in auto-approval mode.
	RemoteInboundProfiles []string `json:"remoteInboundProfiles,omitempty"`

	// RemoteOutboundProfiles: Remote Outbound profile names from which Outbound is allowed. In current version, it is readonly
	// property and it's value is set to ['*'] to allow outbound from all profiles. In later version, user will be able to
	// modify it.
	RemoteOutboundProfiles []string `json:"remoteOutboundProfiles,omitempty"`

	// RemotePerimeterGuid: Remote NSP Guid with which the link gets created.
	RemotePerimeterGuid *string `json:"remotePerimeterGuid,omitempty"`

	// RemotePerimeterLocation: Remote NSP location with which the link gets created.
	RemotePerimeterLocation *string `json:"remotePerimeterLocation,omitempty"`

	// Status: The NSP link state.
	Status *NspLinkStatus_STATUS `json:"status,omitempty"`
}

// The current provisioning state of NSP Link/LinkReference.
type NspLinkProvisioningState_STATUS string

const (
	NspLinkProvisioningState_STATUS_Accepted                = NspLinkProvisioningState_STATUS("Accepted")
	NspLinkProvisioningState_STATUS_Creating                = NspLinkProvisioningState_STATUS("Creating")
	NspLinkProvisioningState_STATUS_Deleting                = NspLinkProvisioningState_STATUS("Deleting")
	NspLinkProvisioningState_STATUS_Failed                  = NspLinkProvisioningState_STATUS("Failed")
	NspLinkProvisioningState_STATUS_Succeeded               = NspLinkProvisioningState_STATUS("Succeeded")
	NspLinkProvisioningState_STATUS_Updating                = NspLinkProvisioningState_STATUS("Updating")
	NspLinkProvisioningState_STATUS_WaitForRemoteCompletion = NspLinkProvisioningState_STATUS("WaitForRemoteCompletion")
)

// Mapping from string to NspLinkProvisioningState_STATUS
var nspLinkProvisioningState_STATUS_Values = map[string]NspLinkProvisioningState_STATUS{
	"accepted":                NspLinkProvisioningState_STATUS_Accepted,
	"creating":                NspLinkProvisioningState_STATUS_Creating,
	"deleting":                NspLinkProvisioningState_STATUS_Deleting,
	"failed":                  NspLinkProvisioningState_STATUS_Failed,
	"succeeded":               NspLinkProvisioningState_STATUS_Succeeded,
	"updating":                NspLinkProvisioningState_STATUS_Updating,
	"waitforremotecompletion": NspLinkProvisioningState_STATUS_WaitForRemoteCompletion,
}

// The NSP link state.
type NspLinkStatus_STATUS string

const (
	NspLinkStatus_STATUS_Approved     = NspLinkStatus_STATUS("Approved")
	NspLinkStatus_STATUS_Disconnected = NspLinkStatus_STATUS("Disconnected")
	NspLinkStatus_STATUS_Pending      = NspLinkStatus_STATUS("Pending")
	NspLinkStatus_STATUS_Rejected     = NspLinkStatus_STATUS("Rejected")
)

// Mapping from string to NspLinkStatus_STATUS
var nspLinkStatus_STATUS_Values = map[string]NspLinkStatus_STATUS{
	"approved":     NspLinkStatus_STATUS_Approved,
	"disconnected": NspLinkStatus_STATUS_Disconnected,
	"pending":      NspLinkStatus_STATUS_Pending,
	"rejected":     NspLinkStatus_STATUS_Rejected,
}
