// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_CommonSubResource_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of CommonSubResource_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForCommonSubResource_STATUS, CommonSubResource_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForCommonSubResource_STATUS runs a test to see if a specific instance of CommonSubResource_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForCommonSubResource_STATUS(subject CommonSubResource_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual CommonSubResource_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of CommonSubResource_STATUS instances for property testing - lazily instantiated by
// CommonSubResource_STATUSGenerator()
var commonSubResource_STATUSGenerator gopter.Gen

// CommonSubResource_STATUSGenerator returns a generator of CommonSubResource_STATUS instances for property testing.
func CommonSubResource_STATUSGenerator() gopter.Gen {
	if commonSubResource_STATUSGenerator != nil {
		return commonSubResource_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForCommonSubResource_STATUS(generators)
	commonSubResource_STATUSGenerator = gen.Struct(reflect.TypeOf(CommonSubResource_STATUS{}), generators)

	return commonSubResource_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForCommonSubResource_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForCommonSubResource_STATUS(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
}

func Test_NetworkSecurityPerimetersResourceAssociation_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersResourceAssociation_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersResourceAssociation_STATUS, NetworkSecurityPerimetersResourceAssociation_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersResourceAssociation_STATUS runs a test to see if a specific instance of NetworkSecurityPerimetersResourceAssociation_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersResourceAssociation_STATUS(subject NetworkSecurityPerimetersResourceAssociation_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersResourceAssociation_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersResourceAssociation_STATUS instances for property testing - lazily instantiated
// by NetworkSecurityPerimetersResourceAssociation_STATUSGenerator()
var networkSecurityPerimetersResourceAssociation_STATUSGenerator gopter.Gen

// NetworkSecurityPerimetersResourceAssociation_STATUSGenerator returns a generator of NetworkSecurityPerimetersResourceAssociation_STATUS instances for property testing.
// We first initialize networkSecurityPerimetersResourceAssociation_STATUSGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimetersResourceAssociation_STATUSGenerator() gopter.Gen {
	if networkSecurityPerimetersResourceAssociation_STATUSGenerator != nil {
		return networkSecurityPerimetersResourceAssociation_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_STATUS(generators)
	networkSecurityPerimetersResourceAssociation_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersResourceAssociation_STATUS{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_STATUS(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_STATUS(generators)
	networkSecurityPerimetersResourceAssociation_STATUSGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersResourceAssociation_STATUS{}), generators)

	return networkSecurityPerimetersResourceAssociation_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_STATUS(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_STATUS is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_STATUS(gens map[string]gopter.Gen) {
	gens["Properties"] = gen.PtrOf(NspAssociationProperties_STATUSGenerator())
	gens["SystemData"] = gen.PtrOf(SecurityPerimeterSystemData_STATUSGenerator())
}

func Test_NspAssociationProperties_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NspAssociationProperties_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNspAssociationProperties_STATUS, NspAssociationProperties_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNspAssociationProperties_STATUS runs a test to see if a specific instance of NspAssociationProperties_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForNspAssociationProperties_STATUS(subject NspAssociationProperties_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NspAssociationProperties_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NspAssociationProperties_STATUS instances for property testing - lazily instantiated by
// NspAssociationProperties_STATUSGenerator()
var nspAssociationProperties_STATUSGenerator gopter.Gen

// NspAssociationProperties_STATUSGenerator returns a generator of NspAssociationProperties_STATUS instances for property testing.
// We first initialize nspAssociationProperties_STATUSGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NspAssociationProperties_STATUSGenerator() gopter.Gen {
	if nspAssociationProperties_STATUSGenerator != nil {
		return nspAssociationProperties_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNspAssociationProperties_STATUS(generators)
	nspAssociationProperties_STATUSGenerator = gen.Struct(reflect.TypeOf(NspAssociationProperties_STATUS{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNspAssociationProperties_STATUS(generators)
	AddRelatedPropertyGeneratorsForNspAssociationProperties_STATUS(generators)
	nspAssociationProperties_STATUSGenerator = gen.Struct(reflect.TypeOf(NspAssociationProperties_STATUS{}), generators)

	return nspAssociationProperties_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForNspAssociationProperties_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNspAssociationProperties_STATUS(gens map[string]gopter.Gen) {
	gens["AccessMode"] = gen.PtrOf(gen.OneConstOf(AssociationAccessMode_STATUS_Audit, AssociationAccessMode_STATUS_Enforced, AssociationAccessMode_STATUS_Learning))
	gens["HasProvisioningIssues"] = gen.PtrOf(gen.AlphaString())
	gens["ProvisioningState"] = gen.PtrOf(gen.OneConstOf(
		NspProvisioningState_STATUS_Accepted,
		NspProvisioningState_STATUS_Creating,
		NspProvisioningState_STATUS_Deleting,
		NspProvisioningState_STATUS_Failed,
		NspProvisioningState_STATUS_Succeeded,
		NspProvisioningState_STATUS_Updating))
}

// AddRelatedPropertyGeneratorsForNspAssociationProperties_STATUS is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNspAssociationProperties_STATUS(gens map[string]gopter.Gen) {
	gens["PrivateLinkResource"] = gen.PtrOf(CommonSubResource_STATUSGenerator())
	gens["Profile"] = gen.PtrOf(CommonSubResource_STATUSGenerator())
}
