// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

type NetworkSecurityPerimetersResourceAssociation_STATUS struct {
	// Id: Fully qualified resource ID for the resource. E.g.
	// "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id *string `json:"id,omitempty"`

	// Name: The name of the resource
	Name *string `json:"name,omitempty"`

	// Properties: Properties of the NSP resource association.
	Properties *NspAssociationProperties_STATUS `json:"properties,omitempty"`

	// SystemData: Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SecurityPerimeterSystemData_STATUS `json:"systemData,omitempty"`

	// Type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`
}

type NspAssociationProperties_STATUS struct {
	// AccessMode: Access mode on the association.
	AccessMode *AssociationAccessMode_STATUS `json:"accessMode,omitempty"`

	// HasProvisioningIssues: Specifies if there are provisioning issues
	HasProvisioningIssues *string `json:"hasProvisioningIssues,omitempty"`

	// PrivateLinkResource: The PaaS resource to be associated.
	PrivateLinkResource *CommonSubResource_STATUS `json:"privateLinkResource,omitempty"`

	// Profile: Profile id to which the PaaS resource is associated.
	Profile *CommonSubResource_STATUS `json:"profile,omitempty"`

	// ProvisioningState: The provisioning state of the resource  association resource.
	ProvisioningState *NspProvisioningState_STATUS `json:"provisioningState,omitempty"`
}

// Access mode on the association.
type AssociationAccessMode_STATUS string

const (
	AssociationAccessMode_STATUS_Audit    = AssociationAccessMode_STATUS("Audit")
	AssociationAccessMode_STATUS_Enforced = AssociationAccessMode_STATUS("Enforced")
	AssociationAccessMode_STATUS_Learning = AssociationAccessMode_STATUS("Learning")
)

// Mapping from string to AssociationAccessMode_STATUS
var associationAccessMode_STATUS_Values = map[string]AssociationAccessMode_STATUS{
	"audit":    AssociationAccessMode_STATUS_Audit,
	"enforced": AssociationAccessMode_STATUS_Enforced,
	"learning": AssociationAccessMode_STATUS_Learning,
}

// Reference to another subresource.
type CommonSubResource_STATUS struct {
	// Id: Resource ID.
	Id *string `json:"id,omitempty"`
}
