// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_CommonSubResource_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of CommonSubResource via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForCommonSubResource, CommonSubResourceGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForCommonSubResource runs a test to see if a specific instance of CommonSubResource round trips to JSON and back losslessly
func RunJSONSerializationTestForCommonSubResource(subject CommonSubResource) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual CommonSubResource
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of CommonSubResource instances for property testing - lazily instantiated by CommonSubResourceGenerator()
var commonSubResourceGenerator gopter.Gen

// CommonSubResourceGenerator returns a generator of CommonSubResource instances for property testing.
func CommonSubResourceGenerator() gopter.Gen {
	if commonSubResourceGenerator != nil {
		return commonSubResourceGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForCommonSubResource(generators)
	commonSubResourceGenerator = gen.Struct(reflect.TypeOf(CommonSubResource{}), generators)

	return commonSubResourceGenerator
}

// AddIndependentPropertyGeneratorsForCommonSubResource is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForCommonSubResource(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
}

func Test_NetworkSecurityPerimetersResourceAssociation_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NetworkSecurityPerimetersResourceAssociation_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNetworkSecurityPerimetersResourceAssociation_Spec, NetworkSecurityPerimetersResourceAssociation_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNetworkSecurityPerimetersResourceAssociation_Spec runs a test to see if a specific instance of NetworkSecurityPerimetersResourceAssociation_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForNetworkSecurityPerimetersResourceAssociation_Spec(subject NetworkSecurityPerimetersResourceAssociation_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NetworkSecurityPerimetersResourceAssociation_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NetworkSecurityPerimetersResourceAssociation_Spec instances for property testing - lazily instantiated
// by NetworkSecurityPerimetersResourceAssociation_SpecGenerator()
var networkSecurityPerimetersResourceAssociation_SpecGenerator gopter.Gen

// NetworkSecurityPerimetersResourceAssociation_SpecGenerator returns a generator of NetworkSecurityPerimetersResourceAssociation_Spec instances for property testing.
// We first initialize networkSecurityPerimetersResourceAssociation_SpecGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NetworkSecurityPerimetersResourceAssociation_SpecGenerator() gopter.Gen {
	if networkSecurityPerimetersResourceAssociation_SpecGenerator != nil {
		return networkSecurityPerimetersResourceAssociation_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_Spec(generators)
	networkSecurityPerimetersResourceAssociation_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersResourceAssociation_Spec{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_Spec(generators)
	AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_Spec(generators)
	networkSecurityPerimetersResourceAssociation_SpecGenerator = gen.Struct(reflect.TypeOf(NetworkSecurityPerimetersResourceAssociation_Spec{}), generators)

	return networkSecurityPerimetersResourceAssociation_SpecGenerator
}

// AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_Spec(gens map[string]gopter.Gen) {
	gens["Name"] = gen.AlphaString()
}

// AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_Spec is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNetworkSecurityPerimetersResourceAssociation_Spec(gens map[string]gopter.Gen) {
	gens["Properties"] = gen.PtrOf(NspAssociationPropertiesGenerator())
}

func Test_NspAssociationProperties_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of NspAssociationProperties via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForNspAssociationProperties, NspAssociationPropertiesGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForNspAssociationProperties runs a test to see if a specific instance of NspAssociationProperties round trips to JSON and back losslessly
func RunJSONSerializationTestForNspAssociationProperties(subject NspAssociationProperties) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual NspAssociationProperties
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of NspAssociationProperties instances for property testing - lazily instantiated by
// NspAssociationPropertiesGenerator()
var nspAssociationPropertiesGenerator gopter.Gen

// NspAssociationPropertiesGenerator returns a generator of NspAssociationProperties instances for property testing.
// We first initialize nspAssociationPropertiesGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func NspAssociationPropertiesGenerator() gopter.Gen {
	if nspAssociationPropertiesGenerator != nil {
		return nspAssociationPropertiesGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNspAssociationProperties(generators)
	nspAssociationPropertiesGenerator = gen.Struct(reflect.TypeOf(NspAssociationProperties{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForNspAssociationProperties(generators)
	AddRelatedPropertyGeneratorsForNspAssociationProperties(generators)
	nspAssociationPropertiesGenerator = gen.Struct(reflect.TypeOf(NspAssociationProperties{}), generators)

	return nspAssociationPropertiesGenerator
}

// AddIndependentPropertyGeneratorsForNspAssociationProperties is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForNspAssociationProperties(gens map[string]gopter.Gen) {
	gens["AccessMode"] = gen.PtrOf(gen.OneConstOf(AssociationAccessMode_Audit, AssociationAccessMode_Enforced, AssociationAccessMode_Learning))
}

// AddRelatedPropertyGeneratorsForNspAssociationProperties is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForNspAssociationProperties(gens map[string]gopter.Gen) {
	gens["PrivateLinkResource"] = gen.PtrOf(CommonSubResourceGenerator())
	gens["Profile"] = gen.PtrOf(CommonSubResourceGenerator())
}
