// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

// The Network Security Perimeter resource
type NetworkSecurityPerimeter_STATUS struct {
	// Id: Fully qualified resource ID for the resource. E.g.
	// "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
	Id *string `json:"id,omitempty"`

	// Location: The geo-location where the resource lives
	Location *string `json:"location,omitempty"`

	// Name: The name of the resource
	Name *string `json:"name,omitempty"`

	// Properties: The network security perimeter properties
	Properties *NetworkSecurityPerimeterProperties_STATUS `json:"properties,omitempty"`

	// SystemData: Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SecurityPerimeterSystemData_STATUS `json:"systemData,omitempty"`

	// Tags: Resource tags.
	Tags map[string]string `json:"tags,omitempty"`

	// Type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string `json:"type,omitempty"`
}

// Properties of network security perimeter.
type NetworkSecurityPerimeterProperties_STATUS struct {
	// PerimeterGuid: perimeter guid of the network security perimeter.
	PerimeterGuid *string `json:"perimeterGuid,omitempty"`

	// ProvisioningState: The provisioning state of the scope assignment resource.
	ProvisioningState *NspProvisioningState_STATUS `json:"provisioningState,omitempty"`
}

// Metadata pertaining to creation and last modification of the resource.
type SecurityPerimeterSystemData_STATUS struct {
	// CreatedAt: The timestamp of resource creation (UTC).
	CreatedAt *string `json:"createdAt,omitempty"`

	// CreatedBy: The identity that created the resource.
	CreatedBy *string `json:"createdBy,omitempty"`

	// CreatedByType: The type of identity that created the resource.
	CreatedByType *CreatedByType_STATUS `json:"createdByType,omitempty"`

	// LastModifiedAt: The timestamp of resource last modification (UTC)
	LastModifiedAt *string `json:"lastModifiedAt,omitempty"`

	// LastModifiedBy: The identity that last modified the resource.
	LastModifiedBy *string `json:"lastModifiedBy,omitempty"`

	// LastModifiedByType: The type of identity that last modified the resource.
	LastModifiedByType *CreatedByType_STATUS `json:"lastModifiedByType,omitempty"`
}

// The type of identity that created the resource.
type CreatedByType_STATUS string

const (
	CreatedByType_STATUS_Application     = CreatedByType_STATUS("Application")
	CreatedByType_STATUS_Key             = CreatedByType_STATUS("Key")
	CreatedByType_STATUS_ManagedIdentity = CreatedByType_STATUS("ManagedIdentity")
	CreatedByType_STATUS_User            = CreatedByType_STATUS("User")
)

// Mapping from string to CreatedByType_STATUS
var createdByType_STATUS_Values = map[string]CreatedByType_STATUS{
	"application":     CreatedByType_STATUS_Application,
	"key":             CreatedByType_STATUS_Key,
	"managedidentity": CreatedByType_STATUS_ManagedIdentity,
	"user":            CreatedByType_STATUS_User,
}

// The current provisioning state.
type NspProvisioningState_STATUS string

const (
	NspProvisioningState_STATUS_Accepted  = NspProvisioningState_STATUS("Accepted")
	NspProvisioningState_STATUS_Creating  = NspProvisioningState_STATUS("Creating")
	NspProvisioningState_STATUS_Deleting  = NspProvisioningState_STATUS("Deleting")
	NspProvisioningState_STATUS_Failed    = NspProvisioningState_STATUS("Failed")
	NspProvisioningState_STATUS_Succeeded = NspProvisioningState_STATUS("Succeeded")
	NspProvisioningState_STATUS_Updating  = NspProvisioningState_STATUS("Updating")
)

// Mapping from string to NspProvisioningState_STATUS
var nspProvisioningState_STATUS_Values = map[string]NspProvisioningState_STATUS{
	"accepted":  NspProvisioningState_STATUS_Accepted,
	"creating":  NspProvisioningState_STATUS_Creating,
	"deleting":  NspProvisioningState_STATUS_Deleting,
	"failed":    NspProvisioningState_STATUS_Failed,
	"succeeded": NspProvisioningState_STATUS_Succeeded,
	"updating":  NspProvisioningState_STATUS_Updating,
}
